// @codekit-prepend "arush/browser-detect.js"
// @codekit-prepend "male/libs/moment-1.7.2.js"
// @codekit-prepend "arush/swipe.js"
// @codekit-prepend "arush/checkout/checkoutHelpers.js"
// @codekit-prepend "male/modules/parse-core.js"