<!-- <div id="top" class="keep-calm-signup-container">
  <?php // echo $this->getChildHtml('landing_header'); ?>
</div> -->
<div class="chisel-block header">
  <div class="container">
    <div class="logo-container">
      <a id="logo" href="/" class="header-logo">
        <img class="gift-logo ani fadeIn scale-with-grid" alt="BRANDiD logo" src="<?php echo $this->getSkinUrl('images/logo-beta.png')?>" title="BRANDiD Logo"/>
      </a>
    </div>
  </div>
</div>
<div ng-app="ngMaleApp" ng-controller="MainController" class="container maleApp withShadow drawerOpen-{{drawerOpen}}">

  <div  class="drawer-holder shadow-trick-holder" >
    <div class="drawer shadow-trick right">

      <a href="#/section/intro" class="button-overlay over-male" style="width:100%">
        <div class="male-round">
          <div class="male-holder">
            <div id="male-colour" class="male-back">
            </div>
            <div id="male-loader" class="male-loader">
            </div>
            
            <img src="<?php echo $this->getSkinUrl('images/male/male-transparent@2x.png'); ?>" alt="M.A.L.E." class="male-round ani" title="feed the male"/>
            <div class="male-label-box">
              <span id="male-label">M.A.L.E.</span>
            </div>
          </div>
        </div>
      </a>

      <ul>
        <li class="menu-section trans ani open" ng-repeat="menuItem in menu">
          <!-- <a class="button-overlay" href="#/section/{{menuItem.section}}"> -->
            <div class="shadow-trick-holder">
              <div class="chisel-block shadow-trick bottom">
               <span>{{menuItem.title}}</span> 
              </div>
            </div>
          <!-- </a> -->
          <div ng-include src="menuItem.submenuTemplate"></div>

        </li>
      </ul>
    </div>
  </div>

  <div class="rest-of-page">
    <div class="controls chisel-block clearfix" ng-controller="DetailControlsController">
      <div class="controls-content clearfix">
        <a ng-click="$parent.drawerOpen = !$parent.drawerOpen" class="button-overlay">
          <div class="menu-button">
          </div>
        </a>
      </div>
    <!-- TODO: pagination control -->
    </div>

    <!-- detail loads here -->

    <div id="detailView" ng-view>
    </div>
  </div>


  <!-- Workaround to dynamically load :primaryNav/:secondaryNav templates -->
  <script type=text/ng-template id=detailViewProxy.html>
      <div ng-include src="detailTemplate"></div>
  </script>
  <script type=text/ng-template id=sectionProxy.html>
      <div ng-include src="sectionTemplate"></div>
  </script>
  <script type=text/ng-template id=categoryProxy.html>
      <div ng-include src="categoryTemplate"></div>
  </script>

  <!-- Inline Templates (Partials) -->

  <!-- garms submenu is special because it will contain what the user has selected to configure, they might not want to configure everything -->
  <script type=text/ng-template id=menu/catalogItems.html>
    <div ng-repeat="chosenItem in chosenItems"  class="ani big-block clearfix" ng-class="{selected: chosenItem.category==$parent.routeParams.category}">
      <a href="{{catalogItem.link}}" class="button-overlay">
        <div class="icon {{chosenItem.cssClass}}"></div>
        <div class="ani arrow-left"></div>
      </a>
    </div>
  </script>

  <!-- this is for all other submenu items -->
  <script type=text/ng-template id=menu/menuItems.html>
    <div ng-repeat="submenuItem in menuItem.submenuItems"  class="ani big-block clearfix" ng-class="{selected: submenuItem.cssClass==selectedSubmenuItem}">
      
      <!-- the link here skips the dashboard, because no need for a dashboard for simple questions -->
      <a href="{{submenuItem.link}}" class="button-overlay">
        <div class="icon {{submenuItem.cssClass}}">{{submenuItem.label}}</div>
        <div class="ani arrow-left"></div>
      </a>
    </div>
  </script>

  <script type=text/ng-template id=start.html>
      <div class="">M.A.L.E. Beginning</div>
  </script>
  <script type=text/ng-template id=section/garms/category/intro.html>
      <div class="slide-container">
        <div class="curved-white-block withShadow withRadius fadeIn ani">
          <span id="intro">{{question}}</span>
        </div>

        <div class="withRadius male-button-holder" ng-repeat="answer in answers">

          <a ng-click="selectItem($index)" class="button-overlay convert secondary">
            <div class="icon ">{{answer.label}}</div>
          </a>

        </div>
        
      </div>
  </script>

  <script type=text/ng-template id=section/garms/category/boxers/question/brands.html>
      <div class="slide-container">
        <div class="curved-white-block withShadow withRadius fadeIn ani">
          <span id="brands">What brands do you want?<br/>Hint: You can type in your favourite brand and we guarantee we will find it for you</span>
        </div>
        <div class="answers">
            <a class="convert secondary brands-auto-populator" ng-click="chooseValueBrands('boxers')">
              <div class="v-outer-container">

                <div class="v-inner-container">

                  <span class="v-aligned-element">
                    Value Brands <br/><span class="smaller-text">{{valuePriceLower | currency: "£"}} - {{valuePriceUpper | currency: "£"}}</span>
                  </span>
                
                </div>

              </div>

            </a>

            <a class="convert secondary brands-auto-populator" ng-click="choosePremiumBrands('boxers')">
              <div class="v-outer-container">

                <div class="v-inner-container">

                  <span class="v-aligned-element">
                    Premium Brands <br/><span class="smaller-text">{{premiumPriceLower | currency: "£"}} - {{premiumPriceUpper | currency: "£"}}</span>
                  </span>
                
                </div>

              </div>

            </a>

            <a class="convert secondary brands-auto-populator" ng-click="chooseSkateBrands('boxers')">
              <div class="v-outer-container">

                <div class="v-inner-container">

                  <span class="v-aligned-element">
                    Skate Brands <br/><span class="smaller-text">{{skatePriceLower | currency: "£"}} - {{skatePriceUpper | currency: "£"}}</span>
                  </span>
                
                </div>

              </div>

            </a>

        </div>

        <div class="tag-section">
          <input class="tags-field" ui-select2="{tags:brands}" ng-model="$parent.selectedBrands" />
        </div>

        <div class="next-question-button-section">
          <a class="convert" ng-click="nextQuestion('boxers')">
                Next
          </a>
        </div>

      </div>
  </script>

  <script type=text/ng-template id=section/garms.html>
      <div class="">This is the beginning of garms</div>
  </script>
  <script type=text/ng-template id=section/extras.html>
      <div class="">This is the beginning of extras</div>
  </script>

  <script type=text/ng-template id=garms/dashboard.html>
      <div id="dashboard" class="curved-white-block withShadow withRadius fadeIn ani">

          <div class="question chisel-block" ng-repeat="question in questions">
            <a class="list-item" ng-click="$parent.slideToQuestion(question.id)">
              <i class="q-icon icon-check-empty"></i>{{question.question}}<i class="q-icon icon-chevron-right"></i>
            </a>
          </div>

      </div>
  </script>


  <script type=text/ng-template id=garms/boxers/1.html>
      <div class="page">First page</div>
  </script>

  <script type=text/ng-template id=garms/boxers/2.html>
      <div class="page">Second Page</div>
  </script>

  <script type=text/ng-template id=garms/boxers/3.html>
      <div class="page">Third Page</div>
  </script>
</div> <!-- ng-app -->


