<!-- <div id="top" class="keep-calm-signup-container">
  <?php // echo $this->getChildHtml('landing_header'); ?>
</div> -->
<div ng-app="ngMaleApp" ng-controller="MainController" class="container maleApp withShadow drawerOpen-{{drawerOpen}}">

  <div  class="drawer-holder shadow-trick-holder" >
    <div class="drawer shadow-trick right">
      <ul>
        <li class="menu-section" ng-repeat="menuItem in menu">

          <div class="shadow-trick-holder">
            <div class="chisel-block shadow-trick bottom">
             <span>{{menuItem.title}}</span> 
            </div>
          </div>
          
          <div ng-include src="menuItem.submenuTemplate"></div>

        </li>
      </ul>
    </div>
  </div>

  <div class="rest-of-page">
    <div class="controls chisel-block clearfix" ng-controller="DetailControlsController">
      <div class="controls-content clearfix">
        <a ng-click="$parent.drawerOpen = !$parent.drawerOpen" class="button-overlay">
          <div class="menu-button">
          </div>
        </a>
      </div>
    <!-- TODO: pagination control -->
    </div>

    <!-- detail loads here -->

    <div ng-view>
    </div>
  </div>


  <!-- Workaround to dynamically load :primaryNav/:secondaryNav templates -->
  <script type=text/ng-template id=detailViewProxy.html>
      <div ng-include src="detailTemplate"></div>
  </script>

  <!-- Inline Templates (Partials) -->
  <script type=text/ng-template id=menu/catalogItems.html>
    <div ng-repeat="catalogItem in user.configuredItems"  class="ani big-block clearfix" ng-class="{selected: catalogItem.category==$parent.routeParams.category}">
      <a href="#/section/{{menuItem.section}}/category/{{catalogItem.category}}/question/dashboard" class="button-overlay">
        <div class="icon {{catalogItem.cssClass}}"></div>
        <div class="ani arrow-left"></div>
      </a>
    </div>
  </script>

  <script type=text/ng-template id=start.html>
      <div class="">M.A.L.E. Beginning</div>
  </script>

  <script type=text/ng-template id=garms/dashboard.html>
      <div class="curved-white-block withShadow withRadius fadeIn ani">

          <div class="question chisel-block" ng-repeat="question in questions">
            <a class="list-item" href="#">
              <i class="q-icon icon-check-empty"></i>{{question.question}}<i class="q-icon icon-chevron-right"></i>
            </a>
              
          </div>

      </div>
  </script>


  <script type=text/ng-template id=garms/boxers/1.html>
      <div class="page">First page</div>
  </script>

  <script type=text/ng-template id=garms/boxers/2.html>
      <div class="page">Second Page</div>
  </script>

  <script type=text/ng-template id=garms/boxers/3.html>
      <div class="page">Third Page</div>
  </script>
</div> <!-- ng-app -->


