<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gigya Socialize Magento Extension</title>

<style type="text/css">
body { 
	padding: 20px;
	background-color: #E6E6E6;
	color: #2F2F2F;
	
}
</style>
</head>

<body>
	<script>
	document.location.replace('http://wiki.gigya.com/050_CMS_Modules/050_Magento');
	</script>
	<div id="header">
	<h1>Gigya Socialize Magento Extension</h1>
	</div>
	
	<div id="main">
	
	
	<h2 id="socialize">Gigya Socialize</h2>
	<p>
		Gigya Socialize is a set of APIs from Gigya that enable customers to log onto third-party websites, applications and mobile devices with their social identity.
		In other words, this extension enables one-click customer registration and login with their Facebook/Twitter/Google... account.
		It is recommanded that You go over all the setings and decide which ones you want before enableing the extension or any of the plugins within it.
	</p>

	<h2 id="setup">Application setup</h2>
	<p>
		For Gigya Socialize to work you need to register at gigya.com and obtain an API key and and a secret key. 
	</p>
	<p>
		Once you obtain the two keys navigate to Magento Administration and copy/paste them to appropriate fields under Configuration-Gigya Socialize.
	</p>

	<h2 id="releasenotes">Release notes</h2>
	<p>
		v.1.0.0 <br />
		First public release. Compatible with Magento CE 1.4.2 to 1.5.0.1
	</p>
	
	<h2 id="about">About</h2>
	<p>
		author:     Eyal Peleg For Gigya Inc.<br />
		copyright:  Copyright (c) 2010 Gigya.com ltd. (<a href="http://gigya.com">http://gigya.com</a>) <br />
	</p>
	<br />
	</div>
	
	<div id="footer">
		<p>&copy;<a href="http://gigya.com">Gigya.com</a> 2010</p>
	</div>
	
</body>
</html>