<?php if(getOlarkOn() && getOlarkPaymentpage()) { 

	$name = Mage::getSingleton('customer/session')->getCustomer()->getFirstname(); 
	$email = Mage::getSingleton('customer/session')->getCustomer()->getEmail(); 
	
	$name = strtolower($name);
	$name = ucwords($name);
		
	$identity = $name . " | " . $email;
	?>
	
<script type="text/javascript">
olark('api.chat.updateVisitorNickname', {
    snippet: "<?php echo $identity; ?>"
});
</script>

<?php } ?>