<?php  if(Mage::getStoreConfig('mixpanel/track/mixpanel_on')) {
?>
	<!-- start Mixpanel BRANDiD code -->
	<script type="text/javascript">
		

		<?php /* Identify user */
		if(Mage::getSingleton('customer/session')->isLoggedIn()) {
			$customer = Mage::getSingleton('customer/session')->getCustomer();
			$customerID = $customer->getId();
			$customerEmail = $customer->getEmail();

			// we use group id to tell if a customer has paid us before or not
			$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
			if($groupId != 1) {
				$payer = 'has purchased';
			}
			else {
				$payer = 'not purchased';
			}

		 ?>
		<?php /* Otherwise set as guest */
		} else {
			$customerID = 'guest';
			$customerEmail = 'guest';
			$payer = 'guest';
		} ?>

		
		<?php /* Find original referer */

			if(!isset($_SESSION['referer'])) { //has it been set before?
				//get the referrer
				if (isset($_SERVER['HTTP_REFERER'])) {
					$referer = $_SERVER['HTTP_REFERER'];
				} else {
					$referer = "unknown";
				}
				//save it in a session
				$_SESSION['referer'] = $referer; // store session data

			}
			else {
				$referer = $_SESSION['referer']; // store session data
			}

		?>
		

		<?php /* What page is this */
			
			// cms page
			if (Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') {
			    $pageType = "cms";
			    $pageTitle = Mage::getSingleton('cms/page')->getTitle();
			}

			// product must come before category, so else if doesnt trigger category whilst on product page
			else if($product = Mage::registry('current_product')) { 
				$pageType = "product";
				$pageTitle = $product->getName();
				$productSku = $product->getSku();
				$productCat = Mage::registry('current_category')->getName();
				
				/* start js */ ?> 

				var page_properties = {
				    'product_title': "<?php echo $pageTitle; ?>",
				    'product_sku': "<?php echo $productSku; ?>",
				    'product_category': "<?php echo $productCat; ?>"
				};

				mixpanel.track('ProductViewed', page_properties);

				<?php /* end js */
			}

			// category
			else if($catalog = Mage::app()->getRequest()->getControllerName() == 'category') { 
				$pageType = "category";
			    $pageTitle = Mage::registry('current_category')->getUrlKey(); // get name doesn't help cos its always 'Plans'

			    /* start js */ ?> 

				var page_properties = {
				    'category_title': "<?php echo $pageTitle; ?>",
				};

				mixpanel.track('CategoryViewed', page_properties);

				<?php /* end js */

			}
			
			// custom gift page
			else if($this->getRequest()->getActionName() == 'getgifted') {
				$pageType = "landing";
				$pageTitle = "gift";
			}

			// custom home page
			else if($this->getRequest()->getActionName() == 'signmeup') { 
				$pageType = "landing";
				$pageTitle = "home";
			}

			// catchall
			else {
				$pageType = $this->getRequest()->getModuleName();
				$pageTitle = $this->getRequest()->getControllerName();
			}

		?>
		// set global properties for every event
	 	mixpanel.register({
			'paying customer': '<?php echo $payer ?>'
	 	});

		// track original referrer
		mixpanel.register_once({
			'first touch landing page': window.location.href,
			'first touch referrer': '<?php echo $referer; ?>'
	 	});

		// who is it
		

		mixpanel.identify("<?php echo $customerID; ?>");
		mixpanel.name_tag('<?php echo $customerEmail; ?>');


		// custom actions
		document.observe('dom:loaded', function(){
			
			// navigating around homepage
			mixpanel.track_links(
				".header-button a",
				"soft nav clicked",
				function(ele) {
					return {
						'button_id': jQuery(ele).attr('id'),
						'page_type': "<?php echo $pageType; ?>",
						'page_title': "<?php echo $pageTitle; ?>",
						'mp_note': "User clicked on " + jQuery(ele).attr('id') + " on the <?php echo $pageType; ?> page"
					}
				}
			);
			
			// view plans
			mixpanel.track_links(
				"#header-convert",
				"viewed plans",
				function(ele) {
					return {
						'button_id': jQuery(ele).attr('id'),
						'button_size': "small header button",
						'page_type': "<?php echo $pageType; ?>",
						'page_title': "<?php echo $pageTitle; ?>",
						'mp_note': "User clicked on View Plans from the header nav on the <?php echo $pageType; ?> page"
					}
				}
			);
			
			// view plans main button
			mixpanel.track_links(
				"#big-body-convert",
				"viewed plans",
				function(ele) {
					return {
						'button_id': jQuery(ele).attr('id'),
						'button_size': "big body button",
						'page_type': "<?php echo $pageType; ?>",
						'page_title': "<?php echo $pageTitle; ?>",
						'mp_note': "User clicked on View Plans from the body of the <?php echo $pageType; ?> page"
					}
				}
			);

			mixpanel.track_forms(
				"#form-validate.register-email",
				"completed form",
				function(ele) {
					return {
						'form_class': jQuery(ele).attr('class'),
						'page_type': "<?php echo $pageType; ?>",
						'page_title': "<?php echo $pageTitle; ?>",
						'mp_note': "User filled out a form on the <?php echo $pageType; ?> page"
					}
				}
			);

		});


			
	</script>
	<!-- end Mixpanel BRANDiD code -->

<?php } ?>