<!-- BEGIN Gigya Socialize plugin Comments -->
<?php if ($this->isEnabled() && $this->isConfigured()) {
	if ($this->hasData('productCommentsCategoryID')) {
		$CommentsCategoryID=$this->getData('productCommentsCategoryID');
	}
	else {
		$CommentsCategoryID=$this->getSetting('product_comments_categoryID');
	}
	$divID="commentsDiv_$CommentsCategoryID";
?>
	<?php echo('<style>#'.$divID.' div.gig-commentBox td {vertical-align:middle}</style>')?> 
	<div id="<?php echo($divID)?>"></div>
	<script type="text/javascript">
	    var showComments_params =
	    {
	        categoryID: <?php echo $CommentsCategoryID ?>
	        ,streamID: '<?php echo $this->getStreamID() ?>'
	        ,containerID: '<?php echo $divID ?>'
		    ,onSiteLoginClicked:function(e) {
			    document.location.replace('<?php echo Mage::helper('socialize')->getLoginUrl() ?>');	
		    }
		    ,onCommentSubmitted:function(e) {
				//e.commentText has the userMessage
		    	var Comment_useraction=new gigya.services.socialize.UserAction();
				<?php
					$mediaBlock=$this->getLayout()->getBlock('product.info.media');
					$product=$mediaBlock->getProduct();
					$images=$mediaBlock->getGalleryImages();
					if (count($images) > 0) {
						$image=$images->getFirstItem();
				?>
				var image = {
				        type: 'image',
				        src: <?php echo Mage::helper('socialize')->toJSStringLiteral ($image->geturl()); ?>,
				        href: <?php echo Mage::helper('socialize')->toJSStringLiteral (Mage::helper('socialize')->getCurrentUrl()); ?>
				      };
				Comment_useraction.addMediaItem(image);
				
				<?php
					}
				?>
				
				Comment_useraction.setUserMessage('<?php echo $this->__('Commented on:') ?>'); 
				Comment_useraction.setTitle(<?php echo Mage::helper('socialize')->toJSStringLiteral($product->getMetaTitle()); ?>);
				Comment_useraction.setDescription('');//< ? php echo json_encode($product->getDescription()); ? >);

				Comment_useraction.setLinkBack(<?php echo Mage::helper('socialize')->toJSStringLiteral(Mage::helper('socialize')->getCurrentUrl()); ?>);

			    gigya.services.socialize.publishUserAction(conf,{scope:'internal',privacy:'public',userAction:Comment_useraction});
		    }
	    };
	    
	    <?php echo $this->getAdvancedSettingsScript('showComments_params'); ?>
	    showComments_params.context='commentsPlugin';
	    gigya.services.socialize.showCommentsUI(conf,showComments_params);
	</script>
<?php
}
else {
?>
	<!-- Comments are either disabled or not configured properly -->
<?php 
}
?> 		
<!-- End Gigya Socialize plugin Comments-->