<!-- BEGIN Gigya Socialize plugin Login -->
<?php if ($this->isEnabled() && $this->isConfigured()) {
?>
	<script type="text/javascript">
	var login_params=
	{
		useHTML: 'true'
		,showTermsLink: 'false'
		,width: <?php echo Mage::helper('socialize')->toJSStringLiteral($this->getSetting('width')); ?>
		,height: <?php echo Mage::helper('socialize')->toJSStringLiteral($this->getSetting('height')); ?>
		,UIConfig: '<config><body><controls><snbuttons buttonsize="35"></snbuttons></controls></body></config>'
		,buttonsStyle: <?php echo Mage::helper('socialize')->toJSStringLiteral($this->getSetting('button_style')); ?>
		,containerID: 'gigyaLoginPluginDiv'
		,redirectURL: '<?php echo $this->getPostActionUrl() ?>'
		,hideGigyaLink:'true'
		,pendingRegistration:'true'
	}
	<?php echo $this->getAdvancedSettingsScript('login_params'); ?>
	login_params.context='loginPlugin';	
	</script>
	<div id="gigyaLoginPluginDiv"></div>
	<script type="text/javascript">
	   gigya.services.socialize.showLoginUI(conf,login_params);
	</script>
<?php
}
else {
?>
	<!-- Socialize login is either disabled or not configured properly -->
<?php 
}
?> 	
<!-- END Gigya Socialize plugin Login -->