<!-- BEGIN Gigya Socialize plugin ReactionsBar -->
<?php if ($this->isEnabled() && $this->isConfigured()) {
	$divID="gs4m_reactionsBar_Div";
?>
	<script type="text/javascript">
	   <?php if ($this->getSetting('repositionUI')) { ?>	
			   var gs4m_parentContainerCollection=$$('<?php echo ($this->getSetting('repositionUISelector')) ?>');
			   if (gs4m_parentContainerCollection.length>0) {
				   var <?php echo($divID)?> = new Element('div',{id:'<?php echo($divID)?>'});
		       	   gs4m_parentContainerCollection[0].insert(<?php echo($divID)?>);
			   }
				else {
				   document.write('<div id="<?php echo($divID)?>"></div>');
				}
		<?php }
		      else { //No repositioning 
		?>
			<div id="<?php echo($divID)?>"></div>
		<?php 
			  }
		?>

		var usedDefaultReactions=<?php echo ($this->getJSONMapForUsedDefaultReactions())?>;
		
		var selfDefinedReactionsArray=<?php echo ($this->getJSONArrayofSelfDefinedReactions())?>;
		var selfDefinedReactionsMap={};
		var iReaction;
		var reactionId;
		for (iReaction=0;iReaction<selfDefinedReactionsArray.length;iReaction++) {
			var selfDefinedReaction=selfDefinedReactionsArray[iReaction];
			if (selfDefinedReaction.hasOwnProperty('ID')) {
				reactionId=selfDefinedReaction['ID']=selfDefinedReaction['ID'].toLowerCase();
				selfDefinedReactionsMap[reactionId]=selfDefinedReaction;
			}
		}
		
		var reactionsToUse='<?php echo ($this->getReactionIdList())?>';
		var reactionsIDs=reactionsToUse.split(',');
		var reactions=[];
		for (iReaction=0;iReaction<reactionsIDs.length;iReaction++) {
			reactionId=reactionsIDs[iReaction];
			if (selfDefinedReactionsMap.hasOwnProperty(reactionId)) {
				reactions.push(selfDefinedReactionsMap[reactionId]);
			}
			else if (usedDefaultReactions.hasOwnProperty(reactionId)) {
				reactions.push(usedDefaultReactions[reactionId]);
			}
		}
		var reactions_useraction=new gigya.services.socialize.UserAction();
		<?php
			$mediaBlock=$this->getLayout()->getBlock('product.info.media');
			$product=$mediaBlock->getProduct();
			$images=$mediaBlock->getGalleryImages();
			if (count($images) > 0) {
				$image=$images->getFirstItem();
		?>

		
		<?php
			//echo '/*';
			//var_dump($mediaBlock->getProduct()->debug());
			//echo '*/';
		?>
		
		
		var image = {
		        type: 'image',
		        src: <?php echo Mage::helper('socialize')->toJSStringLiteral ($image->geturl()); ?>,
		        href:<?php echo Mage::helper('socialize')->toJSStringLiteral (Mage::helper('socialize')->getCurrentUrl()); ?>
		      };
		reactions_useraction.addMediaItem(image);
		
		<?php
			}
			
		?>
		reactions_useraction.setTitle(<?php echo json_encode($product->getMetaTitle()); ?>);
		reactions_useraction.setDescription(<?php echo json_encode($product->getDescription()); ?>);
		reactions_useraction.setLinkBack(<?php echo Mage::helper('socialize')->toJSStringLiteral(Mage::helper('socialize')->getCurrentUrl()); ?>);
		
	    var showReactionsBarUI_params = {
			reactions:reactions
			,CID:'<?php echo ($this->getItemId())?>'
			,shotURLs:'always'	
			,userAction:reactions_useraction
			,itemID:'<?php echo ($this->getItemId())?>'	    	
	        ,containerID: '<?php echo $divID ?>'
		    ,showCounts:'top'
		    //Feed
		    ,scope:'<?php echo ($this->getSetting('scope'))?>'
		    ,privacy:'<?php echo ($this->getSetting('privacy'))?>'
			//< ? php echo($this->getAdvancedSettings());?> 
	    };
	    
	    <?php echo $this->getAdvancedSettingsScript('showReactionsBarUI_params'); ?>
	    showReactionsBarUI_params.context='reactionsBarPlugin';
	    gigya.services.socialize.showReactionsBarUI(conf,showReactionsBarUI_params);
	</script>
<?php
}
else {
?>
	<!-- ReactionsBar is either disabled or not configured properly -->
<?php 
}
?>
<!-- End Gigya Socialize plugin ReactionsBar-->