<!-- BEGIN Gigya Socialize plugin Recommendations -->
<?php if ($this->isEnabled() && $this->isConfigured()) {
	$wrapperDivID="gs4m_Recommendations_wrapper_div";
	$divID="gs4m_Recommendations_div";
?>
	<script type="text/javascript">
	   /* <?php echo ($this->getSetting('repositionUI')) ?> */	
	   <?php if ($this->getSetting('repositionUI')) { ?>	
			   var gs4m_parentContainerCollection=$$('<?php echo ($this->getSetting('repositionUISelector')) ?>');
			   if (gs4m_parentContainerCollection.length>0) {
				   var <?php echo($wrapperDivID)?> = new Element('div',{id:'<?php echo($wrapperDivID)?>'});
		       	   gs4m_parentContainerCollection[0].insert(<?php echo($wrapperDivID)?>)
			   }
				else {
				   document.write('<div id="<?php echo($wrapperDivID)?>"></div>');
				}
		<?php }
		      else { //No repositioning 
		?>
			document.write('<style>#<?php echo($wrapperDivID)?> #<?php echo($divID)?>_tabsTR td {text-align:center}</style><div id="<?php echo($wrapperDivID)?>"></div>');
		<?php 
			  }
		?>

		$('<?php echo($wrapperDivID)?>').update('<div class="block block-recommendations"><div class="block-title"><strong><span><?php echo $this->__('Recommendations') ?></span></strong></div><div id="<?php echo($divID)?>" class="block-content">'
);

		
	    var showFeedUI_params =
	    {
			userAction:new gigya.services.socialize.UserAction()
			,itemID:'<?php echo ($this->getItemId())?>'	    	
	        ,containerID: '<?php echo $divID ?>'
		    ,border:'0px solid white'
		    ,width:191
		    ,height:300
		    ,itemImageSize:'20'
		    //inject the userMessage 
		    ,item_title:'${item.userMessage} $IFDEFELSE("item.titleLink","itemTitleAsLink","itemTitleAsText")'
				    
	    };
	    <?php echo $this->getAdvancedSettingsScript('showFeedUI_params'); ?>
	    showFeedUI_params.context='recommendationsPlugin';
	    
	    gigya.services.socialize.showFeedUI(conf,showFeedUI_params);
	</script>
<?php
}
else {
?>
	<!-- Recommendations is either disabled or not configured properly -->
<?php 
}
?><!-- End Gigya Socialize plugin Recommendations-->