<!-- BEGIN Gigya Socialize plugin ShareLinks -->
<?php if ($this->isEnabled() && $this->isConfigured()) {
	$divID="gs4m_share_Div";
?>
	<script type="text/javascript">
	   <?php if ($this->getSetting('repositionUI')) { ?>	
			   var gs4m_parentContainerCollection=$$('<?php echo ($this->getSetting('repositionUISelector')) ?>');
			   if (gs4m_parentContainerCollection.length>0) {
				   var <?php echo($divID)?> = new Element('div',{id:'<?php echo($divID)?>'});
		       	   gs4m_parentContainerCollection[0].insert(<?php echo($divID)?>);
			   }
				else {
				   document.write('<div id="<?php echo($divID)?>"></div>');
				}
		<?php }
		      else { //No repositioning 
		?>
			</script>
			<div id="<?php echo($divID)?>"></div>
			<script type="text/javascript">
		<?php 
			  }
		?>
		
		var sharelinks_useraction=new gigya.services.socialize.UserAction();
		<?php
			$mediaBlock=$this->getLayout()->getBlock('product.info.media');
			$product=$mediaBlock->getProduct();
			$images=$mediaBlock->getGalleryImages();
			if (count($images) > 0) {
				$image=$images->getFirstItem();
		?>

		
		<?php
			//echo '/*';
			//var_dump($mediaBlock->getProduct()->debug());
			//echo '*/';
		?>
		
		//here		
		var image = {
		        type: 'image',
		        src: <?php echo Mage::helper('socialize')->toJSStringLiteral ($image->geturl()); ?>,
		        href:<?php echo Mage::helper('socialize')->toJSStringLiteral (Mage::helper('socialize')->getCurrentUrl()); ?>
		      };
		sharelinks_useraction.addMediaItem(image);
		<?php
			}
		?>
		
		sharelinks_useraction.setTitle(<?php echo json_encode($product->getMetaTitle()); ?>);
		sharelinks_useraction.setDescription(<?php echo json_encode($product->getDescription()); ?>);
		sharelinks_useraction.setLinkBack(<?php echo Mage::helper('socialize')->toJSStringLiteral(Mage::helper('socialize')->getCurrentUrl()); ?>);
		
		/*
			<?php $v=array('a'=>'/');echo json_encode($v); ?>
		*/
		
		
	    var showShareUI_params =
	    {
			CID:<?php echo ($this->getItemId())?>
			,shotURLs:'always'	
			,userAction:sharelinks_useraction
			,itemID:<?php echo json_encode($this->getItemId())?>
			,showEmailButton:'true'	    	
		    //Feed
		    ,scope:'external' // actual setting is <?php echo json_encode($this->getSetting('scope'))?> will use onShareDone if needed
		    ,privacy:<?php echo json_encode($this->getSetting('privacy'))?>
	    };
		<?php echo $this->getAdvancedSettingsScript('showShareUI_params'); ?>
		showShareUI_params.context='sharePlugin';
		
	    showShareUI_params_email =
	    {
			CID:<?php echo json_encode($this->getItemId())?>
			,shotURLs:'always'	
			,userAction:sharelinks_useraction
			,itemID:<?php echo json_encode($this->getItemId())?>
			,hideSidebar:'true'	    	
		    //Feed
			,showEmailButton:'true'
			,initialView:'email'
		    ,scope:'external' // actual setting is <?php echo json_encode($this->getSetting('scope'))?> will use onShareDone if needed 
		    ,privacy:<?php echo json_encode($this->getSetting('privacy'))?>
			<?php echo($this->getAdvancedSettings());?> 
	    }
		<?php echo $this->getAdvancedSettingsScript('showShareUI_params_email'); ?>
		showShareUI_params_email.context='sharePlugin';

	    <?php if ($this->getSetting('scope')=='both') { ?>
		    function onSendDoneHandler(e) {
			    //alert('onSendDoneHandler');
		    	var Share_useraction=new gigya.services.socialize.UserAction();
				<?php
					$mediaBlock=$this->getLayout()->getBlock('product.info.media');
					$product=$mediaBlock->getProduct();
					$images=$mediaBlock->getGalleryImages();
					if (count($images) > 0) {
						$image=$images->getFirstItem();
				?>
				//HERE
				var image = {
				        type: 'image',
				        src: <?php echo Mage::helper('socialize')->toJSStringLiteral ($image->geturl()); ?>,
				        href: <?php echo Mage::helper('socialize')->toJSStringLiteral (Mage::helper('socialize')->getCurrentUrl()); ?>
				      };
				Share_useraction.addMediaItem(image);
				
				<?php
					}
				?>
				
				Share_useraction.setUserMessage('<?php echo $this->__('Shared') ?>'); 
				Share_useraction.setTitle(<?php echo Mage::helper('socialize')->toJSStringLiteral($product->getMetaTitle()); ?>);
				Share_useraction.setDescription('');//< ? php echo json_encode($product->getDescription()); ? >);
	
				Share_useraction.setLinkBack(<?php echo Mage::helper('socialize')->toJSStringLiteral(Mage::helper('socialize')->getCurrentUrl()); ?>);
	
			    gigya.services.socialize.publishUserAction(conf,{scope:'internal',privacy:'public',userAction:Share_useraction});
		    }
	
		    showShareUI_params_email.onSendDone=showShareUI_params.onSendDone=onSendDoneHandler;
		
		<?php }?>
				
	    var emailToFriendLink=$$('p.email-friend a')[0];
	    if (emailToFriendLink!=null) {
	    	emailToFriendLink.href='#';
	    	emailToFriendLink.observe('click',function(){gigya.services.socialize.showShareUI(conf,showShareUI_params);return false;});
	    	emailToFriendLink.update('<?php echo $this->getShareLinkHTML(null);?>');
	    	emailToFriendLink.title='<?php echo $this->getShareLinkHTML('text') ?>';
	    	
	    	emailToFriendLink.insert({
		    	after:'&nbsp;&nbsp;<a title="<?php echo $this->getEmailLinkHTML('text') ?>"  href="#" onclick="gigya.services.socialize.showShareUI(conf,showShareUI_params_email);return false;"><?php echo $this->getEmailLinkHTML(null);?></a>'
	    	});
	    }
	    
	    
	</script>
	<!-- a href="#" onclick="gigya.services.socialize.showShareUI(conf,showShareUI_params);return false;"><?php echo $this->getShareLinkText();?></a>  -->
<?php
}
else {
?>
	<!-- Share is either disabled or not configured properly -->
<?php 
}
?> 		
<!-- End Gigya Socialize plugin ShareLink-->