<?php if($this->showReferralUrl()) { ?>
<!-- @nelkaake Added on Saturday June 26, 2010: BEGIN referral code/url/email fieldset -->
<div class="share-invitation-link black-title-bar"><?php echo $this->__('Share your personal invitation link'); ?></div>
	<div class="share-invitation-link-box">
		<div class="invitation-link">
		
		        <?php if($this->showReferralUrl()): ?>
		            <div class="urlcode-input-box">
		                <span><?php echo Mage::getBaseUrl();?></span><input type="text" name="referral_url" style="background: #fff;" value="<?php echo Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId())->getCustomerurl(); ?>" 
		                    title="<?php echo $this->__('Your Referral URL') ?>" class="input-text" id="referral_url" disabled="disabled" />
			            <button class="edit"><span><?php echo $this->__('Edit'); ?></span></button>
		            </div>
			            <span id="customer-url-validation-message"></span>
		            
		        <?php endif; ?>
		        
		</div>
	    <div class="social-share">
	        <div class="social-share-images">
	        <?php /*?><a href="http://www.facebook.com/sharer.php?u=<?php echo $this->getReferralUrl(); ?>" target="_blank"><img class="facebook" src="<?php echo $this-> getSkinUrl(); ?>images/facebook.png" width="48" height="48" title="post this on facebook"/></a><?php */?>
	        
	        <div class="t-trans" href"#"></div>
	        <div class="f-trans" href"#"></div>

	        <a target="_blank" href="http://twitter.com/home?status=Sign up for evogue with this link: <?php echo $this->getReferralUrl(); ?>"><img class="twitter" src="<?php echo $this-> getSkinUrl(); ?>images/twitter.png" width="48" height="48" title="post this on twitter" /></a>
	        <a href="mailto:?subject=Sign up for evogue &body=I'm a Member of evogue, an invitation-only shopping club for everything luxury - at private sale prices. New Collections go live a few times each month - but are available only for a short time. Sign up now with this link: <?php echo $this->getReferralUrl(); ?>" target="_blank"><img class="email" src="<?php echo $this-> getSkinUrl(); ?>images/email.png" width="48" height="48" title="email to friend" /></a></div>
	    </div>
	</div>
<?php }?>
<!-- @nelkaake Added on Saturday June 26, 2010: END referral code/url/email fieldset -->

<script type="text/javascript">
	Event.observe($$('.urlcode-input-box button.edit')[0], 'click', function(){
		if ($('referral_url').readAttribute('disabled')) {
			this.select('span')[0].innerHTML = 'save';
			this.setAttribute('disabled', 'disabled');
			this.setStyle({ background: '#777' });
			$('referral_url').setStyle({ background: '#f2f58d' });
			$('referral_url').removeAttribute('disabled');
		} else {
			$('referral_url').setStyle({ background: '#fff' });		
			$('referral_url').setAttribute('disabled', 'disabled');	
			this.select('span')[0].innerHTML = 'edit';
			
			this.removeAttribute('disabled');
			this.setStyle({ background: '#d2002b' });			
			
			var ajax = new Ajax.Request('/index.php/customerurl/unique/save',{
				method: 'post',
				parameters: { customerurl: $('referral_url').value }, 
				onSuccess: function(transport) {
					console.log(transport.responseText);
				}
			});
		}
	});
	
	var timer = 0;
	Event.observe($('referral_url'), 'keyup', function(){
		clearTimeout(timer);
		
		$('customer-url-validation-message').addClassName('loading');
		$('customer-url-validation-message').innerHTML = 'Validating your username...';
		
		timer = setTimeout('verify()', 1000);
	});
	
	function verify() {
	
		$$('.urlcode-input-box button.edit')[0].setAttribute('disabled', 'disabled');
		$$('.urlcode-input-box button.edit')[0].setStyle({ background: '#777' });			
		
		$('customer-url-validation-message').addClassName('loading');
		$('customer-url-validation-message').innerHTML = 'Validating your username...';
		
		var ajax = new Ajax.Request('/index.php/customerurl/unique/verify',{
			method: 'post',
			parameters: { customerurl: $('referral_url').value }, 
			onSuccess: function(transport) {
				var response = eval('new Object(' + transport.responseText + ')');
				$('customer-url-validation-message').removeClassName('loading');
				
				if (response.success == 1) {
					$('customer-url-validation-message').innerHTML = 'Username is available';
					
					$$('.urlcode-input-box button.edit')[0].removeAttribute('disabled');
					$$('.urlcode-input-box button.edit')[0].setStyle({ background: '#d2002b' });			
					
				} else {
					$('customer-url-validation-message').innerHTML = 'Username already taken.';				
				}
			}
		});
	
	}
</script>
