<div id="top" class="keep-calm-signup-container">
	<?php echo $this->getChildHtml('landing_header'); ?>

</div>
<?php
	$referer = false;
	$refererSet = false;
	if(Mage::getSingleton('core/session')->getReferer()) {
		$refererSet = true;
		$referer = Mage::getSingleton('core/session')->getReferer();
	}

	if(!$refererSet) {
		//get the referrer
		if (isset($_SERVER['HTTP_REFERER'])) {
			$referer = $_SERVER['HTTP_REFERER'];
		} else {
			$referer = "unknown";
		}
		//save it in a session variable
		Mage::getSingleton('core/session')->setReferer($referer); // store session data
	}
?>

<div ng-app>

	<div class="container withShadow">
		<div class="top-block">
			

			<div class="content">

				
				<div class="text-overlay clearfix">
					<div class="landing-title">
						<h1 class="heading">Shop. Like a Man.</h1>
						<span class="subheading-subtitle">Outsource your shopping</span>
					</div>


					<div class="home swipe-controls row clearfix">
						<a class="big-control prev" href='#' onclick='doSwipePrev();return false;'></a>
						<a class="big-control next" href='#' onclick='doSwipeNext();return false;'></a>
					</div>

					<nav class="dot-nav">
						<ul id="bullets">
							<li><a href="#" onclick='doSwipeNow(0);return false;' class="dot active"></a></li>
							<li><a href="#" onclick='doSwipeNow(1);return false;' class="dot"></a></li>
							<!-- <li><a href="#" onclick='doSwipeNow(2);return false;' class="dot"></a></li> -->
						</ul>
					</nav>

					<div id="slider" class="swipe clearfix">
					  <ul class="clearfix">

					    <li style='display:block' class="clearfix">
					    	<div class="nine columns">
								<div class="centered-content">
									<div class="subheading-container ani fadeInRight">
										<h2 class="subheading">I'm a man.</h2>
										<span class="subheading-subtitle">I don't have the time to browse through 73 pages of tees.</span>
									</div>
									<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/asos.png');?>" alt="" class="scale-with-grid behind">
								</div>
							</div>
							<div class="seven columns">
								<div>
									<div class="centered-content vertical-middle grey-back all-corners">
										

										<div class="subheading-subtitle">Let us shop for you.</div>
										<a href="/mens-clothing.html" class="convert">Try it free!</a>	
										<div class="subheading-subtitle smaller-subtitle">wait a sec, <a href="#how">how does it work?</a></div>

										<div class="customer-quote quotes clearfix">
											<div class="quote-box">
												
												<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
												<div class="quote v-outer-container">
													<div class="v-inner-container">
														<span class="v-aligned-element">
															It's like shopping, but without the bullshit
														</span>
													</div>
												</div>
												<div class="quote-triangle"></div>
												
												<div class="author-container">
													<div class="twitter-avatar-container">
														<div id="andreas" class="twitter-avatar"></div>
													</div>

													<div class="author-text-container">
														<span class="author">Andreas</span>
														<span class="caption-small">Man since 1986</span>
													</div>
													
												</div>
											
											</div> <!-- end ng-repeat -->
										</div>
										
										
									</div>
									
								</div>
							</div>

					    </li>
					    
					    <li style='display:none' class="clearfix ani">
					    	<div class="nine columns">
								<div class="centered-content">
									<div class="subheading-container ani fadeInRight">
										<h2 class="subheading">I'm a man.</h2>
										<span class="subheading-subtitle">I don't buy clothes online.</span>
									</div>
									<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/parcel.png');?>" alt="" class="scale-with-grid behind">
								</div>
							</div>
					    	
							<div class="seven columns">
								<div>
									<div class="centered-content vertical-middle grey-back all-corners">
										

										<div class="subheading-subtitle">Kick shopping's ass.</div>
										<a href="/mens-clothing.html" class="convert">Try it free!</a>	
										<div class="subheading-subtitle smaller-subtitle">or learn <a href="#how">how it works</a></div>
										<div class="customer-quote quotes clearfix">
											<div class="quote-box">
												
												<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
												<div class="quote v-outer-container">
													<div class="v-inner-container">
														<span class="v-aligned-element">
															I don't think I've ever shopped online for clothes. Except with BRANDiD.
														</span>
													</div>
												</div>
												<div class="quote-triangle"></div>
												
												<div class="author-container">
													<div class="twitter-avatar-container">
														<div id="hywel" class="twitter-avatar"></div>
													</div>

													<div class="author-text-container">
														<span class="author">Hywel</span>
														<span class="caption-small">Man since 1986</span>
													</div>
													
												</div>
											
											</div> <!-- end ng-repeat -->
										</div>
										
										
									</div>
									
								</div>
							</div>

					    </li>
					    <!-- <li style='display:none' class="clearfix ani">
					    	<div class="nine columns">
								<div class="centered-content">
									<div class="subheading-container ani fadeInRight">
										<h2 class="subheading">I'm a man.</h2>
										<span class="subheading-subtitle">Same again please guv'nor.</span>
									</div>
									<img src="<?php // echo $this->getSkinUrl('images/leanlanding/home/reorder-one-tap.png');?>" alt="" class="scale-with-grid behind">
								</div>
							</div>
					    	
							<div class="seven columns">
								<div>
									<div class="centered-content vertical-middle grey-back all-corners">
										

										<div class="subheading-subtitle">Your clothes. On demand.</div>
										<a href="/mens-clothing.html" class="convert">Try it free!</a>	

										<div class="customer-quote quotes clearfix">
											<div class="quote-box">
												
												<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
												<div class="quote v-outer-container">
													<div class="v-inner-container">
														<span class="v-aligned-element">
															I get a reminder, I reorder in one tap. Job done.
														</span>
													</div>
												</div>
												<div class="quote-triangle"></div>
												
												<div class="author-container">
													<div class="twitter-avatar-container">
														<div id="matt" class="twitter-avatar"></div>
													</div>

													<div class="author-text-container">
														<span class="author">Matthew</span>
														<span class="caption-small">Man since 1988</span>
													</div>
													
												</div>
											
											</div>
										</div>
										
										
									</div>
									
								</div>
							</div>

					    </li> -->
					    
					  </ul>
					</div>


					<div class="share-buttons thirteen columns offset-by-three">
	
						<div class="like-but share-but">
							<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
						</div>
					
						<div class="share-but follow">
							<a href="https://twitter.com/brandid" class="twitter-follow-button" data-show-count="true" data-lang="en">Follow @BRANDiD</a>
							<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
						</div>
						
						<div class="share-but">
							<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Dirty boxers never got anyone laid. Designer brands auto-delivered for MEN. get #BRANDiD" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
						</div>

						<div class="share-but gplus">
								<a id="FancyButton" href="http://www.thefancy.com/fancyit?ItemURL=http://www.getbrandid.com/&Title=BRANDiD - Shop. Like a Man.&Category=Men's&ImageURL=http://www.getbrandid.com/brandid-square-big.png">Fancy</a><script src="http://www.thefancy.com/fancyit.js" type="text/javascript"></script>
								<!-- 
								<a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.getbrandid.com%2F&media=http%3A%2F%2Fwww.getbrandid.com%2Fskin%2Ffrontend%2Fdefault%2Fbrandid%2Fimages%2Fgift%2Fparcel.png&description=Mens%20shopping%20for%20men%20who%20hate%20shopping." class="pin-it-button" count-layout="horizontal"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a> -->
						</div>
					</div>

					
					
					<script type="text/javascript">
						var swiper1 = new Swipe(document.getElementById('slider'), {
						    startSlide: 0,
						    speed: 400,
						    // auto: 6000,
						    callback: function(event, index, elem) {

						    	var i = bullets.length;
						        while (i--) {
						          bullets[i].className = 'dot';
						          animate[i].className = 'subheading-container ani';
						        }
						        bullets[index].className = 'dot active';
						        animate[index].className = 'subheading-container ani fadeInRight';

						    	// update dot-nav
						    }
						});
						var bullets = jQuery('#bullets li a');
						var animate = jQuery('.subheading-container');

						var doSwipeNow = function(slideToNum) {
							swiper1.slide(slideToNum, 400);
							return jQuery(".subheading-container").css("opacity", 0);
						}
						var doSwipePrev = function() {
						  jQuery(".subheading-container").css("opacity", 0);
						  return swiper1.prev();
						};

						var doSwipeNext = function() {
						  jQuery(".subheading-container").css("opacity", 0);
						  return swiper1.next();
						};

					</script>

				</div>


				<div id="how" class="withTopShadow relative big-centered-steps">
					<div class="grey-back fullwidth clearfix">
						<div class="row endorsement-title clearfix row">
							How it works
						</div>
						<div class="how-to-step">
							<div class="centered-parts">
								<div class="left part">
									<div class="horizontal-line left-fade"></div>
								</div>
								<div class="circle-container center part">
									<div class="step-circle"><span class="number">1</span></div>
								</div>
								<div class="right part">
									<div class="horizontal-line right-fade"></div>
								</div>
							</div>
							<div class="subheading-subtitle no-float centered clearfix">Tell us what you're looking for.</div>
								
							<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/jumper.png');?>" alt="" class="scale-with-grid behind clearfix">
						</div>
						<div class="how-to-step">
							<div class="centered-parts">
								<div class="left part">
									<div class="horizontal-line left-fade"></div>
									<!-- <span class="subheading-subtitle no-float text-right">Step</span> -->
								</div>
								<div class="circle-container center part">
									<div class="step-circle"><span class="number">2</span></div>
								</div>
								<div class="right part">
									<div class="horizontal-line right-fade"></div>
								</div>
								
							</div>
							
							<div class="subheading-subtitle no-float centered clearfix">
								Our robot M.A.L.E. (Masculine Algorithmic Learning Engine) searches <span class="bold">everywhere</span>. Online, offline  &amp; outerspace.
							</div>
							<div class="scale-with-grid male-scan-transparent clearfix">M.A.L.E.</div>
							<a href="https://twitter.com/intent/tweet?screen_name=male&text=Can%20you%20do%20my%20shopping%20for%20me%3F" class="twitter-mention-button" data-related="BRANDiD">Tweet to @male</a>
							<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

						</div>

						<div class="how-to-step">
							<div class="centered-parts">
								<div class="left part">
									<div class="horizontal-line left-fade"></div>
									<!-- <span class="subheading-subtitle no-float text-right">Step</span> -->
								</div>
								<div class="circle-container center part">
									<div class="step-circle"><span class="number">3</span></div>
								</div>
								<div class="right part">
									<div class="horizontal-line right-fade"></div>
								</div>
								
							</div>
							
							<div class="subheading-subtitle no-float centered clearfix">
								As if by magic, we'll hit your inbox with <span class="bold">with 6 killer options</span>. Buy in seconds.
							</div>
							<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/email.png');?>" alt="" class="scale-with-grid behind clearfix">


							<div class="transparent-block with-margin conversion-reminder">
								<div class="subheading-subtitle">You are hereby granted permission to kick shopping's ass.</div>
								<a href="/mens-clothing.html" class="convert">Try it free!</a>
							</div>
								


						</div>

					</div>
				</div>

				<div class="sub-block-holder">
					
					<div class="shadow-holder">
						<div class="shadow-ninja"></div>
					</div>
					<div class="sub-block-bg first">
						<div class="one-third column sub-block">
							<div class="landing-title">Any Item</div>
							
							<img src="<?php echo $this->getSkinUrl('images/arush/leanlanding/no-male/box-socks-tees.png'); ?>" alt="Your Basics" class="scale-with-grid explain-img">

							<div class="explain">What do you need right now? Just tell us and we'll find it for you.</div>
						</div>
					</div>
					
					<div class="sub-block-bg">
						<div class="one-third column sub-block">
							<div class="landing-title">Every Brand</div>

							<img src="<?php echo $this->getSkinUrl('images/arush/leanlanding/no-male/icon-brands.png'); ?>" alt="Moustache oils" class="scale-with-grid explain-img">

							<div class="explain">Whatever brand you wear, we have it. Guaranteed. Or your money back. Capiche?</div>
						</div>
					</div>

					<div class="sub-block-bg">
						<div class="one-third column sub-block">
							<div class="landing-title">No Fees</div>

							<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/icon-check.png'); ?>" alt="Moustache singing" class="scale-with-grid explain-img">

							<div class="explain">We work hard to find the lowest prices available, and we don't charge you anything on top. Ever.</div>
						</div>
					</div>

				</div>

				

			</div>

			
		</div>



	</div>

	<div class="grey-back fullwidth withTopShadow">
		<div class="quotes container clearfix">

			<div class="row endorsement-title clearfix">
				Unofficial Endorsements
			</div>
			<br/>
			<br/>

			<div class="quote-box one-third column">
				<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/wolverine.png'); ?>" class="scale-with-grid quote-img" alt="Wolverine"/>
				<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
				<div class="quote v-outer-container">
					<div class="v-inner-container">
						<span class="v-aligned-element">
							BRANDiD makes the hairs on my hairs stand up.
						</span>
					</div>
				</div>

				
				<div class="quote-triangle"></div>
				<span class="author">Wolverine, Superhero</span>
				<span class="caption-small">Man since... ???</span>
			</div>
			
			<div class="quote-box one-third column">
				<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/leonidas.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
				<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
				<div class="quote v-outer-container">
					<div class="v-inner-container">
						<span class="v-aligned-element">
							BRANDiD pants are like CGI abs for your crotch.
						</span>
					</div>
				</div>

				
				<div class="quote-triangle"></div>
				<span class="author">Leonidas, King of Sparta</span>
				<span class="caption-small">Man since 540 BC</span>
			</div>
			
				<div class="quote-box one-third column last">
				<img src="<?php echo $this->getSkinUrl('images/leanlanding/home/gok.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
				<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
				<div class="quote v-outer-container">
					<div class="v-inner-container">
						<span class="v-aligned-element">
							It's not for me.
						</span>
					</div>
				</div>

				
				<div class="quote-triangle"></div>
				<span class="author">Gok Wan, Fashionista</span>
				<span class="caption-small">Man since 1974</span>
			</div>
			
		</div>

		<div class="twitter quotes container clearfix" ng-controller="TwitterController">
			<br/>
			<hr/>
			<br/>
			<br/>
			<br/>
			<div class="row endorsement-title clearfix">
				Official Endorsements
			</div>

			<div class="call-to-action-container">
				<a href="https://twitter.com/BRANDiD" class="twitter-follow-button" data-show-count="false">Follow @BRANDiD</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>

			<div class="quote-box one-third column" ng-repeat="tweet in displayTweets">
				<a href="http://www.twitter.com/{{tweet.user.screen_name}}" class="button-overlay" ng-hide="!tweet.media_url_https">
					<div class="tweet-img-container">
						<img src="{{tweet.media_url_https}}" class="scale-with-grid quote-img" alt="{{tweet.user.screen_name}}"/>
					</div>
				</a>
				
				<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
				<div class="quote v-outer-container">
					<div class="v-inner-container">
						<span class="v-aligned-element" ng-bind="tweet.text">
						</span>
					</div>
				</div>
				<div class="quote-triangle"></div>
				
				<div class="author-container">
					<img src="{{tweet.user.profile_image_url_https}}" alt="" class="twitter-avatar">
					<div class="author-text-container">
						<span class="author">@{{tweet.user.screen_name}}</span>
						<span class="caption-small">{{tweet.created_at_1}}</span>
						<span class="caption-small">{{tweet.created_at_2}}</span>	
					</div>
					
				</div>
					
			
			</div> <!-- end ng-repeat -->
			
			<div class="load-more-container clearfix">
				<a ng-click="getNext(scrollByNumTweets)" class="convert secondary more-tweets">Load More...</a>
			</div>
		</div>

	</div>
		

	<div class="container withShadow">
		<div class="share-block">
			<div class="landing-title">
				<span class="heading">Commitment issues?</span>
				<div class="landing-subtitle">
					<span>Not convinced yet? No worries. Until then, soak up cool man stuff daily.</span>
				</div>
			</div>
			
			
			<div class="sub-block-holder">
					
				<div class="shadow-holder">
					<div class="shadow-ninja"></div>
				</div>
				<div class="sub-block-bg first">
					<div class="one-third column sub-block">
						<div class="explain"><span class="bold">Like us on Facebook</span> for cool man stuff daily.</div>

						<div class="fb-like-box" data-href="http://www.facebook.com/getbrandid" data-width="292" data-height="340" data-show-faces="false" data-border-color="#EBEBEB" data-stream="true" data-header="false"></div>

						
					</div>
				</div>
				
				<div class="sub-block-bg">
					<div class="one-third column sub-block">



						<div class="explain"><span class="bold">Follow us on Twitter</span> for cool man stuff daily.</div>


						<a class="twitter-timeline" href="https://twitter.com/BRANDiD" data-widget-id="262989798569017344">Tweets by @BRANDiD</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


					</div>
				</div>

				<div class="sub-block-bg">
					<div class="one-third column sub-block">
							
							<script type="text/javascript">
								setTimeout(function(){
									loadTumblrWidget();
								},5000);
							</script>

							<div class="explain"><span class="bold">Follow us on Tumblr</span> for cool man stuff daily.</div>
						
						<div id="tumblrWidget">
							<div class="timeline-header clearfix">
								<h1 class="summary">Posts</h1>
								<iframe class="btn right" frameborder="0" border="0" scrolling="no" allowtransparency="true" height="25" width="200" src="http://platform.tumblr.com/v1/follow_button.html?button_type=1&tumblelog=because-we-are-men&color_scheme=light"></iframe>
							</div>
							
							<div class="stream">
								<div id="tumblr-badge" class="loading"></div>
							</div>

						</div>

					</div>
				</div>

			</div>

		</div>
	</div>

</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>




<script type="text/javascript">
	function loadTumblrWidget() {

		// load js in after user has indicated they are hanging around on the page

		(function($) {
			$.ajax({ url:"<?php echo $this->getSkinUrl('js/arush/landing/tumblrBadge-1.1-ck.js'); ?>", cache:true, dataType:"script"
			}).done(function ( data ) {
				$('#tumblr-badge').removeClass('loading');
			});
		})(jQuery);
	}
</script>

<script type="text/javascript">

	/* KISSmetrics Tracking */
	if(typeof(_kmq) !== "undefined") {
		_kmq.push(['record', 'Viewed homepage']);
	}
	/* Mixpanel Tracking */
	if(typeof(mixpanel) !== "undefined") {
		mixpanel.track("Viewed Homepage", {
			'Source: JS': document.referrer
		});
	}

</script>

<?php
	if(isset($_GET["fb_ad_id"])) { ?>

		<script type="text/javascript">
			
			// Facebook ads to KISSmetrics tracking
			if(typeof(_kmq) !== "undefined") {
				_kmq.push(['set', {'fb_ad_id':'<?php echo $_GET["fb_ad_id"]; ?>'}]);

			}
		
		</script>

	<?php	}

	if(isset($_GET["fb_ad_group"])) { ?>

		<script type="text/javascript">
			
			// Facebook ads to KISSmetrics tracking
			if(typeof(_kmq) !== "undefined") {
				_kmq.push(['set', {'fb_ad_group':'<?php echo $_GET["fb_ad_group"]; ?>'}]);

			}
		
		</script>

	<?php 	}
?>