<div id="top" class="keep-calm-signup-container">
	<?php echo $this->getChildHtml('landing_header'); ?>

</div>


<div class="title-block first calendar-container row">
	<div class="title-block-inner clearfix">
		<div class="title-block-container clearfix">		
			<div class="calendar container">
				
				<!-- start calendar -->
				<div class="months">

					<div class="month jan">
						<div class="month-title">
							Jan
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="sock-small-icon package-icon">
							</div>
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month feb">
						<div class="month-title">
							Feb
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month mar">
						<div class="month-title">
							Mar
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month apr">
						<div class="month-title">
							Apr
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month may">
						<div class="month-title">
							May
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month jun">
						<div class="month-title">
							Jun
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month jul">
						<div class="month-title">
							Jul
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="sock-small-icon package-icon">
							</div>
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month aug">
						<div class="month-title">
							Aug
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month sep">
						<div class="month-title">
							Sep
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
							<div class="tshirt-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month oct">
						<div class="month-title">
							Oct
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month nov">
						<div class="month-title">
							Nov
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
							<div class="shirt-small-icon package-icon">
							</div>
						</div>
					</div>
					<div class="month dec">
						<div class="month-title">
							Dec
						</div>
						<div class="package">
							<div class="sock-small-icon package-icon">
							</div>
							<div class="boxer-small-icon package-icon">
							</div>
						</div>
					</div>
				</div>

				<div class="copy">
					<div class="sixteen columns row">
						<h1 class="one-liner">I'm a man. I don't do shopping.</h1>
					</div>
					<div class="description ten columns offset-by-three row">
						<h4 class="description-copy">BRANDiD is the simplest way for men to get their clothes.<br/>How? Say hello to M.A.L.E.</h4>
					</div>
					<div class="male row">
						<div class="three columns">
							<img src="<?php echo $this->getSkinUrl('images/arush/home/small-mag-male.png'); ?>" alt="feed the M.A.L.E." title="feed the M.A.L.E."/>
						</div>
						
						<div class="thirteen columns">
							<span class="" id="male-welcome-msg">Hey, I'm M.A.L.E. (Masculine Algorithmic Learning Engine). What's your name? </span>
							<div class="mobile-buttons saving clearfix">
								<form id="malesubmit">
									<input id="name-to-save" type="text" name="firstname" value="e.g. Steve" onfocus="clearDefault(this)" onblur="restoreText(this)">
									<a id="step1" href="/get/party/started" class="convert secondary" style="display:none;float: left; margin: 0 10px 0 0;">Step 1. Feed the M.A.L.E.</a>
									<a id="submit_email" type="submit" class="convert" onclick="handleNameSubmit(); return false;">Feed the M.A.L.E.</a>
									<a id="step3" class="convert inactive" style="float:left" href="#">Step 3. Get BRANDiD</a>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
	<span id="2"></span>
</div>

<!-- <div class="commitment-caption container">
	<span class="vision-title-text">News</span>
	<div class="row">
		<br/><br/>
	</div>
	
</div> -->

<div class="commitment-caption container">
		
	<div class="row movember-banner">
		<div class="eight columns">
				
			<div class="left-section">
				<div class="movember-title">
					<span class="movember-title-text">Get a Mo Butler for Movember</span>
				</div>
				<div class="clearfix movember-caption">
					
					<span class="caption">Movember means that us men need to <span class="bold">grow large or go home.</span> With that in mind, BRANDiD has put together the ultimate in <span class="bold">bespoke moustache experiences.</span> A dedicated 24/7 specialist <span class="bold">tache technician.</span></span>

					<a href="/get/that/butler" class="movember-btn convert">Check it out!</a>
				</div>
			</div>
		</div>
		<div class="eight columns mo-butler-pic-holder">
			<img src="<?php echo $this->getSkinUrl('images/arush/movember/homepage-banner.png'); ?>" alt="Movember Mo Butler" class="scale-with-grid movember-img">
		</div>
	</div>


	<div class="row">
		
		<div class="vision-title">
			<span class="vision-title-text">What is BRANDiD?</span>
		</div>
		<span class="caption">BRANDiD is mens shopping for men who hate shopping. You tell us what tees, socks and boxers you like, and we sort the rest. We can even auto-deliver every three or six months, so your boxers are always box fresh. Select. Subscribe. Sorted. Capiche?</span>

	</div>

	<div class="process">
		<div class="one-third column">
			<img src="<?php echo $this->getSkinUrl('images/arush/home/small-mag-male.png'); ?>" alt="we feed the M.A.L.E." title="we feed the M.A.L.E."/>
			<a id="main-step-1" href="#top" class="convert step">Step 1. Feed the M.A.L.E.</a>
			<div class="step-caption">M.A.L.E. is our Masculine Algorithmic Learning Engine. It learns what you like.</div>
		</div>
		<div class="one-third column">
			<img src="<?php echo $this->getSkinUrl('images/arush/home/small-mag-plan.png'); ?>" alt="choose a clothing subscription" title="choose a clothing subscription"/>
			<a id="main-step-2" href="#" class="convert step inactive">Step 2. Plan Configurator</a>
			<div class="step-caption"><span>Boxers, disco or classic? Tees, Vees or Polos? Quarterly delivery, biannually or just a one month taster?</span></div>
		</div>
		<div class="one-third column">
			<img src="<?php echo $this->getSkinUrl('images/arush/home/small-mag-pack.png'); ?>" alt="we feed the M.A.L.E." title="we feed the M.A.L.E."/>
			<a href="#" class="convert step inactive">Step 3. Get BRANDiD</a>
			<div class="step-caption">Now you're rockin' fresh garms, time to do something more important instead.</div>
		</div>
	</div>

	<div class="share-buttons thirteen columns offset-by-three">
	
		<div class="like-but share-but">
			<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
		</div>
	
		<div class="share-but follow">
			<a href="https://twitter.com/brandid" class="twitter-follow-button" data-show-count="true" data-lang="en">Follow @BRANDiD</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		</div>
		
		<div class="share-but">
			<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Dirty boxers never got anyone laid. Designer brands auto-delivered for MEN. get #BRANDiD" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
		</div>

		<div class="share-but gplus">
				<a id="FancyButton" href="http://www.thefancy.com/fancyit?ItemURL=http://www.getbrandid.com/&Title=BRANDiD - Shop. Like a Man.&Category=Men's&ImageURL=http://www.getbrandid.com/brandid-square-big.png">Fancy</a><script src="http://www.thefancy.com/fancyit.js" type="text/javascript"></script>
				<!-- 
				<a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.getbrandid.com%2F&media=http%3A%2F%2Fwww.getbrandid.com%2Fskin%2Ffrontend%2Fdefault%2Fbrandid%2Fimages%2Fgift%2Fparcel.png&description=Mens%20shopping%20for%20men%20who%20hate%20shopping." class="pin-it-button" count-layout="horizontal"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a> -->
		</div>
	</div>
</div>


<div class="quotes container clearfix">

	<div class="quote-box one-third column">
	<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
	<span class="quote left">BRANDiD makes the hairs on my hairs stand up.</span>
	<div class="quote-triangle"></div>
	<span class="author">Wolverine</span>
	<span class="caption-small">aka Logan of the X-Men</span>
	<span class="caption-small">Man since… nobody knows</span></div>
	
	<div class="quote-box one-third column">
	<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
	<span class="quote middle">I may have gotten fat in my later years, but I always wore sexy pants.</span>
	<div class="quote-triangle"></div>
	<span class="author">Henry VIII</span>
	<span class="caption-small">King of England</span>
	<span class="caption-small">Man since 1491</span></div>
	
	<div class="quote-box one-third column last">
	<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
	<span class="quote right">It's not for me.</span>
	<div class="quote-triangle"></div>
	<span class="author">Gok Wan</span>
	<span class="caption-small">Not sure why he's famous</span>
	<span class="caption-small">Around since 1974</span></div>
	
</div>			


<?php /* ?>
<div class="grey-tilt-holder vision-block">
	<div class="grey-tilt clearfix">
		<div class="grey-tilt-container clearfix">
			<div class="vision section clearfix">
				<div class="vision-title">
					<span class="vision-title-text">Our Vision</span>
				</div>
				<div class="mandate box">
					<span class="vision-sub-title">Our <span class="red-text">Man</span>date</span>
					<div class="mandate-one-line block">
						We are reinventing shopping for men because the industry has forgotten about us.
						Why should we have to sift through poncy female-focused fashionista content just to get our clothes delivered? It's time to <a href="https://www.youtube.com/watch?v=aaas7GFbLHk&feature=related" target="_blank">take the power back.</a>
						<!-- if you're reading this, watch this one from '92! http://www.youtube.com/watch?v=cPHEgpWhkuQ&feature=related -->
					</div>
				</div>
				<div class="what-is box">
					<span class="vision-sub-title">What is BRANDiD?</span>
					<div class="what-is-oneliner">
						BRANDiD is a subscription service for designer basics… and a whole lot more. We love quality gear, great service and good humour.
					</div>
				</div>

			</div>
		</div> <!-- end grey tilt container -->
	</div> <!-- end grey tilt -->
</div>	
<?php */ ?>


<div class="commitment-caption middle container">
	<div class="commitment-caption">
		<span id="1" class="caption">Plans? Whoa there buddy... we just met.</span>
	</div>
</div>
<div class="title-block first">
	<div class="title-block-inner clearfix">
		<div class="title-block-container container clearfix">		
			<div id="bigtop-title" class="im-man-title">
				<span class="first">I'm a man.</span><br/>
				<span class="second">I have commitment issues.</span>
			</div>
		</div>
	</div>
</div>


<div class="grey-tilt-holder">
	<div class="grey-tilt clearfix">
			<div class="grey-tilt-container clearfix">
				<div class="faq container clearfix" id="take-to-plans">
					<div class="row"></div>

					<div class="vision-title">
						<span class="vision-title-text">FAQ</span>
					</div>
					

					<div class="container">

						<div class="row"></div>
						<div class="row"></div>	

						<img class="four columns" src="<?php echo $this->getSkinUrl('images/arush/faq-icon.png');?>" alt="press releases"/>
						<div id="st-accordion" class="st-accordion twelve columns row">
						    <ul>
						        <li>
						            <a href="#" class="opener">
						                I still don't get it, wtf is BRANDiD?<br/>
						                <span class="st-arrow">Open or Close</span>
						                <div class="article-date">No high street, no hassle, no nonsense</div>

						            </a>
						            <div class="st-content">
						                
						                It’s a service that takes the hassle out of shopping for your clothing essentials. Great gear. Auto delivered. On your schedule.
						                <br/><br/>
						                
						                Men hate shopping. Unless it’s for a new Ferrari or a Swiss Army Knife. 
						                <br/><br/>
						                Men especially hate shopping online. You know why? Because too often men’s shopping sites are just women’s sites with the pinks turned blue.
						                <br><br>
						                Too much choice, too much fashion, too much content. 
						                <br><br>
						                Well BRANDiD have simplified the whole process. Just configure your ideal package and set up a one off drop or a recurring delivery that suits you. Get in, get out, get on with something else.
						                <br><br>
						                You’ll never have to shop again.
						                <br><br>
						                Unless it’s for that Ferrari.
						                <br><br>
						                
						            	
						                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="arush,4nkush">Tweet to @BRANDiD</a>
										<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
										<br/>

										
										<div class="row faq-button">
											<br/>Or jump straight in:<br/>
											<a href="#top" class="faq convert">Step 1. Feed the M.A.L.E.</a>
										</div>

						            </div>
						        </li>

						        <li>
						            <a href="#" class="opener">
						                How do you know what clothes I'll like?<br/>
						                <span class="st-arrow">Open or Close</span>
						                <div class="article-date">Because we built M.A.L.E. our Masculine Algorithmic Learning Engine.</div>

						            </a>
						            <div class="st-content">
						                
						                A digital wingman. A robotic shopping superhero. A manly, metal, mathematical genius.
						                
						                <br/><br/>
						                A silicon wonderkid with a primary overriding objective. To make sure you get exactly the clothes you like, exactly when you like.
						                <br><br>
						                Just answer a few simple questions and M.A.L.E. will crunch the numbers, spin the gears and recommend the right package for you. 
						                <br><br>
						                The more you tell him, the more he learns. Like everything in life, you get out what you put in. Capiche?
						                <br><br>
						                
						            	Want to talk about it?<br/>
						                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="arush,4nkush">Tweet to @BRANDiD</a>
										<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
										<br/>

										
										<div class="row faq-button">
											<br/>Or jump straight in:<br/>
											<a href="#top" class="faq convert">Step 1. Feed the M.A.L.E.</a>
										</div>

						            </div>
						        </li>

						        <li>
						            <a href="#" class="opener">
						                What if I want to return something?<br/>
						                <span class="st-arrow">Open or Close</span>
						                <div class="article-date">No probs. Just send it back dude.</div>
						            </a>
						            <div class="st-content">
						               	We'll give you a full refund or an exchange in your next package. No messing.

						                <br/><br/>

						                And unlike other stores, M.A.L.E. will learn from what you send back, so we never make the same mistake twice. 

						                <br/><br/>

						                Want to talk about it?<br/>
						                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="arush,4nkush">Tweet to @BRANDiD</a>
										<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
										<br/>

										
										<div class="row faq-button">
											<br/>Or jump straight in:<br/>
											<a href="#top" class="faq convert">Step 1. Feed the M.A.L.E.</a>
										</div>
						            </div>
						        </li>

						        <li>
						            <a href="#" class="opener">
						                What clothes and brands do you offer?<br/>
						                <span class="st-arrow">Open or Close</span>
						                <div class="article-date">Right now, it’s all about pants, socks and tees...</div>
						            </a>
						            <div class="st-content">
						               
						            	Once we're sure we’ve got those exactly right, we can start offering more gear, but only if we're confident we can deliver a superior experience than traditional stores.
						                <br/><br/>
						                We offer a whole bunch of premium brands like Calvin Klein, Ralph Lauren and Hugo Boss as well as the value brands such as UniQlo, American Apparel and good old M&amp;S. And if there’s a brand you just can’t be without, no problem, we’ll hook you up with that too. Whatever brands you’re after, we’ll always make sure that you get a great deal. Standard.

						                <br/><br/>

						                Want to talk about it?<br/>
						                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="arush,4nkush">Tweet to @BRANDiD</a>
										<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
										<br/>

										
										<div class="row faq-button">
											<br/>Or jump straight in:<br/>
											<a href="#top" class="faq convert">Step 1. Feed the M.A.L.E.</a>
										</div>
						            </div>
						        </li>

						        <li>
						            <a href="#" class="opener">
						                Why can't I just shop on the high street or online?<br/>
						                <span class="st-arrow">Open or Close</span>
						                <div class="article-date">Seriously, you want to shop without a robot sidekick at your disposal?</div>

						            </a>
						            <div class="st-content">
						                
						                You could. But as me, we all face the same problem. Even after dragging ourselves to the dreaded high street or taking pot luck on google: <strong>we don't know what to buy</strong>. And we definitely don't have the patience levels of a female shopper to happily browse through <a href="http://www.asos.com/Men/T-Shirts-Vests/Cat/pgecategory.aspx?cid=7616">72 pages</a> of items to find THAT special outfit. But you know who does?

						                <br/><br/>M.A.L.E. does. And M.A.L.E. knows exactly what you like.
						                <br/><br/>

						                Want to talk about it?<br/>
						                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="arush,4nkush">Tweet to @BRANDiD</a>
										<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
										<br/>

										
										<div class="row faq-button">
											<br/>Or jump straight in:<br/>
											<a href="#top" class="faq convert">Step 1. Feed the M.A.L.E.</a>
										</div>
						            </div>
						        </li>
						        <li>
						            <a href="#" class="opener">
						                Can I just try the service without committing?<br/>
						                <span class="st-arrow">Open or Close</span>
						                <div class="article-date">Yes...</div>
						            </a>
						            <div class="st-content">
						               	
						            	For sure. You’re a man. Men don’t do commitment.

						                <br/><br/>

						                You have the option to configure your delivery to drop just the once if you like. 
										M.A.L.E will send you a timely reminder when he thinks you might need a top up. He’s good like that.
										<br><br>


						                Want to talk about it?<br/>
						                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="arush,4nkush">Tweet to @BRANDiD</a>
										<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
										<br/>

										
										<div class="row faq-button">
											<br/>Or jump straight in:<br/>
											<a href="#top" class="faq convert">Step 1. Feed the M.A.L.E.</a>
										</div>
						            </div>
						        </li>
						        <li>
						            <a href="#" class="opener">
						                Do you ship outside the UK?<br/>
						                <span class="st-arrow">Open or Close</span>
						                <div class="article-date">Yep. We can ship anywhere.</div>
						            </a>
						            <div class="st-content">
						               	
						            	Anywhere within reason. Don’t go asking for a package to be sent to the International Space Station. That’s just nuts. Check out our International shipping prices <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>international-shipping#1">here</a>.

						                <br/><br/>

						                Want to talk about it?<br/>
						                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="arush,4nkush">Tweet to @BRANDiD</a>
										<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
										<br/>

										
										<div class="row faq-button">
											<br/>Or jump straight in:<br/>
											<a href="#top" class="faq convert">Step 1. Feed the M.A.L.E.</a>
										</div>
						            </div>
						        </li>

						    </ul>

						</div>








						<!-- <div class="one-third column">
							
							<div class="fade">

								<img id="step-1-feed" class="scale-with-grid male-explanation-img" src="<?php // echo $this->getSkinUrl('images/arush/home/step-1-feed.png'); ?>" alt="the M.A.L.E. learns what you like" title="the M.A.L.E. learns what you like"/>

								<div>
									<img id="step-2-feed" class="scale-with-grid male-explanation-img" src="<?php // echo $this->getSkinUrl('images/arush/home/step-2-feed.png'); ?>" alt="the M.A.L.E. learns what you like" title="the M.A.L.E. learns what you like"/>
								</div>
							</div>

						</div>
						<div class="one-third column">
							<div class="male-explanation">Your data gets punched into BRANDiD’s proprietary Masculine Algorithmic Learning Engine (M.A.L.E.).</div>
							<img src="<?php // echo $this->getSkinUrl('images/arush/home/small-mag-male.png'); ?>" alt="the M.A.L.E. learns what you like" title="the M.A.L.E. learns what you like"/>
							<div class="male-explanation">We built M.A.L.E. from the pixel up to learn what you like. It eats feedback and sh*ts great garms.</div>

						</div>
						<div class="one-third column">

							<div class="fade">

								<img id="step-1-clothes" class="scale-with-grid male-explanation-img" src="<?php // echo $this->getSkinUrl('images/arush/home/step-1-clothes.jpg'); ?>" alt="the M.A.L.E. learns what you like" title="the M.A.L.E. learns what you like"/>
								
								<div>
									<img id="step-2-clothes" class="scale-with-grid male-explanation-img" src="<?php // echo $this->getSkinUrl('images/arush/home/step-2-clothes.jpg'); ?>" alt="the M.A.L.E. learns what you like" title="the M.A.L.E. learns what you like"/>
								</div>
							</div>
						</div>

						<div class="twelve columns offset-by-two">
							
						</div>
					</div> -->

					<?php /* ?>

					<div id="how" class="how section">
					
					
					
					<div class="how-to-process">
						<div class="how-to-box">
							<div class="select-title">
								<span class="select-title-text">Select</span>
							</div>
							<div class="select-circle circle">
							</div>
							<div class="select-title red-title">
								<span class="select-title-text">Select a monthly plan</span>
							</div>
							
							<div class="select-triangle vert-chevron">
								<div class="select-triangle white moveable">
								</div>
								<div class="select-triangle grey">
								</div>
							</div>
						</div> <!-- end how to box -->
						
						<div class="how-to-box">
							<div class="select-title">
								<span class="select-title-text">Subscribe</span>
							</div>
							<div class="subscribe-circle circle">
								<div class="sub-detail detail-1">plans start at only</div>
								<div class="sub-detail detail-2">£19</div>
								<div class="sub-detail detail-3">monthly or quarterly</div>
							</div>
							<div class="select-title red-title">
								<span class="select-title-text">Automatic monthly billing</span>
							</div>
							
							<div class="subscribe-triangle vert-chevron">
								<div class="subscribe-triangle white moveable">
								</div>
								<div class="subscribe-triangle grey">
								</div>
							</div>
						</div> <!-- end how to box -->
			
						<div id="third-how" class="how-to-box last">
							<div class="select-title">
								<span class="select-title-text">Sorted</span>
							</div>
							<div id="sorted-cal" class="sorted-circle circle">
							</div>
							<div class="select-title red-title">
								<span class="select-title-text">Automatic monthly delivery</span>
							</div>
							
						</div> <!-- end how to box -->
						
					</div> <!-- end how to process -->						
					
					
				</div> <!-- end how section -->
				<?php */ ?>
					<!-- div class="plans-img">
					</div-->
					<div id="action-section-2" class="sixteen columns action-section clearfix">
							
						<div class="coupon-card">
							<!--div class="upper-box">
								<div class="commitment-caption">
									<span class="caption">Use the coupon code:</span>
									<br/>
									<span class="caption-strong">FREEDOUBLE</span>
									<br/>
									<span class="caption">at checkout for a FREE double pack in your first month<sup>*</sup></span>
									<br/>
									<br/>
									<span class="caption-small"><sup>*</sup>Not redeemable with any other offers, valid until May 31st, 2012.</span>

								</div>
							</div-->
							<div class="green-box clearfix">
								<div class="commitment-caption">
									<span class="caption">No commitment or credit card required, just balls.</span>
								</div>
								<div class="convert-button clearfix">
									<a id="body-convert-2" href="#top" class="convert">Step 1. Feed the M.A.L.E.</a>
								</div>
							</div>
						</div>

					</div>
				</div>
				
				
				
				<!--div class="vision section clearfix">
					<div class="vision-title">
						<span class="vision-title-text">Boosters (coming soon)</span>
					</div>
					<div class="what box boosters">Because men shop to solve a problem.<br/>
					Delivered immediately in large quantities and with bulk discounts,
					Boosters ensure you're not in this situation again any time soon.<br/>
					If you're not the shopping type, choose Lucky Dip and we'll shop for you.
					</div>

					<div class="boosters-img first">
					</div>
					<div class="boosters-img second">
					</div>
					<div class="boosters-img third">
					</div>

					
				</div-->
			</div> <!-- end grey tilt container -->
	</div> <!-- end grey tilt -->
</div>

<div class="chev-group-wrap container">
	<div class="chevron-group final container">
		
		<a class="invisibut" href="#notaman">
			<div class="chevron down black">
				<div id="notaman" class="first-line block">Sounds cool, but it's just</div>
				<div class="second-line block">Not for me</div>
				<div class="chevron-triangle"></div>
			</div>
		</a>
	</div>
</div>

<div class="final title-block last">
	<div class="title-block-inner clearfix">
		<div class="title-block-container container clearfix">		
			<div id="bigtop-title" class="im-man-title">
				<span class="first">I'm not a man.</span><br/>
				<a href="http://www.barbie.com"><span class="second red">Get me the heck out of here.</span></a>
			</div>
		</div>
	</div>
</div>

<div class="final-share container">
	<div class="vision-title">
		<span class="vision-title-text">Know someone who'll like this?</span>
	</div>
	<div class="box">
		Let them know using the buttons below.
	</div>
	
	<div class="share-buttons six columns offset-by-five clearfix">
			
			<div class="like-but share-but">
				<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
			</div>
			
			<div class="share-but twitter">
				<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Men, rally the troops. It's time to take the power back. #shoplikeaman" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
			</div>
			
			<div class="share-but gplus">
				<a id="FancyButton" href="http://www.thefancy.com/fancyit?ItemURL=http://www.getbrandid.com/&Title=BRANDiD - Shop. Like a Man.&Category=Men's&ImageURL=http://www.getbrandid.com/brandid-square-big.png">Fancy</a><script src="http://www.thefancy.com/fancyit.js" type="text/javascript"></script>
				<!-- <div class="tapiture_tapit_button"></div> -->
					<!-- <script type="text/javascript" src="//static.tapcdn.com/mosaic/tap_button.js"></script> -->
			</div>

			<!-- <div class="share-but gplus">
				<g:plusone size="medium" href="https://www.getbrandid.com/"></g:plusone>
			</div> -->
	</div>
</div>



<div id="rejecter">
	<div id="jr_overlay" style="background-color: rgb(0, 0, 0); opacity: 0.8; background-position: initial initial; background-repeat: initial initial; ">
	</div>
	<div id="jr_wrap">
		<div id="jr_inner" style="min-width: 420px; max-width: 420px; width: auto; ">
			<h1 id="jr_header">You're using a really old browser!</h1>
			<p>
				We tried our best, but we really can't afford to support old browsers like this.
			</p>
			<p>
				Please install one of these awesome browsers instead:
			</p>
			<ul>
				<li id="jr_firefox" style="background-image: url(<?php echo $this->getSkinUrl('images/reject/background_browser.gif'); ?>); background-attachment: scroll; background-color: transparent; background-position: 0% 0%; background-repeat: no-repeat no-repeat; ">
					<a href="http://www.mozilla.com/firefox/">
						<div class="jr_icon" style="background-image: url(<?php echo $this->getSkinUrl('images/reject/browser_firefox.gif'); ?>); background-attachment: scroll; background-color: transparent; background-position: 0% 0%; background-repeat: no-repeat no-repeat; ">
						</div>
						<div>
							Firefox
						</div>
					</a>
				</li>
				<li id="jr_chrome" style="background-image: url(<?php echo $this->getSkinUrl('images/reject/background_browser.gif'); ?>); background-attachment: scroll; background-color: transparent; background-position: 0% 0%; background-repeat: no-repeat no-repeat; ">
					<a href="http://www.google.com/chrome/">
						<div class="jr_icon" style="background-image: url(<?php echo $this->getSkinUrl('images/reject/browser_chrome.gif'); ?>); background-attachment: scroll; background-color: transparent; background-position: 0% 0%; background-repeat: no-repeat no-repeat; ">
						</div>
						<div>
							Chrome
						</div>
					</a>
				</li>
				<li id="jr_safari" style="background-image: url(<?php echo $this->getSkinUrl('images/reject/background_browser.gif'); ?>); background-attachment: scroll; background-color: transparent; background-position: 0% 0%; background-repeat: no-repeat no-repeat; ">
					<a href="http://www.apple.com/safari/download/">
						<div class="jr_icon" style="background-image: url(<?php echo $this->getSkinUrl('images/reject/browser_safari.gif'); ?>); background-attachment: scroll; background-color: transparent; background-position: 0% 0%; background-repeat: no-repeat no-repeat; ">
						</div>
						<div>
							Safari
						</div>
					</a>
				</li>
			</ul>
			<div id="jr_close">
				<a onclick="closeReject()" href="#">Close This Window</a>
				<p>
					By closing the window, you can still use the site, but may not have the best experience.
				</p>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">

	var $j = jQuery.noConflict();
	
	// check for FB login
	if(typeof(FB) !== "undefined" && typeof(mixpanel) !== "undefined") {
		FB.getLoginStatus(function(response){
			mixpanel.track("Connected to Facebook?": response.status);
		});
	}



	$j(document).ready(function () {
				
	});

</script>



