<?php
	$referer = false;
	$refererSet = false;
	if(Mage::getSingleton('core/session')->getReferer()) {
		$refererSet = true;
		$referer = Mage::getSingleton('core/session')->getReferer();
	}

	if(!$refererSet) {
		//get the referrer
		if (isset($_SERVER['HTTP_REFERER'])) {
			$referer = $_SERVER['HTTP_REFERER'];
		} else {
			$referer = "unknown";
		}
		//save it in a session variable
		Mage::getSingleton('core/session')->setReferer($referer); // store session data
	}
?>

<div class="ghost-header"></div>

<div class="share-header clearfix">
	<div class="trans-back"></div>
	<div class="share-header-container container clearfix">

		<a id="logo" href="/" class="logo-button">
			<img class="gift-logo scale-with-grid" alt="BRANDiD logo" src="<?php echo $this->getSkinUrl('images/logo-beta.png')?>" title="BRANDiD Logo"/>
		</a>
		
		<nav>
			<select onchange="window.open(this.options[this.selectedIndex].value,'_top')">
			    <option value="" selected="selected">Navigate</option>
			    <option value="/">Home</option>
			    <option value="http://www.getbrandid.com/customer/account/login">Login</option>
			    <option value="/keep/calm/wearepros">Who</option>
			    <option value="http://blog.getbrandid.com/">Blog</option>
			    <option value="/get/that/app">Mobile App</option>
			  </select>
		</nav>

		<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) {?>
			<div class="top-name">
				
				<!--oneall thumbnail -->
				<?php // TODO put this in the module code
				
				$customerID = Mage::getSingleton('customer/session')->getId();
				//check if user has a Facebook ID or twitter ID
				$model = Mage::getModel('oneall/identifiers');
				$collection = $model->getCollection()
					->addFieldToFilter('customer_id',$customerID)
					->addFieldToFilter('provider',array('in' => array('Facebook','twitter')));
				foreach($collection as $item) {
				   if($item['provider'] === 'Facebook') {
		   				$facebookID = $item['identifier'];
		   			}
		   			else if($item['provider'] === 'twitter') {
		   				$twitterID = $item['profile_name'];
		   			};
				}
				
				
				if(isset($facebookID)) { ?>
					<img class="oaimg" width="50" height="50" src="https://graph.facebook.com/<?php echo $facebookID ?>/picture?type=square" />
				<?php  } else if(isset($twitterID)) { ?>
					<img class="oaimg" width="50" height="50" src="https://api.twitter.com/1/users/profile_image?screen_name=<?php echo $twitterID ?>&size=normal" />
				<?php
				} else {
				?><style type"text/css">.top-header .account-link a.header-link { padding-right:0px; }</style><?php
				}
				?>
				
				<?php // Mage::helper('oneall')->getThumbnailUrl(); ?>
				<!--oneall thumbnail -->
				

			</div>

			<div class="account-link">
				<a class="header-link" href="/customer/account/index/">My Account</a>
				<?php $customerName = Mage::helper('customer')->getCustomerName(); 
					$names = explode(" ",$customerName, 2);
					$firstname = $names[0];
				
				?> 						
				<a class="flname" href="#">Hi <?php echo $firstname; ?></a>						
									
			
			</div>
			
		<?php }
			else { ?>
				
				<div class="convert">
					<a id="gift-header-convert" href="/mens-clothing.html" class="convert secondary">Skip to Configurator</a>
				</div>

				<!-- social login -->
				<!-- div id="oa_social_login_header_convert" class="loading"></div>
			<span></span>	
				<script type="text/javascript">
					 oneall.api.plugins.social_login.build("oa_social_login_header_convert", {
					  'providers' :  ['facebook', 'twitter'],
					  'callback_uri': '<?php echo $this->getUrl('arush-oneall/rpx/token_url', array('_forced_secure' => false)) ?>',
					  'css_theme_uri': '<?php echo $this->getSkinUrl(); ?>css/social-convert-head.css',
					  'events' :{
						        'onload' : function(){jQuery('#oa_social_login_header_convert').removeClass('loading');}   
						      } 
					 });
				</script -->
				
		<?php } ?>


		<?php /* get homepage links */ 
			$urlmodifier = "/";
			if(Mage::getSingleton('cms/page')->getIdentifier() == 'home'  &&
				Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' 
				) {
				$urlmodifier = "";
			}
		?>

		<div class="convert">
			<a id="header-convert" href="/get/party/started" class="convert">Step 1. Feed the M.A.L.E.</a>
		</div>
		
		<a id="app" href="/get/that/app" class="header-button">
			<span class="button-copy">App</span>
		</a>
		<a id="who" href="/keep/calm/getgifted" class="header-button">
			<span class="button-copy">Gifts</span>
		</a>

		<a id="how-but" href="<?php echo $urlmodifier; ?>#1" class="header-button">
			<span class="button-copy">FAQ</span>
		</a>
		<a id="blog" href="http://blog.getbrandid.com/" class="header-button">
			<span class="button-copy">Blog</span>
		</a>
		

		<!-- <a id="what" href="<?php echo $urlmodifier; ?>#2" class="header-button">
			<span class="button-copy">What?</span>
		</a> -->

		
		<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) {?>
			<span style="
			    float: right;
			    clear: both;
			    margin-top: -23px;
			    margin-right: 14px;
				" class="login">or <a style="text-decoration:underline;" href="/customer/account/login">Login</a>
			</span>
		<?php } ?>

	</div>
	
</div>
<script type="text/javascript">
	function getReferer() {
		var referer;
		referer = '<?php echo parse_url($referer,PHP_URL_HOST); ?>';
		if(referer === '') {
			referer = 'PHP_URL_HOST was blank';
		}
		return referer;
	}
</script>