<div class="chisel-block header">
  <div class="container">
    <div class="logo-container">
      <a id="logo" href="/" class="header-logo">
        <img class="gift-logo ani fadeIn scale-with-grid" alt="BRANDiD logo" src="<?php echo $this->getSkinUrl('images/logo-beta.png')?>" title="BRANDiD Logo"/>
      </a>
    </div>
    <div class="navigation-holder">
    	
    	<a href="//blog.getbrandid.com" class="top-nav-link">
    		Blog
    	</a>
    	<a href="/get/that/app" class="top-nav-link">
    		App
    	</a>
    	<a href="/keep/calm/getgifted" class="top-nav-link">
    		Gifts
    	</a>
    	<a href="/mens-clothing.html" class="convert secondary">Try it!</a>
    	<a href="/customer/account/login" class="top-nav-link">
    		Login
    	</a>
    </div>
  </div>
</div>