<div class="chisel-block header">
  <div class="container">
    <div class="logo-container">
      <a id="logo" href="/" class="header-logo">
        <img class="gift-logo ani fadeIn scale-with-grid" alt="BRANDiD logo" src="<?php echo $this->getSkinUrl('images/logo-beta.png')?>" title="BRANDiD Logo"/>
      </a>
    </div>
    <div class="navigation-holder">
    	
    	<a href="//blog.getbrandid.com" class="top-nav-link">
    		Blog
    	</a>
    	<a href="/get/that/app" class="top-nav-link">
    		App
    	</a>
    	<a href="/keep/calm/getgifted" class="top-nav-link">
    		Gifts
    	</a>
    	<a href="/male" class="convert secondary">Try it!</a>
    	<a ng-hide="loggedIn" ng-click="loginModalShown=true" class="top-nav-link">
    		Login
    	</a>
        <a ng-show="loggedIn" class="profile-image-container" ng-click="myAccountModalShown=true">
            <img class="scale-with-grid profile-image-circle withShadow" ng-src="{{profileImageUrl}}" alt="your profile image"/>
        </a>
    </div>
  </div>
</div>