<div id="top" class="keep-calm-signup-container">
	<?php echo $this->getChildHtml('landing_header'); ?>
</div>

<div class="container withShadow">
	<div class="top-block">
		

		<div class="content">

			<div class="text-overlay clearfix">
				
				<div class="top-section clearfix">


					<div class="sixteen columns">
						<div class="landing-title">
							<span class="landing-title-span">We disabled login while we build a new<br/>My Account section...</span>
							<div class="landing-subtitle">
								<br/><br/>
								<span>If you need help, you can <span class="bold">contact us 24/7</span> via
								<br/>
								<a href="mailto:help@getbrandid.com?Subject=I%20need%20urgent%20help" style="color:#d2002b;text-decoration:underline;" class="bold">email</a>, telephone <span class="bold">+44 203 322 2882</span> or on Twitter</span>
								<br/><br/>
								<a href="https://twitter.com/intent/tweet?screen_name=male" class="twitter-mention-button" data-size="large" data-related="brandid">Tweet to @male</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
							</div>
						</div>
					</div>

					<div class="eight columns offset-by-four">
						
						<div class="signup">
							<div id="wufoo-z7x3p9">
								Fill out my <a href="http://brandid.wufoo.com/forms/z7x3p9">online form</a>.
							</div>
								<script type="text/javascript">var z7x3p9;(function(d, t) {
								var s = d.createElement(t), options = {
								'userName':'brandid', 
								'formHash':'z7x3p9', 
								'autoResize':true,
								'height':'619',
								'async':true,
								'header':'show'};
								s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'wufoo.com/scripts/embed/form.js';
								s.onload = s.onreadystatechange = function() {
								var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
								try { z7x3p9 = new WufooForm();z7x3p9.initialize(options);z7x3p9.display(); } catch (e) {}};
								var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
								})(document, 'script');</script>
							
						</div>
					</div>
				</div> <!-- end top-section -->

			</div>

			

		</div>

		
	</div>



</div>

<script type="text/javascript">

	var $j = jQuery.noConflict();
	var phoneOS = "none chosen";


	/* KISSmetrics tracking */
    if(typeof(_kmq) !== "undefined") {
    	_kmq.push(['record', 'Viewed Login Page']);
    }
    /* Mixpanel tracking */
    if(typeof(mixpanel) !== "undefined") {
   		mixpanel.track("Viewed Login Page");
    }

	
	/* attach a submit handler to the form */
	  $j("#download-app").submit(function(event) {



	    /* stop form from submitting normally */
	    event.preventDefault(); 
	        
	    /* get some values from elements on the page: */
	    var $form = $j(this),
	        url = $form.attr('action');

	    /* KISSmetrics tracking */
	    if(typeof(_kmq) !== "undefined") {
			_kmq.push(['record', 'Clicked App Download Link']);
	    	_kmq.push(['set', {'mobile number':mobileInput, 'Phone OS':phoneOS}]);
	    }

	    /* Mixpanel Tracking */
	   	if(typeof(mixpanel) !== "undefined") {
	   		mixpanel.track("Clicked App Download Link", {"Phone OS": phoneOS, "Phone number": mobileInput});
		}


		/* disable the button */

		$j('#submit-mobile').attr('disabled', true);
		$j('#twilio-response').addClass('loading');


	    /* Send the data using post and put the results in a div */
	    $j.post( url, { "mobile": mobile },
	      function( data ) {
	      	$j('#submit-mobile').removeAttr('disabled');
	      	$j('#twilio-response').removeClass('loading');
	      	alert('Cool, check your phone for a text message!');
	          //var content = $( data ).find( '#content' );
	          //$( "#result" ).empty().append( content );
	      }, "json");
	  });

</script>
