
<?php if ($this->showSendReferralForm()): ?>
<div class="send-now black-title-bar"><?php echo $this->__('Stage an Intervention') ?></div>
   <div class="send-now-box"> 
    <form action="<?php echo $this->getUrl('rewardsref/customer/invites/') ?>" method="post" id="form-validates">
        <?php /*?><?php if ($this->hasPredictedSignupPoints()): ?>
            <?php echo $this->__("You could earn up to %s when your referral signs up.", $this->getPredictedSignupPoints()); ?>
        <?php endif; ?>
        <?php if ($this->hasPredictedFirstOrderPoints()): ?>
            <?php echo $this->__("You could earn up to %s when your referral makes their first order.", $this->getPredictedFirstOrderPoints()); ?>
        <?php endif; ?><?php */?>

        <fieldset class="group-select" style="margin-bottom: 0px;">
            <input type="hidden" value="Il1NwrpfsCuSmp03" name="form_key"/>

               		<div class="send-now-box-left">
               		
               			<div id="inviteStyle" class="invite-options">
               				<h3><?php echo $this->__('Choose invitation style'); ?></h3>
               				<ul>
               					<li class="selected"><input type="radio" name="invite_style" value="0" checked="checked" /></li>
               					<li><input type="radio" name="invite_style" value="1" /></li>
               					<li><input type="radio" name="invite_style" value="2" /></li>
               				</ul>
               			</div>
               			
               			<div id="inviteQuote" class="invite-options">
	           				<h3><?php echo $this->__('Choose motivational quote'); ?></h3>
               				<ul>
               					<li class="selected"><input type="radio" name="invite_quote" value="0" checked="checked" /></li>
               					<li><input type="radio" name="invite_quote" value="1" /></li>
               					<li><input type="radio" name="invite_quote" value="2" /></li>
               				</ul>
               			</div>
                        <div class="plaxo"><?php echo $this->getChildHtml('plaxo_contact_chooser'); ?></div>
                        <img class="secure-image" src="<?php echo $this->getSkinUrl(); ?>images/secure.png" width="75" height="27" />
                        <span class="secure-note">We never store your password</span>

                        <div class="providers">
                        	<div class="gmail provider-logos"></div>
                        	<div class="yahoo provider-logos"></div>
                        	<div class="ms provider-logos"></div>
                        	<div class="aol provider-logos"></div>
                        	<span class="many-more">…and many more</span>
                        </div>
                                                
                        <div class="send-addresses">
                            <label><?php echo $this->__('To:') ?></label><br/>
                            <textarea name="contacts" id="recipient_list" style="width:406px;" rows="4" cols="80" ></textarea>
                        </div>
                   	<div class="button-set" style="margin-top:0px">
                        <!--<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>-->
                        <button class="form-button rewardsref-button sendinvitations" type="submit">Send invitations</button>
		            </div>
                        
                    </div>

                    <div class="send-now-box-right">
						<div class="black-title-bar">Intervention email preview</div>
						<div class="intervention-box">
						<div class="email-logo">
							<img class="intervention-logo" src="<?php echo $this->getSkinUrl() ?>images/logo.png" alt="BRANDiD email logo" />
						</div>
	                        <div class="send-message">
	                            <textarea name="message" id="message" class="required-entry textarea" style="width:396px;" rows="6" cols="80" title="<?php echo $this->__('Short Message') ?>"  >I'm a Member of evogue, an invitation-only shopping club for everything luxury - at private sale prices. New Collections go live a few times each month - but are available only for a short time. Sign up now with this invitation!</textarea>
	                        </div>
	                        
	                        <div id="randomQuotePreview"></div>

	                           
	                    </div>                                           
					</div>
               
        </fieldset>
   
    </form>
   </div>
   
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
        
        $$('.invite-options ul li').each(function(obj){
        	Event.observe(obj, 'click', function(){
	        	this.up().select('li').each(function(obj){
		        	obj.removeClassName('selected');		        	
	        	});
	        	this.addClassName('selected');
        		this.select('input')[0].checked = 'checked';
				if (this.up().up().id == 'inviteQuote') {
					var ajax = new Ajax.Request('/index.php/randomquote/quote/quote/position/'+this.select('input')[0].value+'/', {
						method: 'post',
						onSuccess: function(transport) {
							
							$('randomQuotePreview').innerHTML = transport.responseText;

							jQuery('.send-now-box .quote').css("background-color","#FFFBCC");
							jQuery('.send-now-box .quote').animate({ backgroundColor: '#eaeaea'}, 2000);
							jQuery('.send-now-box .quote-triangle').css("border-top-color","#FFFBCC");
							jQuery('.send-now-box .quote-triangle').animate({ borderTopColor: '#eaeaea'}, 2000);

						}
					});
				} else {

					var ajax = new Ajax.Request('/index.php/randomquote/quote/style/position/'+this.select('input')[0].value+'/', {
						method: 'post',
						onSuccess: function(transport) {
							$('message').innerHTML = transport.responseText;
							jQuery('#message').css("background-color","#FFFBCC");
							jQuery('#message').animate({ "background-color": '#fff' }, 2000);
						}
					});
				
				}
        		
        	})
        });
                
		var ajax = new Ajax.Request('/index.php/randomquote/quote/quote/position/0/', {
			method: 'post',
			onSuccess: function(transport) {
				$('randomQuotePreview').innerHTML = transport.responseText;
				jQuery('.send-now-box .quote').css("background-color","#FFFBCC");
				jQuery('.send-now-box .quote').animate({ backgroundColor: '#eaeaea'}, 2000);
				jQuery('.send-now-box .quote-triangle').css("border-top-color","#FFFBCC");
				jQuery('.send-now-box .quote-triangle').animate({ borderTopColor: '#eaeaea'}, 2000);
			}
		});
    </script>


<?php endif; ?>
