
<script type="text/javascript">

// Other PHP content ///////////////
var currency_map  = <?php echo $this->getCurrencyMapJson(); ?>;

function feignPriceChange() {
    
}

</script>
<div class="slider" onmouseup="sliderNotSliding()" style="display:none;">
	<table cellspacing="0" cellpadding="0">
		<tbody>
			<tr>
			    <td style="vertical-align:middle" class="btn-slider-reduce-points-container">
                    <img class="btn-slider-reduce-points" alt="<?php echo $this->__('Spend one point less'); ?>" 
                            src="<?php echo $this->getSkinUrl('images/rewards/slider/decr_points.gif'); ?>" 
                            id="slider_reduce_points"
                            onclick="rSlider.slider.setValue(rSlider.slider.value-1)" 
                            style="position:relative; top:5px;" />
                </td>
				<td>
					<div class="sliderRail" id="sliderRail">
					   <a style="left: 0%; top: -7px;" class="sliderHandle ui-slider-handle ui-state-default" id="sliderHandle"
							onmousedown="sliderSliding()"  
							onmouseup="sliderNotSliding()"></a>
					</div>
				</td>
			    <td style="vertical-align: middle" class="btn-slider-reduce-points-container">
    				<img class="btn-slider-increase-points" 
                            alt="<?php echo $this->__('Spend one point more'); ?>" 
                            src="<?php echo $this->getSkinUrl('images/rewards/slider/incr_points.gif'); ?>" 
                            id="slider_reduce_points"
                            onclick="rSlider.slider.setValue(rSlider.slider.value+1)" 
                            style="position:relative; top:5px;" />
                </td>
				<td valign="top">
					<div id="sliderCaption" class="sliderCaption" >
						<?php echo ''; ?>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<script type="text/javascript">
	document.observe("dom:loaded", function() {
		rSlider = new PointsSlider('sliderHandle', 'sliderRail', 'sliderCaption', 'redemption_rule_uses');
	});

	// Functions for changing the cursor on the slider
	function sliderSliding() {
		$('sliderRail').addClassName('sliderRail-sliding'); 
		$('sliderHandle').addClassName('sliderHandle-sliding');
	}

	function sliderNotSliding() {
		$('sliderRail').removeClassName('sliderRail-sliding'); 
		$('sliderHandle').removeClassName('sliderHandle-sliding');
	}
</script>
	<input type="text" name="redemption_uses" id="redemption_rule_uses"/>

<div class="rangeinput">
	<?php
	$quote = Mage::getSingleton ('rewards/session')->getQuote();
	?>
	<input type="range" id="range" name="test" min="<?php echo (string)$quote->getMinSpendablePoints(); ?>" max="<?php echo (string)$quote->getMaxSpendablePoints(); ?>" value="" /><br />

	<script type="text/javascript">
	jQuery(":range").rangeinput();
	Event.observe($$('.wrapper')[0], 'mouseup', function(obj){
			setTimeout(function(){
			if ($('redemption_rule_uses').value == $('range').value) {
				return;
			} else {
				$('redemption_rule_uses').value = $('range').value;
			}
		}, 500);
	});

	</script>
</div>