<?php

/**
 * Retail Evolved - Facebook Like Button
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA that is bundled with this
 * package in the file EVOLVED_EULA.txt.
 * It is also available through the world-wide-web at this URL:
 * http://retailevolved.com/eula-1-0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to service@retailevolved.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * You may edit this file, but only at your own risk, as long as it is within
 * the constraints of the license agreement. Before upgrading the module (not Magento), 
 * be sure to back up your original installation as the upgrade may override your
 * changes.
 *
 * @category   Evolved
 * @package    Evolved_Like
 * @copyright  Copyright (c) 2010 Kaelex Inc. DBA Retail Evolved (http://retailevolved.com)
 * @license    http://retailevolved.com/eula-1-0 (Retail Evolved EULA 1.0)
 */

?>
<?php if(!Mage::helper('evlike')->getLikeConfig('ev_facebook_type')): ?>
<?php $_locale = Mage::helper('evlike')->getFacebookLocale(); ?>

<!-- Using the JavaScript SDK -->
<div id="fb-root"></div>


<?php /* instead of writing BRANDiDs own FB integration, we just used this and modified it to use Parse */ ?>

<script>
  window.fbAsyncInit = function() {
      
    // use Parse if available

    if(typeof(Parse) !== "undefined") {
      
      Parse.FacebookUtils.init({
          appId: '<?php echo Mage::helper("evlike")->getLikeConfig("ev_facebook_app_id") ?>',
          channelUrl : '<?php echo $this->getBaseUrl() ?>facebook/channel',
      		Status: true,
        	Cookie: true,
          xfbml: true,
          frictionlessRequests: true
      });
   	
    } else {
      FB.init({
          appId: '<?php echo Mage::helper("evlike")->getLikeConfig("ev_facebook_app_id") ?>',
          channelUrl : '<?php echo $this->getBaseUrl() ?>facebook/channel',
          Status: true,
          Cookie: true,
          xfbml: true,
          frictionlessRequests: true
      });
    }

    // custom initialisation for advanced tracking

  	FB.Event.subscribe('edge.remove', function(href, widget) {
    	alert('You are not a real man');
  	}); 
    
  	FB.Event.subscribe('edge.create', function(href, widget) {
   		 /* KISSmetrics tracking */
        if(typeof(_kmq) !== "undefined") {
          _kmq.push(['record', 'Social Event', {
            'Facebook': 'Like',
            'Internal URL: ': document.URL,
            'Source: PHP': whereFrom,
            'Liked from internal URL, Source: JS': document.referrer
          } ]);
        }

        /* Mixpanel Tracking */
        if(typeof(mixpanel) !== "undefined") {
            mixpanel.track("Social Event", {
              'Facebook': 'Like',
              'Like URL': document.URL,
              'Source: PHP': whereFrom,
              'Source: JS': document.referrer
            });
        }
   	
  	});
  	
  };
  
  <?php // is this duplicated now that we have /facebook/channel working? ?>
  
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/<?php echo $_locale ?>/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
  
  
</script>

<?php endif; ?>