<div class="fb-canvas-logo">
	<img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt="" />
</div>

<div class="invite-gauge">
	<h3><?php echo $this->__('Total invitations sent'); ?></h3>
	<div id="inviteGauge"></div>

<div class="gauge-bottom">
	<div id="inviteCounter" class="flip-counter"></div>
	<span class="text"><?php echo $this->__('of 10,000 beta invitations'); ?></span>
	<span class="total-signups">10,000</span>
</div>

</div>	
<script type='text/javascript'>
	var inviteCounter = new flipCounter('inviteCounter', {value:0, inc:3, pace:15, tFH: 20, bFH: 34, fW: 28, bOffset: 200});
	inviteCounter.incrementTo(<?php echo Mage::helper('randomquote')->getTotalInvitesSent(); ?>);	

(function() {
    var config = {
        'api': '/randomquote/gauge/points',
        'color': '#d2002b',  // Optional
        'disableStyles': false,  // Optional
        'element': 'inviteGauge',
        'label': '',  // Optional
        'width': 250,  // Optional
        'refreshInterval': 3000  // Optional, milliseconds
    };

    new SiteTotal(config);
})();
</script>
