<!-- <div class="fb-like-box" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-width="300" data-show-faces="false" data-stream="false" data-header="false"></div> -->

<div class="invite-gauge">
	<h3><?php echo $this->__('Live feed of BRANDiD invites'); ?></h3>
	<div id="inviteGauge"></div>

	<div class="gauge-bottom">
		<div id="inviteCounter" class="flip-counter"></div>
		<span class="text"><?php echo $this->__('of 10 weekly invitations'); ?></span>
		<span class="total-signups">10</span>
	</div>

</div>	
<div class="small-spacer"></div>



<?php if(!Mage::helper('facebook')->isFan()) { ?>
	<div class="black-title-bar">'like' THIS PAGE TO GET STARTED</div>
	<div class="small-spacer"></div>
	<div class="fb-like-box" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-width="495" data-show-faces="true" data-border-color="#ffffff" data-stream="true" data-header="false"></div>
<?php } else if(!Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
	<div class="black-title-bar">CLAIM YOUR FACEBOOK INVITATION</div>
			<!-- The provider login will be embedded in this div //-->
				<div id="oa_social_login_container"></div>
			
				<script type="text/javascript">
					 oneall.api.plugins.social_login.build("oa_social_login_container", {
					  'providers' :  ['facebook'], 
					  'callback_uri': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>arush-oneall/rpx/token_url/',
					  'css_theme_uri': 'https://cdn.oneall.com/css/api/socialize/themes/connect_vertical.css'
					 });
				</script>
<?php } else {
	echo 'log in and send invites';
} ?>

<!--div class="fb-canvas-logo">
	<img src="<?php // echo $this->getSkinUrl('images/logo.png'); ?>" alt="" />
</div-->

<script type='text/javascript'>
	var inviteCounter = new flipCounter('inviteCounter', {value:0, inc:3, pace:15, tFH: 20, bFH: 34, fW: 28, bOffset: 200});
	inviteCounter.incrementTo(<?php echo Mage::helper('randomquote')->getTotalInvitesSent(); ?>);	

(function() {
    var config = {
        'api': '/randomquote/gauge/weekly',
        'color': '#d2002b',  // Optional
        'disableStyles': false,  // Optional
        'element': 'inviteGauge',
        'label': '',  // Optional
        'width': 250,  // Optional
        'refreshInterval': 3000  // Optional, milliseconds
    };

    new SiteTotal(config);
})();
</script>

