<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>


<div class="fb-like-box" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-width="300" data-show-faces="false" data-stream="false" data-header="false"></div>


<div id="container_notlike">
YOU DONT LIKE
</div>

<div id="container_like">
YOU LIKE
</div>

<script>
  
FB.init({
    appId  : '288271097870534',
    status : true, 
    cookie : true, 
    xfbml  : true  
  });

</script>


<div class="fb-canvas-logo">
	<img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt="" />
</div>

<div class="invite-gauge">
	<h3><?php echo $this->__('Total invitations sent'); ?></h3>
	<div id="inviteGauge"></div>

<div class="gauge-bottom">
	<div id="inviteCounter" class="flip-counter"></div>
	<span class="text"><?php echo $this->__('of 10,000 beta invitations'); ?></span>
	<span class="total-signups">10,000</span>
</div>

</div>	
<script type='text/javascript'>
	var inviteCounter = new flipCounter('inviteCounter', {value:0, inc:3, pace:15, tFH: 20, bFH: 34, fW: 28, bOffset: 200});
	inviteCounter.incrementTo(<?php echo Mage::helper('randomquote')->getTotalInvitesSent(); ?>);	

(function() {
    var config = {
        'api': '/randomquote/gauge/points',
        'color': '#d2002b',  // Optional
        'disableStyles': false,  // Optional
        'element': 'inviteGauge',
        'label': '',  // Optional
        'width': 250,  // Optional
        'refreshInterval': 3000  // Optional, milliseconds
    };

    new SiteTotal(config);
})();
</script>

<script type='text/javascript'>

jQuery(document).ready(function(){

    FB.login(function(response) {
      if (response.session) {
       
          var user_id = response.session.uid;
          var page_id = "40796308305"; //coca cola
          var fql_query = "SELECT uid FROM page_fan WHERE page_id = "+page_id+"and uid="+user_id;
          var the_query = FB.Data.query(fql_query);
          
          the_query.wait(function(rows) {

              if (rows.length == 1 && rows[0].uid == user_id) {
                  jQuery("#container_like").show();

                  //here you could also do some ajax and get the content for a "liker" instead of simply showing a hidden div in the page.
                  
              } else {
                  jQuery("#container_notlike").show();
                  //and here you could get the content for a non liker in ajax...
              }
          });
          

      } else {
        // user is not logged in
      }
    });
        
});
</script>

