<?php
/**
 * @see Mage_Catalog_Block_Product_View
 */
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();

?>
<ul class="quickie-tier-prices">
	<li><span class="price">&pound;<?php echo number_format($_product->getPrice(), 0)?></span><span><?php echo $this->__('1')?></span>x<br /><span><?php echo $this->__('for one night stands');?></span></li>
	<li><span class="price"></span><span><?php echo $this->__('2')?></span>x<br /><span><?php echo $this->__('\'cos all good things come in threes');?></span></li>
	<li><span class="price"></span><span><?php echo $this->__('3')?></span>x<br /><span><?php echo $this->__('to impress that fit bird at work');?></span></li>		
</ul>
<script type="text/javascript">
	document.observe('dom:loaded', function(){
	
		var counter = 0;

		$H(bundle.config.options).each(function(obj){

			var located = $H(obj.value.selections);
			located.each(function(o){
				var tierPrices = o.value.tierPrice;
				$$('.quickie-tier-prices span.price')[0].innerHTML = '&pound;' + parseInt(o.value.price);
				$$('.quickie-tier-prices span.price')[1].innerHTML = '&pound;' + parseInt(tierPrices[0].website_price);
				$$('.quickie-tier-prices span.price')[2].innerHTML = '&pound;' + parseInt(tierPrices[1].website_price);				
				throw $break;
				
			});
			throw $break;
		});
//		console.log(bundle.config.options.firstChild);		


		$$('ul.quickie-tier-prices li').each(function(obj){
			obj.observe('mouseover', function(){
				if (this.getStyle('background-color') != '#d2002b') {
					this.setStyle({ backgroundColor: '#000000' });				
				}

			});
			obj.observe('mouseout', function(){
				if (this.getStyle('background-color') != '#d2002b') {
					this.setStyle({ backgroundColor: '#595959' });
				}
			});

			obj.observe('click', function(){
				if (!$$('.input-text.qty')[0].hasClassName('qty-disabled')) {
					this.up().select('li').each(function(o){
						o.setStyle({ backgroundColor: '#595959', cursor: 'pointer' });
					});
					this.setStyle({ backgroundColor: '#d2002b', cursor: 'default' });

					$$('.input-text.qty')[0].value = this.select('span')[0].innerHTML;	
					jQuery($$('.input-text.qty')[0]).keyup();		
				}

			});			

		
		});
	});
</script>
<style type="text/css">
.quickie-tier-prices {
/* 	clear: both; */
	float: left;
	margin-top: 40px;
}

.quickie-tier-prices li {
	background-color: #595959;
	width: 106px;
	padding: 10px;
	cursor: pointer;
	float: left;
	margin-right: 10px;
	text-align: center;
}

.quickie-tier-prices li span.price {
	position: absolute;
	margin-top: -40px;
}
</style>