// Generated by CoffeeScript 1.3.3
(function() {
  var punter, root;

  punter = new Object();

  createPunter();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.buildPlan = function($scope) {
    var boxerOptions, boxerSizes, boxerUpgrades, genericColours, sockOptions, sockSizes, sockUpgrades, teeOptions, underteeSizes, underteeUpgrades;
    $scope.alert = function(text) {
      return alert(text);
    };
    genericColours = [
      {
        text: "classic",
        filterCode: ".classic",
        buttonId: "classic"
      }, {
        text: "disco",
        filterCode: ".disco",
        buttonId: "disco"
      }, {
        text: "both",
        filterCode: ".classic, .disco",
        buttonId: "both"
      }
    ];
    sockOptions = [];
    boxerOptions = [
      {
        text: "boxer shorts",
        buttonId: "boxer-shorts",
        filterCode: ".shorts",
        selected: false,
        supplement: 0
      }, {
        text: "boxer trunks",
        buttonId: "boxer-trunks",
        filterCode: ".trunks",
        selected: true,
        supplement: 0
      }
    ];
    teeOptions = [
      {
        text: "crew neck",
        buttonId: "crew-neck",
        selected: false,
        supplement: 0
      }, {
        text: "v-neck",
        buttonId: "v-neck",
        selected: false,
        supplement: 0
      }
    ];
    sockUpgrades = [
      {
        value: "value",
        code: "option-8-v-socks",
        supplement: 0
      }, {
        value: "premium",
        code: "option-10-d-socks",
        supplement: 5
      }
    ];
    boxerUpgrades = [
      {
        value: "value",
        code: "option-18-v-boxers",
        supplement: 0
      }, {
        value: "premium",
        code: "option-20-d-boxers",
        supplement: 5
      }
    ];
    underteeUpgrades = [
      {
        value: "value",
        code: "option-28-v-undertees",
        supplement: 0
      }, {
        value: "premium",
        code: "option-30-d-undertees",
        supplement: 5
      }
    ];
    sockSizes = [
      {
        text: "S",
        helper: "6-10 UK shoe size"
      }, {
        text: "L",
        helper: "11-13 UK shoe size"
      }
    ];
    boxerSizes = [
      {
        text: "S",
        helper: "30in - 32in waist"
      }, {
        text: "M",
        helper: "32in - 34in waist"
      }, {
        text: "L",
        helper: "34in - 36in waist"
      }, {
        text: "XL",
        helper: "36in - 38in waist"
      }
    ];
    underteeSizes = [
      {
        text: "S",
        helper: "47cm - 48cm chest"
      }, {
        text: "M",
        helper: "49cm - 50cm chest"
      }, {
        text: "L",
        helper: "51cm - 52cm chest"
      }, {
        text: "XL",
        helper: "53cm - 54cm chest"
      }, {
        text: "XXL",
        helper: "55cm - 56cm chest"
      }
    ];
    $scope.addMessage = [
      {
        text: 'socks',
        chosenPhrase: 0,
        phrases: ["Go on, add some socks, think of those poor little naked toes.", "Just because you can't see the holes, doesn't mean they're not there."]
      }, {
        text: 'boxers',
        chosenPhrase: 0,
        phrases: ["Are you sure you don't want any? What if you get lucky?", "I got two words for ya buddy: skid marks.", "You must have a draw full of fresh undies. Yeah, sure you do."]
      }, {
        text: 'undertees',
        chosenPhrase: 0,
        phrases: ["undertees random1", "undertees random2", "undertees random3", "undertees random4", "undertees random5"]
      }
    ];
    $scope.plan = {
      frequency: "trial"
    };
    $scope.drops = [
      {
        value: "trial"
      }, {
        value: "quarterly"
      }, {
        value: "biannually"
      }
    ];
    $scope.master = {};
    $scope.itemOptions = [
      {
        colours: genericColours,
        options: sockOptions
      }, {
        colours: genericColours,
        options: boxerOptions
      }, {
        colours: genericColours,
        options: teeOptions
      }
    ];
    $scope.items = [
      {
        recurlyCode: "option-8-v-socks",
        text: "socks",
        qty: 0,
        price: 3,
        size: false,
        chosenColour: 'both',
        chosenOptions: 'Choose a style',
        optionSupplement: 0,
        upgradeSupplement: 0,
        upgrades: sockUpgrades,
        sizes: sockSizes
      }, {
        recurlyCode: "option-20-d-boxers",
        text: "boxers",
        qty: 1,
        price: 10,
        size: false,
        chosenColour: 'Choose a colour',
        chosenOptions: 'Choose a style',
        optionSupplement: 0,
        upgradeSupplement: 0,
        upgrades: boxerUpgrades,
        sizes: boxerSizes
      }, {
        recurlyCode: "option-28-v-undertees",
        text: "undertees",
        qty: 0,
        price: 30,
        size: false,
        chosenColour: 'Choose a colour',
        chosenOptions: 'Choose a style',
        optionSupplement: 0,
        upgradeSupplement: 0,
        upgrades: underteeUpgrades,
        sizes: underteeSizes
      }
    ];
    $scope.update = function() {
      var basketItem, x;
      x = 0;
      basketItem = [];
      while (x < $scope.items.length) {
        basketItem[x] = {
          code: $scope.items[x].code,
          qty: $scope.items[x].qty
        };
        x++;
      }
      $scope.plan.basket = basketItem;
      $scope.updateMageFrequency();
      return saveBasket($scope.plan);
    };
    $scope.freqChanger = function(newFreq) {
      $j('.frequency-chooser a').removeClass('active');
      $j('#' + newFreq + '-button').addClass('active');
      $scope.plan.frequency = newFreq;
      return $scope.update();
    };
    $scope.recalculate = function() {
      var x;
      $scope.plan.total = 0;
      x = 0;
      while (x < $scope.items.length) {
        $scope.plan.total += $scope.items[x].qty * ($scope.items[x].price + $scope.items[x].upgradeSupplement + $scope.items[x].optionSupplement);
        x++;
      }
      $scope.updateMageOptions();
      $scope.update();
    };
    $scope.updateMageFrequency = function() {
      $j("#product-options-wrapper select").each(function(index) {
        var dropId, e, optionSelector, str;
        e = $j(this);
        dropId = e.attr('id');
        str = e.parent().parent().prev().find('label').text();
        if (str === "option-frequency" || str.indexOf("option-frequency") >= 0) {
          optionSelector = 'option:contains("' + $scope.plan.frequency + '")';
          $j('#' + dropId + ' ' + optionSelector).attr("selected", "selected");
          document.getElementById(dropId).onchange();
          return false;
        }
      });
    };
    $scope.updateMageOptions = function() {
      $j("#product-options-wrapper textarea").each(function(index) {
        var e, str;
        e = $j(this);
        str = e.parent().parent().prev().find('label').text();
        if (str === "options-json") {
          e.text(JSON.stringify($scope.items));
          return false;
        }
      });
    };
    $scope.updateMageQty = function(text, qty, brands) {
      $j("#product-options-wrapper select").each(function(index) {
        var drop1Found, drop2Found, dropId, e, itemText, str;
        e = $j(this);
        str = e.parent().parent().prev().find('label').text();
        str = str.split('-');
        if (str[0] === "option") {
          itemText = str[1];
          if (itemText === text) {
            if (str[2] === brands) {
              e.find("option").eq(qty).attr("selected", "selected");
              dropId = e.attr('id');
              document.getElementById(dropId).onchange();
              drop1Found = true;
            } else {
              e.find("option").eq(0).attr("selected", "selected");
              dropId = e.attr('id');
              document.getElementById(dropId).onchange();
              drop2Found = true;
            }
            if (drop1Found && drop2Found) {
              return false;
            }
          }
        }
      });
    };
    $scope.subtract = function(item, idx) {
      var brands;
      if (item.qty > 0) {
        item.qty--;
        $scope.recalculate();
        if (item.qty === 0) {
          $scope.chooseAddMessage(idx);
        }
        if (item.upgradeSupplement === 0) {
          brands = 'value';
        } else {
          brands = 'premium';
        }
        return $scope.updateMageQty(item.text, item.qty, brands);
      }
    };
    $scope.calculateOptionSupplement = function(index, item, idx) {
      var x, y;
      $scope.items[idx].optionSupplement = 0;
      x = 0;
      while (x < $scope.items.length) {
        y = 0;
        while (y < $scope.itemOptions[x].options.length) {
          if ($scope.itemOptions[x].options[y].selected === true) {
            $scope.items[x].optionSupplement += $scope.itemOptions[x].options[y].supplement;
          }
          y++;
        }
        x++;
      }
      return $scope.recalculate();
    };
    $scope.calculateUpgradeSupplement = function(upgrade, item, idx) {
      $scope.items[idx].upgradeSupplement = upgrade.supplement;
      $j('.upgrade-chooser.item-' + idx + ' a').removeClass('active');
      $j('.upgrade-chooser.item-' + idx + ' a.' + item.text + '-' + upgrade.value).addClass('active');
      $scope.updateMageQty(item.text, item.qty, upgrade.value);
      return $scope.recalculate();
    };
    $scope.add = function(item) {
      var brands;
      item.qty++;
      $scope.recalculate();
      if (item.upgradeSupplement === 0) {
        brands = 'value';
      } else {
        brands = 'premium';
      }
      return $scope.updateMageQty(item.text, item.qty, brands);
    };
    $scope.toggleCustomOption = function(index, $index, idx) {
      var x;
      if ($scope.itemOptions[idx].options[$index].selected === true) {
        $scope.itemOptions[idx].options[$index].selected = false;
      } else {
        $scope.itemOptions[idx].options[$index].selected = true;
      }
      $j('.' + '-' + $scope.items[idx] + '-' + index.buttonId).toggleClass('true');
      $scope.items[idx].chosenOptions = '';
      x = 0;
      while (x < $scope.itemOptions[idx].options.length) {
        if ($scope.itemOptions[idx].options[x].selected === true) {
          if ($scope.items[idx].chosenOptions !== '') {
            $scope.items[idx].chosenOptions += ', ';
          }
          $scope.items[idx].chosenOptions += $scope.itemOptions[idx].options[x].filterCode;
        }
        x++;
      }
      $scope.recalculate();
      return $scope.refilter(idx);
    };
    $scope.toggleColour = function(index, idx) {
      $scope.items[idx].chosenColour = index.filterCode;
      $j('.' + $scope.items[idx].text + '.colours a').removeClass('active');
      $j('.' + $scope.items[idx].text + '-' + index.buttonId).toggleClass('active');
      $scope.recalculate();
      return $scope.refilter(idx);
    };
    $scope.refilter = function(idx) {
      var $isocontainer, filterString;
      if ($isocontainer === void 0) {
        $isocontainer = $j('#' + $scope.items[idx].text + '-section-container .isotope-holder');
      }
      filterString = '';
      if ($scope.items[idx].chosenColour !== '') {
        filterString = $scope.items[idx].chosenColour;
      }
      if ($scope.items[idx].chosenOptions !== '') {
        if (filterString !== '') {
          filterString += ', ';
        }
        filterString += $scope.items[idx].chosenOptions;
      }
      return $isocontainer.isotope({
        filter: filterString
      });
    };
    $scope.groupButtons = function(idx, buttons) {
      if (idx === 0) {
        return 'lt';
      } else if (idx + 1 === buttons.length) {
        return 'rt';
      } else {
        return 'mid';
      }
    };
    $scope.changeSize = function(item, size, idx) {
      $scope.items[idx].size = size.text;
      $scope.recalculate();
      $j('.configure-size.' + item.text + '-size a').removeClass('active');
      return $j('.' + item.text + '-' + size.text).addClass('active');
    };
    $scope.isZeroed = function(idx) {
      if ($scope.items[idx].qty === 0) {
        return 'zeroed';
      } else {
        return 'non-zero';
      }
    };
    $scope.chooseAddMessage = function(idx) {
      var randomisedNum;
      randomisedNum = Math.floor(Math.random() * $scope.addMessage[idx].phrases.length);
      return $scope.addMessage[idx].chosenPhrase = $scope.addMessage[idx].phrases[randomisedNum];
    };
    $scope.init = function() {
      var $j, brandType, colour, o, x, _results;
      $j = jQuery.noConflict();
      x = 0;
      while (x < $scope.items.length) {
        o = $scope.items[x];
        if (o.recurlyCode.indexOf("-v-", 0) >= 0) {
          brandType = 'value';
        } else {
          brandType = 'premium';
        }
        $scope.updateMageQty(o.text, o.qty, brandType);
        $j('.' + $scope.items[x].text + '-' + brandType).click();
        if (o.chosenColour.indexOf("Choose", 0) <= 0) {
          if (o.chosenColour.indexOf("classic") >= 0) {
            colour = 'classic';
            if (o.chosenColour.indexOf("disco") >= 0) {
              colour = 'both';
            }
          } else {
            colour = 'disco';
          }
        } else {
          colour = '';
        }
        x++;
      }
      $scope.recalculate();
      $scope.update();
      x = 0;
      _results = [];
      while (x < $scope.addMessage.length) {
        $scope.chooseAddMessage(x);
        _results.push(x++);
      }
      return _results;
    };
    return $j(document).ready(function() {
      return $scope.init();
    });
  };

}).call(this);
