// Generated by CoffeeScript 1.3.3
(function() {
  var punter, root;

  punter = new Object();

  createPunter();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.buildPlan = function($scope) {
    var boxerOptions, shirtOptions, shirtUpgrades, sockOptions, teeOptions;
    sockOptions = [
      {
        text: "classic",
        selected: false,
        supplement: 0
      }, {
        text: "disco",
        selected: false,
        supplement: 0
      }
    ];
    boxerOptions = [
      {
        text: "classic",
        selected: false,
        supplement: 0
      }, {
        text: "disco",
        selected: false,
        supplement: 0
      }, {
        text: "boxer shorts",
        selected: false,
        supplement: 0
      }, {
        text: "boxer trunks",
        selected: false,
        supplement: 0
      }, {
        text: "briefs",
        selected: false,
        supplement: 0
      }
    ];
    teeOptions = [
      {
        text: "crew neck",
        selected: false,
        supplement: 0
      }, {
        text: "v-neck",
        selected: false,
        supplement: 0
      }, {
        text: "plain",
        selected: false,
        supplement: 0
      }, {
        text: "graphic",
        selected: false,
        supplement: 0
      }
    ];
    shirtOptions = [
      {
        text: "short collar",
        selected: false,
        supplement: 0
      }, {
        text: "double cuff",
        selected: false,
        supplement: 0
      }, {
        text: "slim fit",
        selected: false,
        supplement: 0
      }, {
        text: "straight fit",
        selected: false,
        supplement: 0
      }, {
        text: "no pocket",
        selected: false,
        supplement: 0
      }
    ];
    shirtUpgrades = [
      {
        value: "Tier 1",
        supplement: 0
      }, {
        value: "Tier 2",
        supplement: 25
      }, {
        value: "Tier 3",
        supplement: 75
      }
    ];
    $scope.plan = {};
    $scope.master = {};
    $scope.items = [
      {
        type: "socks",
        qty: 0,
        price: 5,
        optionSupplement: 0,
        upgradeSupplement: 0,
        options: sockOptions
      }, {
        type: "boxers",
        qty: 1,
        price: 10,
        optionSupplement: 0,
        upgradeSupplement: 0,
        options: boxerOptions
      }, {
        type: "tees",
        qty: 0,
        price: 30,
        optionSupplement: 0,
        upgradeSupplement: 0,
        options: teeOptions
      }, {
        type: "shirts",
        qty: 1,
        price: 25,
        optionSupplement: 0,
        upgradeSupplement: 0,
        options: shirtOptions,
        upgrades: shirtUpgrades
      }
    ];
    $scope.update = function(plan) {
      var basketItem, x;
      x = 0;
      basketItem = [];
      while (x < $scope.items.length) {
        basketItem[x] = {
          type: $scope.items[x].type,
          qty: $scope.items[x].qty
        };
        x++;
      }
      $scope.plan.basket = basketItem;
      return saveBasket(plan);
    };
    $scope.reset = function() {
      return $scope.plan.total = angular.copy($scope.master);
    };
    $scope.recalculate = function() {
      var x, _results;
      $scope.plan.total = 0;
      x = 0;
      _results = [];
      while (x < $scope.items.length) {
        $scope.plan.total += $scope.items[x].qty * ($scope.items[x].price + $scope.items[x].upgradeSupplement + $scope.items[x].optionSupplement);
        _results.push(x++);
      }
      return _results;
    };
    $scope.subtract = function(item) {
      if (item.qty > 0) {
        item.qty--;
        return $scope.recalculate();
      }
    };
    $scope.calculateOptionSupplement = function(index, item) {
      var x, y;
      item.optionSupplement = 0;
      x = 0;
      while (x < $scope.items.length) {
        y = 0;
        while (y < $scope.items[x].options.length) {
          if ($scope.items[x].options[y].selected === true) {
            $scope.items[x].optionSupplement += $scope.items[x].options[y].supplement;
          }
          y++;
        }
        x++;
      }
      return $scope.recalculate();
    };
    $scope.calculateUpgradeSupplement = function(upgrade, item) {
      item.upgradeSupplement = upgrade.supplement;
      return $scope.recalculate();
    };
    $scope.add = function(item) {
      item.qty++;
      return $scope.recalculate();
    };
    $scope.reset();
    return $scope.recalculate();
  };

}).call(this);
