// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.saveBasket = function(basket) {
    var $j;
    $j = jQuery.noConflict();
    return $j.cookie("basket", JSON.stringify(basket), {
      expires: 1,
      path: "/"
    });
  };

}).call(this);
