<?php 
print_r($this->getRequest()->getRequestUri());
if (strpos($this->getRequest()->getRequestUri(), Mage::getBaseUrl()) >= 0) {
	Mage::getSingleton('customer/session')->setBeforeAuthUrl($this->getRequest()->getRequestUri());
}

Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::getUrl("customer/account/index"));
if(!Mage::getSingleton('customer/session')->isLoggedIn() && strpos($this->getRequest()->getRequestUri(), Mage::getBaseUrl()) >= 0) {
    echo "<script type=\"text/javascript\">window.location='".Mage::getUrl("customer/account/login")."';</script>";  
}
?>