<?php 
if ($this->getSuppresstest() == 'true'){
	Mage::getModel('core/cookie')->set('suppresstest', true);
//	header('Location: '.Mage::getBaseUrl().'customer/account/create/');
	print_r(Mage::getBaseUrl().'customer/account/create/');
} 
if (Mage::getSingleton('customer/session')->isLoggedIn() && !Mage::getModel('core/cookie')->get('suppresstest')):
?>

Yowza
<form name="customer_details" action="/popup/form/page/index/anothertest/suppresstest/true">
	<input type="hidden" name="suppresstest" value="true" />
	<!-- a id="5-next" class="done" href="/popup/form/page/index/beta/suppress/true">Send some invitations</a-->
	<input id="5-next" class="done" type="submit" name="submit" value="don't show me this again" />
</form>
											


<script type="text/javascript">
Ajax.Responders.register({
    onComplete: function(request) {
        if (request.url.indexOf('popup/form/page/index/anothertest/suppresstest/true') >= 0) {
            document.location.href = request.transport.responseText;
        }
    }
});
</script>


<?php endif; ?>