<?php 
if ($this->getSuppresstest() == 'true'){
	Mage::getModel('core/cookie')->set('suppresstest', true);
	header('Location: '.Mage::getBaseUrl().'customer/account/create/');
} 
if (!Mage::getSingleton('customer/session')->isLoggedIn() /* && !Mage::getModel('core/cookie')->get('suppresstest') */):
?>

Yowza

<a id="5-next" class="done" href="/popup/form/page/index/beta/suppresstest/true">Send some invitations</a>


<script type="text/javascript">
Ajax.Responders.register({
    onComplete: function(request) {
        if (request.url.indexOf('popup/form/page/index/getstarted/suppresstest/true') >= 0) {
            document.location.href = request.transport.responseText;
        }
    }
});
</script>


<?php endif; ?>


