<?php /*

if ($this->getSuppressPopup() == '1') {
	Mage::getModel('core/cookie')->set('suppress_popup', true);
}
if ($this->getSubmit()) {
	Mage::getModel('core/cookie')->set('getting_started', true);
} */
if (Mage::getSingleton('customer/session')->isLoggedIn()):

?>
<div class="gettingstarted getstarted">
	<div class="popup-top">
		<h1>You're in, now what?</h1>
	</div>
	<div class="popup-form">
		<div class="left">			
			You just earned 100 points.
			<br/><br/>
			We’ll be opening the site up in a few weeks, you’re in early because we know you’ve got a bunch of friends who’ll love BRANDiD.
			<br/><br/>
			We also know every man needs a great designer tie, so when you get 50 signups we’ll send you one for free!
		</div>
		
		<div class="right">
			<img class="gauge-start" src="<?php echo $this->getSkinUrl();?>images/getstarted.png"/>
		</div>
	</div>
	<div class="popup-bottom">
		<a href="/rewardsref/customer/index">Start sending invitations</a>
	</div>
</div>
<?php endif; ?>
