<?php 
if ($this->getSuppress() == 'true'){
    Mage::getModel('core/cookie')->set('suppress', '1');
	echo '<script type="text/javascript">document.location.href = "/rewardsref/customer/index/";</script>';

} elseif (Mage::getSingleton('customer/session')->isLoggedIn() && !Mage::getModel('core/cookie')->get('suppress')) {
?>
<div class="gettingstarted getstarted">
    <div class="popup-top">
        <h1>You're in, now what?</h1>
    </div>
    <div class="popup-form">
        <div class="left">            
            You just earned 100 points.
            <br/><br/>
            We’ll be opening the site up in a few weeks, you’re in early because we know you’ve got a bunch of friends who’ll love BRANDiD.
            <br/><br/>
            We also know every man needs a great designer tie, so when you get 50 signups we’ll send you one for free!
        </div>
        
        <div class="right">
            <img class="gauge-start" src="<?php echo $this->getSkinUrl();?>images/getstarted.png"/>
        </div>
    </div>
    <div class="popup-bottom">
        <a href="/popup/form/page/index/getstarted/suppress/true">Start sending invitations</a>
    </div>
</div>

<?php } ?>


