// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.TwitterController = function($scope, $http) {
    $scope.tweetCount = 0;
    $scope.scrollByNumTweets = 6;
    $scope.allTweets = [];
    $scope.favourites = [];
    $scope.displayTweets = [
      {
        created_at_1: "One fine Wednesday evening",
        created_at_2: "in November",
        text: "Got a little extra touch this month from @BRANDiD in touch screen gloves as well as me Knickers & Stockins http://t.co/2tEvPzmt",
        user: {
          screen_name: "RDRB26",
          profile_image_url_https: "https://si0.twimg.com/profile_images/2912023785/5ad786af7826794f6d0f6f38b0a5529c_bigger.jpeg"
        },
        media_url_https: "https://pbs.twimg.com/media/A8z9PjcCEAInIY0.jpg"
      }, {
        created_at_1: "A crisp Monday morning",
        created_at_2: "in November",
        text: "Colourful toes. http://t.co/BstLnVXA”- thanks to @BRANDiD",
        user: {
          screen_name: "patrickjpr",
          profile_image_url_https: "https://si0.twimg.com/profile_images/2286049346/cuuye3eggcyz2xq17pyy_bigger.jpeg"
        },
        media_url_https: "https://instagr.am/p/R68nbWoThX/media/?size=m"
      }, {
        created_at_1: "One fine Saturday evening",
        created_at_2: "in November",
        text: "Had my second delivery from @BRANDiD and this was inside. Amazing! Thanks guys. You're the best! http://t.co/sp4B6oKX",
        user: {
          screen_name: "craigmdennis",
          profile_image_url_https: "https://si0.twimg.com/profile_images/2914319457/a7604c20568dda0b315ba0340841fc95_bigger.png"
        },
        media_url_https: "https://pbs.twimg.com/media/A8eFjSuCAAEUwtb.jpg"
      }
    ];
    $scope.convertTweetToDisplayableTweet = function(tweet) {
      var moment1, morning, tweetToReturn, _ref, _ref1;
      tweetToReturn = {};
      moment1 = moment(tweet["created_at"]);
      morning = moment1.format("a");
      if (morning === "am") {
        tweetToReturn.created_at_1 = "A crisp " + moment1.format("dddd") + " morning";
        tweetToReturn.created_at_2 = "in " + moment1.format("MMMM");
      } else {
        tweetToReturn.created_at_1 = "One fine " + moment1.format("dddd") + " evening";
        tweetToReturn.created_at_2 = "in " + moment1.format("MMMM");
      }
      tweetToReturn.text = tweet["text"];
      tweetToReturn.user = {};
      tweetToReturn.user.screen_name = tweet["user"]["screen_name"];
      tweetToReturn.user.profile_image_url_https = tweet["user"]["profile_image_url_https"].replace("normal", "bigger");
      tweetToReturn.media = false;
      if (((_ref = tweet["media"]) != null ? (_ref1 = _ref[0]) != null ? _ref1["media_url_https"] : void 0 : void 0) != null) {
        tweetToReturn.media = [];
        tweetToReturn.media_url_https = tweet["media"][0]["media_url_https"];
      }
      return tweetToReturn;
    };
    $scope.retrieveMoreTweets = function(maxTweets) {
      return $http({
        method: "GET",
        url: "/ajax/twitter/favourites.json"
      }).success(function(data, status, headers, config) {
        $scope.allTweets = data;
        return $scope.getNext(maxTweets);
      }).error(function(data, status, headers, config) {
        return $scope.allTweets = false;
      });
    };
    return $scope.getNext = function(maxTweets) {
      var displayableTweet, x, _i, _ref, _ref1;
      if (typeof $scope.allTweets[0] === "undefined") {
        $scope.retrieveMoreTweets(maxTweets);
      } else if ($scope.tweetCount >= $scope.allTweets.length) {

      } else {
        for (x = _i = _ref = $scope.tweetCount, _ref1 = $scope.tweetCount + maxTweets; _ref <= _ref1 ? _i < _ref1 : _i > _ref1; x = _ref <= _ref1 ? ++_i : --_i) {
          displayableTweet = $scope.convertTweetToDisplayableTweet($scope.allTweets[x]);
          $scope.displayTweets.push(displayableTweet);
          $scope.tweetCount++;
        }
        return $scope.displayTweets;
      }
    };
  };

  TwitterController.$inject = ["$scope", "$http"];

}).call(this);
