<?php  if(Mage::getStoreConfig('kissmetrics/track/kissmetrics_on')) {
?>
	<!-- start Kissmetrics BRANDiD code -->
	<script type="text/javascript">
		
		//detect browser and OS
		_kmq.push(['set', {'Browser' : BrowserDetect.browser + " " + BrowserDetect.version, 'Operating System' : BrowserDetect.OS}]);

		<?php /* What page is this */

			$module = $this->getRequest()->getModuleName();
			$controller = $this->getRequest()->getControllerName();
			$action = $this->getRequest()->getActionName();

		?>
		

		<?php /* Identify user */
		if(Mage::getSingleton('customer/session')->isLoggedIn()) {
			$customer = Mage::getSingleton('customer/session')->getCustomer();
			$customerID = $customer->getId();
			$customerEmail = $customer->getEmail();


			/* payer can be: unknown, yes, or definitely not. Need to check this after email address. 
			*/

			// we use group id to tell if a customer has paid us before or not
			// $groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
			// if($groupId != 1) {
			// 	$payer = 'has purchased';
			// }
			// else {
			// 	$payer = 'not purchased';
			// }

		?>
			

		<?php /* Otherwise set as guest */
		} ?>

		// custom actions
		jQuery(document).ready(function() {
			var $j = jQuery.noConflict();
			
			<?php /* Identify user */
				if($module === 'catalog' && $controller === 'category' && $action === 'view') {
					?> _kmq.push(['record', 'Viewed Plans']);	<?php
				}
				if($module === 'catalog' && $controller === 'product' && $action === 'view') {
					?> _kmq.push(['record', 'Viewed Product']);
						// added to cart
						$j("button.convert").click(function() {
						  _kmq.push(['record', 'Add to Cart']);
						});	<?php
				}
				if($module === 'checkout' && $controller === 'onepage' && $action === 'index') {
					?> _kmq.push(['record', 'Reached Checkout']);

					// get the punter from cookie
					createPunter();
					// auto fill email and name
					if(punter.email) {
						$j('input.validate-email').val(punter.email);
					}
					if(punter.fname) {
						$j('.name-firstname input').val(punter.fname);
					}

					// code to track coupon submit is in recurly callback function

					<?php 
				}
				// echo $module . ' ' . $controller . ' ' . $action;

				if(Mage::getSingleton('customer/session')->isLoggedIn()) { ?>

					_kmq.push(['identify', '<?php echo $customerEmail; ?>']);			

			<?php } ?>
		});


			
	</script>
	<!-- end Kissmetrics BRANDiD code -->

<?php } ?>