<?php
if ($this->getSuppressPopup() == '1') {
	Mage::getModel('core/cookie')->set('suppress_popup', true);
}
if (Mage::getSingleton('customer/session')->getCustomer() && !Mage::getModel('core/cookie')->get('getting_started')):
	Mage::getModel('core/cookie')->set('getting_started', true);
?>
<form name="getting_started" action="/popup/form/page/index/gettingstarted">
	<p>Welcome to Evogue, where shopping is more than just a dream...</p>
	<input type="checkbox" name="suppress_popup" value="1" <?php if (Mage::getModel('core/cookie')->get('suppress_popup')) { echo 'checked="checked"'; } ?>/>
	<input type="submit" name="next" value="next" />
</form>
<?php endif; ?>
