<div class="title-block">
	<div class="title-block-inner">
		<div class="title">
			<span class="page-title"><?php echo $this->getTitle(); ?></span>
			<div class="title-cms-block">
			<?php if(Mage::registry('current_category')) { $_category = Mage::registry('current_category');?>
				<div class="category-likebutton">
            		<?php echo Mage::helper('evlike')->getLikeHtml($this, $_category, true) ?>
            	</div>
            	<?php } ?>
			<?php echo $this->getText(); ?></div>

		</div>
	</div>
</div>