<?php
	if(Mage::registry('current_category')) {
		$_category = Mage::registry('current_category');
	    $_helper    = $this->helper('catalog/output');
	    $_description = $_category->getDescription();
	    $_imgHtml   = '';
	    if ($_imgUrl = $_category->getImageUrl()) {
	        $_imgHtml = '<p class="title-block-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
	        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    	}
    }
?>

<div class="title-block">
	<div class="title-block-inner clearfix">
		<div class="title">
			
			<?php if($_category) {?>
				<div class="first-row">
					<span class="page-title"><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></span>
				</div>
				
				<div class="second-row clearfix">
					<div class="title-cms-block">
						<div class="category-likebutton">
	    	        		<?php echo Mage::helper('evlike')->getLikeHtml($this, $_category, true) ?>
	        	    	</div>
			
			       	   	<p class="actual-category-text"><?php echo $_description; ?></p>
			
			       	</div>
		       	<?php echo $_imgHtml;?>
		       	</div>

            <?php } else { ?>
            	
        		<div class="first-row"><h1><span class="page-title">
					<?php echo $this->getTitle(); ?></span></h1>
				</div>
				
				<div class="title-cms-block">
  					<?php echo $this->getText(); ?>
  				</div>

            <?php } ?>

		</div>
	</div>
</div>