<script type="text/javascript" src="https://use.typekit.com/hyr0chu.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<!--
Available defitions:

.tk-ff-enzo-web {
	font-family: ff-enzo-web,sans-serif;
	font-style: normal | italic;
	font-weight: 100 | 600 | 900;
}

.tk-proxima-nova {
	font-family: "proxima-nova",sans-serif;
	font-style: normal;
	font-weight: 300 | 600;
}


-->