<!-- The plugin will be embedded into this div //-->
<div id="social_link_container"></div>
<script type="text/javascript">
 oneall.api.plugins.social_link.build("social_link_container", {
  'providers' :  ['facebook', 'google', 'hyves', 'linkedin', 'openid', 'twitter', 'vkontakte', 'wordpress', 'yahoo'], 
  'user_token': '<?php echo Mage::getSingleton('customer/session')->getOneallUserToken(); ?>',
  'callback_uri': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>arush-oneall/rpx/token_url_add/'
 });
</script>