	<?php

?>


<div class="header-container">
    <div class="header">
	
		<div class="top-header">
			<!-- div class="store-language"><?php // echo $this->getChildHtml('store_language') ?></div-->
			<!-- div class="facebook-header"><?php // echo $this->getLayout()->createBlock('cms/block')->setBlockId('header-fb-like')->toHtml() ?></div-->
			<?php /* echo $this->getChildHtml('topLinks') */ ?>
		    
			<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) {?>
				<div class="top-name">
					
					<!--oneall thumbnail -->
					<?php // TODO put this in the module code
					
					$customerID = Mage::getSingleton('customer/session')->getId();
					//check if user has a Facebook ID or twitter ID
					$model = Mage::getModel('oneall/identifiers');
					$collection = $model->getCollection()
						->addFieldToFilter('customer_id',$customerID)
						->addFieldToFilter('provider',array('in' => array('facebook','twitter')));
					foreach($collection as $item) {
					   if($item['provider'] === 'facebook') {
			   				$facebookID = $item['identifier'];
			   			}
			   			else if($item['provider'] === 'twitter') {
			   				$twitterID = $item['profile_name'];
			   			};
					   
					}
					
					
					if(isset($facebookID)) { ?>
						<img class="oaimg" width="50" height="50" src="http://graph.facebook.com/<?php echo $facebookID ?>/picture?type=square" />
					<?php  } else if(isset($twitterID)) { ?>
						<img class="oaimg" width="50" height="50" src="http://api.twitter.com/1/users/profile_image?screen_name=<?php echo $twitterID ?>&size=normal" />
					<?php
					} 
					?>
					
					<?php // Mage::helper('oneall')->getThumbnailUrl(); ?>
					<!--oneall thumbnail -->
					


				</div>

				<div class="account-link">
					<a class="header-link" href="/customer/account/index/">My Account</a>
					<?php $customerName = Mage::helper('customer')->getCustomerName(); 
						$names = explode(" ",$customerName, 2);
						$firstname = $names[0];
					
					?> 						
					<a class="flname" href="#">Hi <?php echo $firstname; ?></a>						
					<div class="my-account-links">
						<div class="my-account-triangle"></div>
						<?php echo $this->getChildHtml('accountLinks') ?>
					</div>					
				
				</div>
				
				<script>
					jQuery(document).ready(function () { 
		 
						jQuery('.account-link .header-link').hover(
							function () {
								//show its submenu
								jQuery('.my-account-links').show();
								jQuery('.account-link .header-link').css("border-top", "7px solid #000");

					 
							}, 
							function () {
								//hide its submenu
								jQuery('.my-account-links').hide();
								jQuery('.account-link .header-link').css("border-top", "7px solid #cfcfcf");
         
							}
						);
						jQuery('.account-link .my-account-links').hover(
							function () {
								//show its submenu
								jQuery('.my-account-links').show();
								jQuery('.account-link .header-link').css("border-top", "7px solid #000");

					 
							}, 
							function () {
								//hide its submenu
								jQuery('.my-account-links').hide();
								jQuery('.account-link .header-link').css("border-top", "7px solid #cfcfcf");
         
							}
						);
						jQuery('.flname').hover(
							function () {
								//show its submenu
								jQuery('.my-account-links').show();
								jQuery('.account-link .header-link').css("border-top", "7px solid #000");

					 
							}, 
							function () {
								//hide its submenu
								jQuery('.my-account-links').hide();
								jQuery('.account-link .header-link').css("border-top", "7px solid #cfcfcf");
         
							}
						
						);
									/*
jQuery('.account-link').hover(
										function() {
										  jQuery(this).addClass('light');
											},
										function() {
										  jQuery(this).removeClass('light');
									});
*/
					});
				</script>
			<?php }; ?>
	
				<?php echo $this->getChildHtml('topCart') ?>

			<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
				<div id="nav-invite">
				
					<a class="header-link" href="/index.php/rewardsref/customer/index/">Invite and earn</a>
				<?php /*WDCA CODE BEGIN*/ ?>
				<?php echo $this->getChildHtml('rewardsHeader') ?>
				<?php /*WDCA CODE END*/ ?>					
				
				</div>
			<?php }; ?>

			<div class="catalogLinks"><?php echo $this->getChildHtml('catalogLinks') ?></div>
			
			<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
				<div class="not-logged-in-header">
					<div class="login-register-header">
						<div class="login-header">
							<?php echo $this->getChildHtml('accountLinks') ?>
						</div>
						<div class="register-header">
							<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>customer/account/create">Register</a>
						</div>
					</div>				

						<!-- The provider login will be embedded in this div //-->
						<div class="connect">or connect</div>
						<div id="oa_social_login_header"></div>
						<script type="text/javascript">
							 oneall.api.plugins.social_login.build("oa_social_login_header", {
							  'providers' :  ['facebook', 'google', 'twitter', 'yahoo'], 
							  'callback_uri': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>arush-oneall/rpx/token_url/',
							  'css_theme_uri': '<?php echo $this->getSkinUrl(); ?>css/brandid.css'
							 });
						</script>	
				</div>
				
			<?php endif; ?>

		<div class="branding">
        <?php if ($this->getIsHomePage()):?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        </div>	   			
			
		</div>	
		 
		<?php //echo $this->getChildHtml('topMenu') ?>
    </div>
    
    
</div>
<div class="title-block">
	<div class="title-block-inner">
		<div class="title">
			<span><span><?php echo Mage::getSingleton('mage_page_block_html_head')->getTitle(); ?></span></span>
			
			<canvas id="meter" width="170" height="130">
			<p>Your browser doesn't support canvas.</p>
			</canvas>
    	    
		</div>
	</div>
</div>


<script type="text/javascript">


var meter = {
	timer: 0,
	deg2Rad: function (theta) {
		return (theta -180)* Math.PI / 180.0;
	},
	
	canvas: document.getElementById('meter'),
	
	size: { width: 170, height: 120, x: 85, y: 120 },
	startAngle: 15,
	endAngle: 165,
	currentAngle: 15,
	finalAngle: 98,
	hand: null,
	init: function() {
		$(this.canvas).setStyle({ position: 'absolute' });		


		this.hand = document.createElement('canvas');
		
		$(this.hand).setAttribute('width', this.size.width);
		$(this.hand).setAttribute('height', this.size.height);
		$(this.hand).setStyle({ position: 'absolute' });		
		$(this.canvas).up().appendChild(this.hand);
		
		context = this.hand.getContext('2d');
		
		context.beginPath();	    
		context.strokeStyle = '#000000';
		context.lineWidth = 1;
		context.moveTo(this.size.x-2, this.size.y-20);
		context.lineTo(this.size.x, this.size.y-115);
		context.lineTo(this.size.x+2, this.size.y-20);
		context.lineTo(this.size.x, this.size.y-15);
		context.lineTo(this.size.x-2, this.size.y-20);
	    context.stroke();		
		
	},
	
	
	
	draw: function() {
	
		this.canvas.width = this.canvas.width;
		
		var context = this.canvas.getContext('2d');

		context.beginPath();
		context.strokeStyle = '#d2002b';
		context.lineWidth = 60;
		var startAngle = this.deg2Rad(this.startAngle);
		var endAngle = this.deg2Rad(this.currentAngle);	
		context.arc(this.size.x,this.size.y,75,startAngle, endAngle, false);
	    context.stroke();
	    

		context.beginPath();	    
		context.strokeStyle = '#cfcfcf';
		context.lineWidth = 60;
		var startAngle = this.deg2Rad(this.currentAngle);
		var endAngle = this.deg2Rad(this.endAngle);
		context.arc(this.size.x,this.size.y,75,startAngle, endAngle, false);
	    context.stroke();
	    
//		this.hand.width = this.hand.width;	    

		context = this.hand.getContext('2d');
		context.rotate(this.deg2Rad(this.currentAngle));	
	    
	    		
	}
	
}
//meter.draw();

function animate(angle) {
	meter.finalAngle = angle;
	if (meter.currentAngle >= meter.finalAngle) {
		clearInterval(meter.timer);
	} else {
		meter.currentAngle += 2;
		meter.draw();
	}
}
meter.init();
meter.timer = setInterval('animate(90)', 100);
</script>
<style type="text/css">
#meter {
	background: #fff;
	width: 170px;
	height: 120px;
}
</style>
