<div class="dashboard">
	<div class="box-account box-info">
		<div class="box-head">
			<h2>Janrain Engage</h2>
		</div>
		<div class="col2-set">
			<div class="col-1">
				<div class="box">
					<div class="box-title">
						<h3>Identities</h3>
					</div>
					<div class="box-content">
						<ul>
						<?php
							$identifiers = Mage::helper('engage/identifiers')->get_identifiers(
								Mage::getSingleton('customer/session')->getCustomer()->getId()
							);

							foreach($identifiers as &$identifier) {
								echo '<li style="clear:both;"><div class="rpx_icon_small rpx_'
									. $identifier->getProvider()
									. '_small"></div><span class="rpx_profile_label">'
									. $identifier->getProfileName()
									. ' <small>(<a href="'
									. Mage::getUrl('engage/rpx/removeid', array('identifier' => $identifier->getId()))
									. '">remove</a>)</small></span></li>';
							}

						?>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-2">
				<div class="box">
					<div class="box-title">
						<h3>Add Identity</h3>
					</div>
					<div class="box-content">
						<?php
							$providers = Mage::helper('engage')->getRpxProviders();
							if (is_array($providers)) {
								$size = "30";
								$wrap_open = '<a class="rpxnow rpx_link_wrap" onclick="return false;" href="'
										. Mage::helper('engage')->getRpxAuthUrl(true)
										. '">';
								$wrap_close = '</a>';

								$rpx_buttons = '';
								foreach ($providers as $val) {
									$rpx_buttons .= '<div class="jn-icon jn-size' . $size . ' jn-' . $val . '" title="' . htmlentities($val) . '"></div>';
								}
								$buttons = '<div class="rpx_button">' . $rpx_buttons . '</div><div class="rpx_clear"></div>';

								echo $wrap_open . $buttons . $wrap_close;
							}
						?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>