
<?php
	$refererSet = false;
	if(Mage::getSingleton('core/session')->getReferer()) {
		$refererSet = true;
	}

	if($refererSet) {
		//get the referrer
		if (isset($_SERVER['HTTP_REFERER'])) {
			$referer = $_SERVER['HTTP_REFERER'];
		} else {
			$referer = "unknown";
		}
		//save it in a session variable
		Mage::getSingleton('core/session')->setReferer($referer); // store session data
	}
	else {
		$referer = Mage::getSingleton('core/session')->getReferer();
	}
?>
<div id="male-status">
	<div id="male-header" class="male-header">
		<div class="container">
			<div class="one-third column">
				<a id="logo" href="/" class="logo-button">
					<img class="gift-logo scale-with-grid" alt="BRANDiD logo" src="<?php echo $this->getSkinUrl('images/logo-beta.png')?>" title="BRANDiD Logo"/>
				</a>
				<div class="title-skip mobile">
					<a class="skip-this" href="#">Skip this</a>
				</div>
			</div>
			<div class="one-third column male-round">
				<div class="male-holder">
					<div id="male-colour" class="male-loading">
					</div>
					<div id="male-loader" class="male-loader">
					</div>
					
					<img src="<?php echo $this->getSkinUrl('images/male/male-round.png'); ?>" alt="MALE" class="male-round ani" title="feed the male"/>
					<div class="male-label-box">
						<span id="male-label">MALE&trade;</span>
					</div>
				</div>
				<div id="status">Establishing Connection</div>

			</div>
			<div class="one-third column">
				<div class="title-skip">
					<!-- <div class="male-title">
						Feed the Male&trade;
					</div> -->
					<a class="skip-this" href="#">Skip this</a>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
<!-- 		<div class="ten columns offset-by-three">
 -->			<div id="console"></div>
<!-- 		</div>
 -->	</div>
</div>
<script type="text/javascript">
	var $j = jQuery.noConflict();

	punter = new Object();
	
	function offside() {
		
	    // fade
		if($j('.console-fade').length == 0) { $j('#console').prepend('<div class="console-fade"></div>'); };

		var s = getLatestSpan();

		var delay = getDelayRequired();

		typeit();

		var url = new Array(
						"<?php echo $this->getSkinUrl('images/male/offside.jpg'); ?>"
						);
		var caption = "Which player is offside?\n\na. I'm a man. Player A is offside.\nb. I'm a woman who knows her football. Player A is offside.\nc. I'm a woman. Just show me a picture of Beckham.\n\nType [a], [b] or [c] and press [ENTER] ";
		var imageString = printImage(url,"offside",caption);
		performAppend(s, delay, imageString);

		offsideAnswer();
	}
	
	function startConsole() {
        jqconsole = $j('#console').jqconsole('Greetings earthling. MALE here, what\'s your name?\n', '>>> ');
        
        //give the header an id, this saves complications down the line
        $j('.jqconsole-header span').attr('id','male-welcome-msg');
        $j('#male-welcome-msg').typewriter();
        $j('#male-welcome-msg').css('color', '#444');

        startPrompt();
        // need this otherwise window flys around on load
        window.scrollTo(0,0);
		jqconsole.Focus;

	}

</script>

<script type="text/javascript">
	function registerUser(emailAd, firstname) {
		
		jqconsole.Write('Saving your progress... ', 'jqconsole-output wordwrap');
		typeit();
		var s = getLatestSpan();
		$(s).addClassName('loading');

	    $j.ajax({
		  type: "POST",
		  url: "/subscribe/newbie",
		  data: {
		  	email: emailAd,
		  	fname: firstname,
		  	source: '<?php echo $referer; ?>'
		  },
		  success: function(data) {
			alert('message: '+data);
			var retval = JSON.parse(data);

			if(retval.status == 1) {
				$j(s).removeClass('loading');
				$j(s).removeClass('red');

				$j(s).text('Almost there - we need you to confirm your email. Click on the link we just sent you. ');
				typeit();
	        }
	        else if(retval.status == 214) {
	        	$j(s).removeClass('loading');
				$j(s).removeClass('red');
				$j(s).text('Wait a sec, we\'ve already got you saved. Are you not receiving our emails? To stop our emails going to spam, please add <strong>help@getbrandid.com</strong> to your address book.');
				typeit();
	        }
	        else {
				$j(s).removeClass('loading');
				$j(s).addClass('red');
				$j(s).text(retval.message+'\nTry again: ');
				typeit();
				emailPrompt();
	        }
		  }
		});
	}
</script>

<script type="text/javascript">
	function loaded(){
			jQuery('#male-status').addClass('online');
			jQuery('.male-header').addClass('flyup');
			jQuery('#male-colour').removeClass('male-loading');
			jQuery('#male-colour').addClass('male-back');
			jQuery('#status').text('');
			setTimeout("startConsole()", 300);

		}

	jQuery(document).ready(function() {
		setTimeout("loaded()", 500);
	});

</script>

