<?php 

Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::getUrl("gifts.html"));

	$refererSet = false;
	if(Mage::getSingleton('core/session')->getReferer()) {
		$refererSet = true;
	}

	if($refererSet) {
		//get the referrer
		if (isset($_SERVER['HTTP_REFERER'])) {
			$referer = $_SERVER['HTTP_REFERER'];
		} else {
			$referer = "unknown";
		}
		//save it in a session variable
		Mage::getSingleton('core/session')->setReferer($referer); // store session data
	}
	else {
		$referer = Mage::getSingleton('core/session')->getReferer();
	}

?>
<div id="male-status">
	<div id="male-header" class="male-header">
		<div class="container">
			<div class="one-third column">
				<a id="logo" href="/" class="logo-button">
					<div class="gift-logo">
					</div>
				</a>
			</div>
			<div class="one-third column male-round">
				<div class="male-holder">
					<div id="male-colour" class="male-loading">
					</div>
					<div id="male-loader" class="male-loader">
					</div>
					
					<img src="<?php echo $this->getSkinUrl('images/male/male-round.png'); ?>" alt="MALE" class="male-round ani" title="feed the male"/>
					<div class="male-label-box">
						<span id="male-label">MALE&trade;</span>
					</div>
				</div>
				<div id="status">Establishing Connection</div>

			</div>
			<div class="one-third column">
				<div class="title-skip">
					<div class="male-title">
						Feed the Male&trade;
					</div>
					<a class="skip-this" href="#">Skip this</a>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
<!-- 		<div class="ten columns offset-by-three">
 -->			<div id="console"></div>
<!-- 		</div>
 -->	</div>
</div>
<script>
	var $j = jQuery.noConflict();

	function typeit() {
		/* types the latest element of the matched object passed */
		e = $j('.jqconsole-output');
		
		var count = e.length -1;
		var randomId = 'male' + (Math.floor(Math.random()*10000000)+1);
		var s = $j(e).find('span')[count];
		$j(s).attr('id',randomId);
        
        $j('#'+randomId).typewriter();
		$j('#'+randomId).css('color', '#444');
		
	}
	function startConsole() {
      //$j(function {
        var jqconsole = $j('#console').jqconsole('Greetings earthling. MALE here, what\'s your name?\n', '>>> ');
        $j('.jqconsole-header span').attr('id','male-welcome-msg');
        $j('#male-welcome-msg').typewriter();
        $j('#male-welcome-msg').css('color', '#444');

        var emailPrompt = function () {
          // Start the prompt with history enabled.
          jqconsole.Prompt(true, function (input) {
            // Output input with the class jqconsole-output.
            jqconsole.Write('You entered:' + input + '\nI\'m going to spam the hell out of you ', 'jqconsole-output wordwrap');
            typeit();
          });
        };
        var startPrompt = function () {
          // Start the prompt with history enabled.
          jqconsole.Prompt(true, function (input) {
            // Output input with the class jqconsole-output.
            jqconsole.Write('Hmm... '+ input + '. That\'s an awesome name.\nYou must be an awesome person.\n\nWhat\'s your email address?\n', 'jqconsole-output wordwrap');
            typeit();
            // Restart the prompt.
            emailPrompt();
          });
        };
        startPrompt();
		jqconsole.Focus;

        //give the header an id, this saves complications down the line
     // });
	}

</script>
<script type="text/javascript">
	function loaded(){
			jQuery('#male-status').addClass('online');
			jQuery('.male-header').addClass('flyup');
			jQuery('#male-colour').removeClass('male-loading');
			jQuery('#male-colour').addClass('male-back');
			jQuery('#status').text('');
			setTimeout("startConsole()", 300);
		}

	jQuery(document).ready(function() {
		setTimeout("loaded()", 5000);
	});

</script>

