<?php
	$refererSet = false;
	if(Mage::getSingleton('core/session')->getReferer()) {
		$refererSet = true;
	}

	if($refererSet) {
		//get the referrer
		if (isset($_SERVER['HTTP_REFERER'])) {
			$referer = $_SERVER['HTTP_REFERER'];
		} else {
			$referer = "unknown";
		}
		//save it in a session variable
		Mage::getSingleton('core/session')->setReferer($referer); // store session data
	}
	else {
		$referer = Mage::getSingleton('core/session')->getReferer();
	}
?>

<div id="male-status">
	<div id="male-header" class="male-header">
		<div class="container">
			<div class="one-third column">
				<a id="logo" href="/" class="logo-button">
					<img class="gift-logo scale-with-grid" alt="BRANDiD logo" src="<?php echo $this->getSkinUrl('images/logo-beta.png')?>" title="BRANDiD Logo"/>
				</a>
			</div>
			<div class="one-third column male-round">
				<div class="male-holder">
					<div id="male-colour" class="male-loading">
					</div>
					<div id="male-loader" class="male-loader">
					</div>
					
					<img src="<?php echo $this->getSkinUrl('images/male/male-round.png'); ?>" alt="MALE" class="male-round ani" title="feed the male"/>
					<div class="male-label-box">
						<span id="male-label">MALE&trade;</span>
					</div>
				</div>
				<div id="status">Establishing Connection</div>

			</div>
		</div>
	</div>
	<div class="progress-bar">
		<div class="container">
				<div class="one-third column">
					<div class="progress-content active">
						<div class="circle-back">
						</div>
						<div class="circle">
							<div class="circle-text">
								1
							</div>
						</div>
						<div class="progress-sub">Feed the MALE™</div>
					</div>
				</div>
				<div class="one-third column">
					<div class="progress-content">
						<div class="circle-back">
						</div>
						<div class="circle">
							<div class="circle-text">
								2
							</div>
						</div>
						<div class="progress-sub">Confirm Plan</div>
					</div>
				</div>
				<div class="one-third column">
					<div class="progress-content">
						<div class="circle-back">
						</div>
						<div class="circle">
							<div class="circle-text">
								3
							</div>
						</div>
						<div class="progress-sub">Checkout</div>
					</div>
				</div>
		</div>
	</div>
	<div class="male-console container">
			<div id="console"></div>
	</div>
</div>
<script type="text/javascript">
	var $j = jQuery.noConflict();
	//global punter object
	var punter = new Object();
	createPunter();
	function workImages(appendTo, mobile) {
	
		var delay = getDelayRequired();
		// type has to go after, otherwise the delay counts only one or two chars
		typeit();

		var images = new Array();
		images[0] = new Array("<?php echo $this->getSkinUrl('images/male/work/1.jpg'); ?>", "work-image", "a. Smart", "workAa(true)");
		images[1] = new Array("<?php echo $this->getSkinUrl('images/male/work/2.jpg'); ?>", "work-image", "b. Casual", "workAb(true)");
		images[2] = new Array("<?php echo $this->getSkinUrl('images/male/work/3.jpg'); ?>", "work-image", "c. Laid Back", "workAc(true)");
		images[3] = new Array("<?php echo $this->getSkinUrl('images/male/work/4.jpg'); ?>", "work-image", "d. Gorilla Suit", "workAd(true)");

		var imageString = printImage(images);
		performAppend(appendTo, imageString);
		if(mobile) {
			var buttons = new Array();
			buttons[0] = new Array("convert","Smart", "workAa(true)");
			buttons[1] = new Array("convert","Casual", "workAb(true)");
			buttons[2] = new Array("convert","Laid Back", "workAc(true)");
			buttons[3] = new Array("convert","Gorilla Suit", "workAd(true)");
			insertImageButtons(buttons,"work-image");
		}
		else {
			workA();
		}
	}


	function playImages(appendTo, mobile) {
	
		var delay = getDelayRequired();
		// type has to go after, otherwise the delay counts only one or two chars
		typeit();

		var images = new Array();
		images[0] = new Array("<?php echo $this->getSkinUrl('images/male/play/1.jpg'); ?>", "play-image", "a. Shirts", "playAa(true)");
		images[1] = new Array("<?php echo $this->getSkinUrl('images/male/play/2.jpg'); ?>", "play-image", "b. Polos", "playAb(true)");
		images[2] = new Array("<?php echo $this->getSkinUrl('images/male/play/3.jpg'); ?>", "play-image", "c. Tees", "playAc(true)");
		images[3] = new Array("<?php echo $this->getSkinUrl('images/male/play/4.jpg'); ?>", "play-image", "d. Elvis Outfit", "playAd(true)");

		var imageString = printImage(images);
		performAppend(appendTo, imageString);
		if(mobile) {
			var buttons = new Array();
			buttons[0] = new Array("convert","Suave", "playAa(true)");
			buttons[1] = new Array("convert","Polos", "playAb(true)");
			buttons[2] = new Array("convert","Tees", "playAc(true)");
			buttons[3] = new Array("convert","Elvis Outfit", "playAd(true)");
			insertImageButtons(buttons,"play-image");
		}
		else {
			playA();
		}
	}
	
	var attach;
	attach = function() {

		
		var imageUrl = '<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('offside_pic')->toHtml(); ?>';
			//must be format <p><img src="..." /></p>

		var imageUrl = imageUrl.split('\"');

		var images = new Array();
		images[0] = new Array(imageUrl[1],"offside", "Which player is offside?");

		var imageString = printImage(images);
		$j('#male-welcome-msg').append(imageString);

		//make question text appear
		var s = getLatestSpan();
		$j(s).css('color','#444');
	}

	function beckham() {
		var images = new Array();
		images[0] = new Array("<?php echo $this->getSkinUrl('images/male/offside/beckham.jpeg'); ?>","offside beckham", '"We should have gone to BRANDiD"');

		var imageString = printImage(images);
		$j('#male-welcome-msg').append(imageString);
	}


	function startMale() {

		if(punter.fname != undefined) {
	        var backMessage = new Array(", I thought you were gone forever! ", ", missing me already, eh? ", ", I knew you\'d be back. I could feel it. ");
	        var i = Math.floor(Math.random()*3);
        	
        	var q = 'Hey '+punter.fname+backMessage[i];
        	newQ(q);
        	
        	setTimeout('returningVisitor();',1500);
        	initiate();
        }
        else {

        	var q = 'Greetings earthling. MALE™ here, what\'s your name? ';
        	newQ(q);

			nameA();
        }

	}

</script>

<script type="text/javascript">
	function getReferer() {
		var referer;
		referer = '<?php echo $referer; ?>';
		return referer;
	}
</script>

<script type="text/javascript">
	function loaded(){
			jQuery('#male-status').addClass('online');
			jQuery('.male-header').addClass('flyup');
			jQuery('#male-colour').removeClass('male-loading');
			jQuery('#male-colour').addClass('male-back');
			jQuery('#status').text('');
			setTimeout("startMale()", 300);
		}

	jQuery(document).ready(function() {
		window.scrollTo(0,0);
		setTimeout("loaded()", 3000);
	});

</script>

