// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.finalSave = function() {
    var answers, q;
    wipeConsole();
    recommend();
    saveProgress("finalSave");
    punter.goAfterSave = "finalSave";
    answers = {
      work: punter.work,
      play: punter.play,
      roll: punter.roll
    };
    punter.maleAnswers = JSON.stringify(answers);
    q = 'I\'ll be adding more questions soon, but that\'s all I need right now to recommend you a plan. ';
    newQ(q);
    typeit();
    jqconsole.Write('Computing manhood percentage...  ', 'jqconsole-output loading-flash wordwrap');
    typeit();
    setTimeout(function() {
      return finalRegister();
    }, 1000);
    return setTimeout(function() {
      return replaceText(0);
    }, 4000);
  };

  root.replaceText = function(num) {
    var msg, s, shareCallback;
    shareCallback = function() {
      return replaceText(num);
    };
    msg = ['Please bear with me... ', 'I\'m M.A.L.E., I can only do one thing at a time... '];
    s = getLatestSpan();
    $j(s).text(msg[num]);
    num++;
    typeit();
    if (num < msg.length && $j(s).text() === msg[num - 1]) {
      console.log($j(s).text() + '\n' + msg[num - 1]);
      return setTimeout(function() {
        return replaceText(num);
      }, 2500);
    } else {

    }
  };

}).call(this);
