<div class="account-linking socialize-linking">
    <div class="page-title">
        <h1><?php echo $this->__('Do you already have an existing account on this site?') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getLinkingPostUrl() ?>" method="post" id="linking-form">
        <div class="col1-set">
            <div class="col-1 registered-users">
                <div class="content">
                    <p><?php echo str_replace('$nickname',$this->getNickname()."(".$this->getProvider().")",__('If so, you can link $nickname to your account:')) ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button type="submit" title="<?php echo $this->__('Link Accounts') ?>" class="button"><span><span><?php echo $this->__('Link Accounts') ?></span></span></button>
                    <p/>
                </div>
         	</div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('linking-form', true);
    //]]>
        
    </script>
    
	<div class="register-form">
    	<?php echo $this->getChildHtml('customer_form_register'); ?>
	</div>    
</div>
