<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=447675568617682";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container withShadow">
	<div class="top-block">
		

		<div class="content">

			<div class="text-overlay clearfix">
				
				<div class="top-section clearfix">

					

					<div class="six columns">

						<div class="app-holder">
							<img src="<?php echo $this->getSkinUrl('images/arush/leanlanding/app/beta-iphone.png'); ?>" alt="butler" class="scale-with-grid app-img">
						</div>
					</div>

					<div class="ten columns">
						<div class="landing-title">
							<span class="landing-title-span">Shop with an app that knows men.<br/>And knows you.</span>
							<div class="landing-subtitle">
								<br/><br/>
								<span>Introducing the <span class="bold">simplest</span>, most <span class="bold">nag-free</span> way<br/>for men to get their clothes.</span>
							</div>
						</div>
						<div class="signup">
							<form id="download-app" action="/twilio/download-app.php" class="get-the-app">
								<div class="blurb">
									Choose your weapon
								</div>
								<a id="ios" class="mobile-os-selector convert secondary">
									<div class="os-title">iOS</div>
								</a>

								<a id="android" class="mobile-os-selector convert secondary android">
									<div class="os-title">Android</div>
								</a>
								<div class="clearfix"></div>
								<div class="blurb">
									Enter your mobile number for early beta access
								</div>
								<div class="get-the-app-input clearfix">
									<div id="mobile-prefix" class="input-overlay">+44</div>
									<input type="text" id="mobile-input" name="mobile-input" class="clear-input">
									<div id="twilio-response" class="start"></div>
									<button type="submit" id="submit-mobile" class="convert get-the-app">Txt me a download link!</button>
									
								</div>
							</form>

							<div class="share-top clearfix">
								<div class="share like">
									<div class="fb-like" data-href="http://www.facebook.com/getbrandid" data-send="false" data-layout="button_count" data-width="200" data-show-faces="false" data-font="arial"></div>
								</div>
								<div class="share">
									<a href="https://twitter.com/share" class="twitter-share-button" data-text="Finally, a shopping app designed for men. i.e. no more shopping. Get on the beta!" data-via="BRANDiD" data-related="male" data-hashtags="shoplikeaman">Tweet</a>
									<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
								</div>
								<div class="share follow">
									<a href="https://twitter.com/BRANDiD" class="twitter-follow-button" data-show-count="false">Follow @BRANDiD</a>
									<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
								</div>
							</div>
						</div>
					</div>
				</div> <!-- end top-section -->

			</div>

			<div class="sub-block-holder">
				
				<div class="shadow-holder">
					<div class="shadow-ninja"></div>
				</div>
				<div class="sub-block-bg first">
					<div class="one-third column sub-block">
						<div class="landing-title">Talk to M.A.L.E.</div>
						
						<img src="<?php echo $this->getSkinUrl('images/arush/leanlanding/app/icon-chat.png'); ?>" alt="Moustache weight training" class="scale-with-grid explain-img">

						<div class="explain">M.A.L.E. (Masculine Algorithmic Learning Engine) learns exactly what gear you wear, and remembers your payment deets so next time you need something you're just a tap away.</div>
					</div>
				</div>
				
				<div class="sub-block-bg">
					<div class="one-third column sub-block">
						<div class="landing-title">Feed M.A.L.E. With Tags</div>

						<img src="<?php echo $this->getSkinUrl('images/arush/leanlanding/app/icon-tags.png'); ?>" alt="Moustache singing" class="scale-with-grid explain-img">

						<div class="explain">Boxers riding too high? Didn't like that brand? Tag deliveries with specific, actionable feedback so M.A.L.E. keeps learning.</div>
					</div>
				</div>

				<div class="sub-block-bg">
					<div class="one-third column sub-block">
						<div class="landing-title">Reorder in one tap, or snooze</div>

						<img src="<?php echo $this->getSkinUrl('images/arush/leanlanding/app/icon-phone.png'); ?>" alt="Moustache oils" class="scale-with-grid explain-img">

						<div class="explain">Depending on your order M.A.L.E. will figure out when you need a top-up, and hit you up with a reminder. Reorder in one tap, or snooze to deal with it later. Simple.</div>
					</div>
				</div>

				

			</div>

			

		</div>

		
	</div>



</div>

<!-- <div class="quotes container clearfix">

	<div class="row endorsement-title clearfix">
		Unofficial Endorsements
	</div>

	<div class="quote-box one-third column">
	<img src="<?php // echo $this->getSkinUrl('images/arush/movember/magnum.jpg'); ?>" class="scale-with-grid quote-img" alt="Magnum PI"/>
	<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
	<span class="quote left">A moustache is like steroids for your face. It makes you look strong.</span>
	<div class="quote-triangle"></div>
	<span class="author">Magnum PI</span>
	<span class="caption-small">Man since 1980</span></div>
	
	<div class="quote-box one-third column">
	<img src="<?php // echo $this->getSkinUrl('images/arush/movember/borat.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
	<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
	<span class="quote middle">Old Kazakh saying. Man with much power have much moustache and man with much moustache have much power. In the chram. High five.</span>
	<div class="quote-triangle"></div>
	<span class="author">Borat</span>
	<span class="caption-small">Man since 1999</span></div>
	
	<div class="quote-box one-third column last">
	<img src="<?php // echo $this->getSkinUrl('images/arush/movember/neo.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
	<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
	<span class="quote right">There is no moustache.</span>
	<div class="quote-triangle"></div>
	<span class="author">Neo</span>
	<span class="caption-small">Man since 1999</span></div>
	
</div> -->

<div class="container withShadow">
	<div class="share-block">
		<div class="landing-title">
			<span>Like what we're doing? Lets stay in touch</span>
			<div class="landing-subtitle">
				<span>Choose how you want to receive your updates from us</span>
			</div>
		</div>
		<!-- <div class="big-share-buttons clearfix">
				<div class="one-third column">
					<div class="share like">
						<div class="fb-like" data-href="http://www.getbrandid.com/get/that/app" data-send="false" data-width="250" data-show-faces="true"></div>
					</div>
				</div>

				<div class="one-third column">
					<div class="share">
						<a href="https://twitter.com/share" class="twitter-share-button" data-via="BRANDiD" data-related="male" data-hashtags="movember">Tweet</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
					</div>
				</div>

				<div class="one-third column">
					<div class="share">
						<span id="tumblr_button_abc123"></span>
					</div>
				</div>
			</div> -->
		
		<div class="sub-block-holder">
				
			<div class="shadow-holder">
				<div class="shadow-ninja"></div>
			</div>
			<div class="sub-block-bg first">
				<div class="one-third column sub-block">
					<div class="explain"><span class="bold">Like us on Facebook</span> for cool man stuff daily.</div>

					<div class="fb-like-box" data-href="http://www.facebook.com/getbrandid" data-width="292" data-height="340" data-show-faces="false" data-border-color="#EBEBEB" data-stream="true" data-header="false"></div>

					
				</div>
			</div>
			
			<div class="sub-block-bg">
				<div class="one-third column sub-block">



					<div class="explain"><span class="bold">Follow us on Twitter</span> for cool man stuff daily.</div>


					<a class="twitter-timeline" href="https://twitter.com/BRANDiD" data-widget-id="262989798569017344">Tweets by @BRANDiD</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


				</div>
			</div>

			<div class="sub-block-bg">
				<div class="one-third column sub-block">
						
						<script type="text/javascript">
							setTimeout(function(){
								loadTumblrWidget();
							},5000);
						</script>

						<div class="explain"><span class="bold">Follow us on Tumblr</span> for cool man stuff daily.</div>
					
					<div id="tumblrWidget">
						<div class="timeline-header clearfix">
							<h1 class="summary">Posts</h1>
							<iframe class="btn right" frameborder="0" border="0" scrolling="no" allowtransparency="true" height="25" width="200" src="http://platform.tumblr.com/v1/follow_button.html?button_type=1&tumblelog=because-we-are-men&color_scheme=light"></iframe>
						</div>
						
						<div class="stream">
							<div id="tumblr-badge" class="loading"></div>
						</div>

					</div>

				</div>
			</div>

		</div>

	</div>
</div>

<script type="text/javascript">

	var $j = jQuery.noConflict();
	var phoneOS = "none chosen";

	/* track Phone OS */
	$j("#ios").click(function() {
		phoneOS = "iOS";
	  	$j('.mobile-os-selector').removeClass('active');
	  	$j('#ios').addClass('active');
	});

	$j("#android").click(function() {
		phoneOS = "android";
		$j('.mobile-os-selector').removeClass('active');
	  	$j('#android').addClass('active');
	});


	/* KISSmetrics tracking */
    if(typeof(_kmq) !== "undefined") {
    	_kmq.push(['record', 'Viewed App Download Page']);
    }
    /* Mixpanel tracking */
    if(typeof(mixpanel) !== "undefined") {
		mixpanel.track_pageview("/get/that/app");
    }



	
	/* attach a submit handler to the form */
	  $j("#download-app").submit(function(event) {



	    /* stop form from submitting normally */
	    event.preventDefault(); 
	        
	    /* get some values from elements on the page: */
	    var $form = $j(this),
	        mobileInput = $form.find('input[name="mobile-input"]').val(),
	        url = $form.attr('action');

	    /* KISSmetrics tracking */
	    if(typeof(_kmq) !== "undefined") {
			_kmq.push(['record', 'Clicked App Download Link']);
	    	_kmq.push(['set', {'mobile number':mobileInput, 'Phone OS':phoneOS}]);
	    }

	    /* Mixpanel Tracking */
	   	if(typeof(mixpanel) !== "undefined") {
	   		mixpanel.track("Clicked App Download Link", {"Phone OS": phoneOS, "Phone number": mobileInput});
		}


	    if(mobileInput.charAt(0) == 0) {
			// remove first digit
			mobileInput = mobileInput.substring(1, mobileInput.length);
		}

		var mobile = $j('#mobile-prefix').text() + mobileInput;
	    

		/* disable the button */

		$j('#submit-mobile').attr('disabled', true);
		$j('#twilio-response').addClass('loading');


	    /* Send the data using post and put the results in a div */
	    $j.post( url, { "mobile": mobile },
	      function( data ) {
	      	$j('#submit-mobile').removeAttr('disabled');
	      	$j('#twilio-response').removeClass('loading');
	      	alert('Cool, check your phone for a text message!');
	          //var content = $( data ).find( '#content' );
	          //$( "#result" ).empty().append( content );
	      }, "json");
	  });


		// $.ajax({  
		//   type: "GET",
		//   url: "/twilio/download-app.php",  
		//   data: dataString,  
		//   success: function() {  
		//     $('#download-app').html("<div id='message'></div>");  
		//     $('#message').html("<h2>Contact Form Submitted!</h2>")  
		//     .append("<p>We will be in touch soon.</p>")  
		//     .hide()  
		//     .fadeIn(1500, function() {  
		//       // $('#message').append("<img id='checkmark' src='images/check.png' />");  
		//     });  
		//   }  
		// });

</script>


<script type="text/javascript">
	function loadTumblrWidget() {

		// load js in after user has indicated they are hanging around on the page

		(function($) {
			$.ajax({ url:"<?php echo $this->getSkinUrl('js/arush/landing/tumblrBadge-1.1-ck.js'); ?>", cache:true, dataType:"script"
			}).done(function ( data ) {
				$('#tumblr-badge').removeClass('loading');
			});
		})(jQuery);
	}
</script>
