<div id="top" class="keep-calm-signup-container">
	<?php echo $this->getChildHtml('landing_header'); ?>

</div>
<?php
	$referer = false;
	$refererSet = false;
	if(Mage::getSingleton('core/session')->getReferer()) {
		$refererSet = true;
		$referer = Mage::getSingleton('core/session')->getReferer();
	}

	if(!$refererSet) {
		//get the referrer
		if (isset($_SERVER['HTTP_REFERER'])) {
			$referer = $_SERVER['HTTP_REFERER'];
		} else {
			$referer = "unknown";
		}
		//save it in a session variable
		Mage::getSingleton('core/session')->setReferer($referer); // store session data
	}
?>



<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=447675568617682";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container withShadow">
	<div class="top-block">
		

		<div class="content">

			<div class="big-tash-holder">

				<!-- <img src="<?php // echo $this->getSkinUrl('images/arush/movember/big-tash.png'); ?>" alt="" class="scale-with-grid big-tash"> -->
				<div class="big-tash"></div>
			</div>

			<div class="text-overlay clearfix">
				<div class="landing-title">
					<span>Get a Mo Butler for Movember</span>
					<div class="landing-subtitle">
						<span>Movember means that us men need to <span class="bold">grow large or go home.</span> With that in mind, BRANDiD has put together the ultimate in <span class="bold">bespoke moustache experiences.</span><br/>A dedicated 24/7 specialist <span class="bold">tache technician.</span></span>
					</div>
				</div>
				<div class="ten columns">
					<div class="mo-price-box-container">
						
						<div class="share-top clearfix">
							<div class="share like">
								<div class="fb-like" data-href="http://www.facebook.com/getbrandid" data-send="false" data-layout="button_count" data-width="200" data-show-faces="false" data-font="arial"></div>
							</div>
							<div class="share">
								<a href="https://twitter.com/share" class="twitter-share-button" data-text="The ultimate #Movember package for a man with a big heart, deep pockets and big cojones" data-via="BRANDiD" data-related="male">Tweet</a>
								<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
							</div>
							<div class="share">
								<a href="https://twitter.com/BRANDiD" class="twitter-follow-button" data-show-count="false">Follow @BRANDiD</a>
								<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
							</div>
							
							

						</div>

						<div class="mo-price-box">
							<div class="price-header">
								<span>a one time only offer of</span>
							</div>
							<div class="price-details">
								<div class="big-price">
									<span>£10,000<sup>*</sup></span>
								</div>
								<div class="price-subtitles">
									<span class="blue">Make the most of your mo, bro.</span><br/><br/>
									<span>An expertly crafted package for men with big hearts, deep pockets and massive cojones.</span>
								</div>

							</div>
							<div class="buy-container clearfix">
								<a href="https://brandid.recurly.com/subscribe/moustache-concierge" class="convert buy">DONATE NOW!</a>
							</div>
						</div>
						<div class="price-box-subtext">
							<span><sup>*</sup>Profits go to charity</span>
						</div>

					</div>
					
				</div>
				<div class="six columns">
					<div class="butler-holder">
						<img src="<?php echo $this->getSkinUrl('images/arush/movember/butler.gif'); ?>" alt="butler" class="scale-with-grid butler-img">
					</div>
				</div>

			</div>

			<div class="sub-block-holder">
				
				<div class="shadow-holder">
					<div class="shadow-ninja"></div>
				</div>
				<div class="sub-block-bg first">
					<div class="one-third column sub-block">
						<div class="landing-title">Tache Training</div>
						
						<img src="<?php echo $this->getSkinUrl('images/arush/movember/training.png'); ?>" alt="Moustache weight training" class="scale-with-grid explain-img">

						<div class="explain">Your butler will create a personalized daily <span class="bold">fitness regime for your follicles</span>. Moustache weights, cheek crunches, lip curls and chin-ups will all be utilized to <span class="bold">prepare your face for greatness.</span></div>
					</div>
				</div>
				
				<div class="sub-block-bg">
					<div class="one-third column sub-block">
						<div class="landing-title">Mo Massages</div>

						<img src="<?php echo $this->getSkinUrl('images/arush/movember/oils.png'); ?>" alt="Moustache oils" class="scale-with-grid explain-img">

						<div class="explain">A combination of <span class="bold">oils, unguents and embrocations</span> will be regularly applied to your upper lip to soothe, stimulate and support the growth of your <span class="bold">heroic Handlebar, feisty Fu Manchu or dangerous Dali.</span></div>
					</div>
				</div>

				<div class="sub-block-bg">
					<div class="one-third column sub-block">
						<div class="landing-title">Whisker Warbling</div>

						<img src="<?php echo $this->getSkinUrl('images/arush/movember/singing.png'); ?>" alt="Moustache singing" class="scale-with-grid explain-img">

						<div class="explain">Like plants, <span class="bold">moustaches grow when serenaded to.</span> So what could be better than a regular burst of Mo’ Better Blues from your butler in the morning to get that that <span class="bold">face foliage thriving.</span></div>
					</div>
				</div>

			</div>

			

		</div>

		
	</div>



</div>

<div class="quotes container clearfix">

	<div class="row endorsement-title clearfix">
		Unofficial Endorsements
	</div>

	<div class="quote-box one-third column">
	<img src="<?php echo $this->getSkinUrl('images/arush/movember/magnum.jpg'); ?>" class="scale-with-grid quote-img" alt="Magnum PI"/>
	<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
	<span class="quote left">A moustache is like steroids for your face. It makes you look strong.</span>
	<div class="quote-triangle"></div>
	<span class="author">Magnum PI</span>
	<span class="caption-small">Man since 1980</span></div>
	
	<div class="quote-box one-third column">
	<img src="<?php echo $this->getSkinUrl('images/arush/movember/borat.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
	<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
	<span class="quote middle">Old Kazakh saying. Man with much power have much moustache and man with much moustache have much power. In the chram. High five.</span>
	<div class="quote-triangle"></div>
	<span class="author">Borat</span>
	<span class="caption-small">Man since 1999</span></div>
	
	<div class="quote-box one-third column last">
	<img src="<?php echo $this->getSkinUrl('images/arush/movember/neo.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
	<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
	<span class="quote right">There is no moustache.</span>
	<div class="quote-triangle"></div>
	<span class="author">Neo</span>
	<span class="caption-small">Man since 1999</span></div>
	
</div>

<div class="container withShadow">
	<div class="share-block">
		<div class="landing-title">
			<span>What?<br/>You left your £10k in your other trousers? Shame.</span>
			<div class="landing-subtitle">
				<span>Share this page with your friends, maybe one of them is feeling more generous than you.</span>
			</div>
		</div>
		<div class="big-share-buttons clearfix">
				<div class="one-third column">
					<div class="share like">
						<div class="fb-like" data-href="http://www.getbrandid.com/get/that/butler" data-send="false" data-width="250" data-show-faces="true"></div>
					</div>
				</div>

				<div class="one-third column">
					<div class="share">
						<a href="https://twitter.com/share" class="twitter-share-button" data-text="The ultimate #Movember package for a man with a big heart, deep pockets and big cojones" data-via="BRANDiD" data-related="male">Tweet</a>
						<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
					</div>
				</div>

				<div class="one-third column">
					<div class="share">
						<span id="tumblr_button_abc123"></span>
					</div>
				</div>
			</div>
		
		<div class="sub-block-holder">
				
			<div class="shadow-holder">
				<div class="shadow-ninja"></div>
			</div>
			<div class="sub-block-bg first">
				<div class="one-third column sub-block">
					<div class="explain"><span class="bold">Like us on Facebook</span> for cool man stuff daily.</div>

					<div class="fb-like-box" data-href="http://www.facebook.com/getbrandid" data-width="292" data-height="340" data-show-faces="false" data-border-color="#EBEBEB" data-stream="true" data-header="false"></div>

					
				</div>
			</div>
			
			<div class="sub-block-bg">
				<div class="one-third column sub-block">



					<div class="explain"><span class="bold">Follow us on Twitter</span> for cool man stuff daily.</div>


					<a class="twitter-timeline" href="https://twitter.com/BRANDiD" data-widget-id="262989798569017344">Tweets by @BRANDiD</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


				</div>
			</div>

			<div class="sub-block-bg">
				<div class="one-third column sub-block">
						
						<script type="text/javascript">
							setTimeout(function(){
								loadTumblrWidget();
							},5000);
						</script>

						<div class="explain"><span class="bold">Follow us on Tumblr</span> for cool man stuff daily.</div>
					
					<div id="tumblrWidget">
						<div class="timeline-header clearfix">
							<h1 class="summary">Posts</h1>
							<iframe class="btn right" frameborder="0" border="0" scrolling="no" allowtransparency="true" height="25" width="200" src="http://platform.tumblr.com/v1/follow_button.html?button_type=1&tumblelog=because-we-are-men&color_scheme=light"></iframe>
						</div>
						
						<div class="stream">
							<div id="tumblr-badge" class="loading"></div>
						</div>

					</div>

				</div>
			</div>

		</div>

	</div>
</div>



<!-- Set these variables wherever convenient -->
<script type="text/javascript">
    var tumblr_photo_source = "http://brandid.s3.amazonaws.com/landing/mobutler.png";
    var tumblr_photo_caption = "Movember means that us men need to grow large or go home. With that in mind, BRANDiD has put together the ultimate in bespoke moustache experiences. A dedicated 24/7 specialist tache technician.";
    var tumblr_photo_click_thru = "http://www.getbrandid.com/get/that/butler";
</script>

<!-- Put this code at the bottom of your page -->
<script type="text/javascript">
    var tumblr_button = document.createElement("a");
    tumblr_button.setAttribute("href", "http://www.tumblr.com/share/photo?source=" + encodeURIComponent(tumblr_photo_source) + "&caption=" + encodeURIComponent(tumblr_photo_caption) + "&clickthru=" + encodeURIComponent(tumblr_photo_click_thru));
    tumblr_button.setAttribute("title", "Share on Tumblr");
    tumblr_button.setAttribute("style", "display:inline-block; text-indent:-9999px; overflow:hidden; width:129px; height:20px; background:url('http://platform.tumblr.com/v1/share_3.png') top left no-repeat transparent;");
    tumblr_button.innerHTML = "Share on Tumblr";
    document.getElementById("tumblr_button_abc123").appendChild(tumblr_button);
</script>



<script type="text/javascript">
	function loadTumblrWidget() {

		// load js in after user has indicated they are hanging around on the page

		(function($) {
			$.ajax({ url:"<?php echo $this->getSkinUrl('js/arush/landing/tumblrBadge-1.1-ck.js'); ?>", cache:true, dataType:"script"
			}).done(function ( data ) {
				$('#tumblr-badge').removeClass('loading');
			});
		})(jQuery);
	}
</script>

<?php
	if(isset($_GET["fb_ad_id"])) { ?>

		<script type="text/javascript">
			
			// Facebook ads to KISSmetrics tracking
			if(_kmq !== undefined) {
				_kmq.push(['set', {'fb_ad_id':'<?php echo $_GET["fb_ad_id"]; ?>'}]);

			}
		
		</script>

	<?php	}

	if(isset($_GET["fb_ad_group"])) { ?>

		<script type="text/javascript">
			
			// Facebook ads to KISSmetrics tracking
			if(_kmq !== undefined) {
				_kmq.push(['set', {'fb_ad_group':'<?php echo $_GET["fb_ad_group"]; ?>'}]);

			}
		
		</script>

	<?php 	}
?>