<div id="mainContainer" class="container">
	<div class="top-block">
		

		<div class="content">

			<div class="big-tash-holder">

				<!-- <img src="<?php // echo $this->getSkinUrl('images/arush/movember/big-tash.png'); ?>" alt="" class="scale-with-grid big-tash"> -->
				<div class="big-tash"></div>
			</div>

			<div class="text-overlay clearfix">
				<div class="landing-title">
					<span>Get a Mo Butler for Movember</span>
					<div class="landing-subtitle">
						<span>Movember means that us men need to grow large or go home.<br/>With that in mind, BRANDiD has put together the ultimate in bespoke moustache experiences.<br>A dedicated 24/7 specialist tache technician.</span>
					</div>
				</div>
				<div class="ten columns">
					<div class="mo-price-box-container">
						
						<div class="share-top clearfix">
							<div class="share like">
								<div class="fb-like" data-href="http://www.facebook.com/getbrandid" data-send="false" data-layout="button_count" data-width="200" data-show-faces="false" data-font="arial"></div>
							</div>
							<div class="share">
								<a href="https://twitter.com/share" class="twitter-share-button" data-via="BRANDiD" data-related="male" data-hashtags="movember">Tweet</a>
							<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
							</div>
							<div class="share">
								<a href="https://twitter.com/BRANDiD" class="twitter-follow-button" data-show-count="false">Follow @BRANDiD</a>
								<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
							</div>
							
							

						</div>

						<div class="mo-price-box">
							<div class="price-header">
								<span>a one time only offer of</span>
							</div>
							<div class="price-details">
								<div class="big-price">
									<span>£10,000<sup>*</sup></span>
								</div>
								<div class="price-subtitles">
									<span class="blue">Make the most of your mo, bro.</span><br/><br/>
									<span>An expertly crafted package for men with big hearts, deep pockets and massive cojones.</span>
								</div>

							</div>
							<div class="buy-container clearfix">
								<a href="https://brandid.recurly.com/subscribe/moustache-concierge" class="convert buy">DONATE NOW!</a>
							</div>
						</div>
						<div class="price-box-subtext">
							<span><sup>*</sup>All profits go directly to The Movember Foundation</span>
						</div>

					</div>
					
				</div>
				<div class="six columns">
					<div class="butler-holder">
						<img src="<?php echo $this->getSkinUrl('images/arush/movember/butler.gif'); ?>" alt="butler" class="scale-with-grid butler-img">
					</div>
				</div>

			</div>

			<div class="sub-block-holder">
				
				<div class="shadow-holder">
					<div class="shadow-ninja"></div>
				</div>
				<div class="sub-block-bg first">
					<div class="one-third column sub-block">
						<div class="landing-title">Tache Training</div>
						
						<img src="<?php echo $this->getSkinUrl('images/arush/movember/training.png'); ?>" alt="Moustache weight training" class="scale-with-grid explain-img">

						<div class="explain">Your butler will create a personalized daily fitness regime for your follicles. Moustache weights, cheek crunches, lip curls and chin-ups will all be utilized to prepare your face for greatness.</div>
					</div>
				</div>
				
				<div class="sub-block-bg">
					<div class="one-third column sub-block">
						<div class="landing-title">Mo Massages</div>

						<img src="<?php echo $this->getSkinUrl('images/arush/movember/oils.png'); ?>" alt="Moustache oils" class="scale-with-grid explain-img">

						<div class="explain">A combination of oils, unguents and embrocations will be regularly applied to your upper lip to soothe, stimulate and support the growth of your heroic Handlebar, feisty Fu Manchu or dangerous Dali.</div>
					</div>
				</div>

				<div class="sub-block-bg">
					<div class="one-third column sub-block">
						<div class="landing-title">Whisker Warbling</div>

						<img src="<?php echo $this->getSkinUrl('images/arush/movember/singing.png'); ?>" alt="Moustache singing" class="scale-with-grid explain-img">

						<div class="explain">Like plants, moustaches grow when serenaded to. So what could be better than a regular burst of Mo’ Better Blues from your butler in the morning to get that that face foliage thriving.</div>
					</div>
				</div>

			</div>

			

		</div>

		
	</div>



</div>

<div class="quotes container clearfix">

		<div class="quote-box one-third column">
		<img src="<?php echo $this->getSkinUrl('images/arush/movember/magnum.jpg'); ?>" class="scale-with-grid quote-img" alt="Magnum PI"/>
		<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
		<span class="quote left">A moustache is like steroids for your face. It makes you look strong.</span>
		<div class="quote-triangle"></div>
		<span class="author">Magnum PI</span>
		<span class="caption-small">Man since 1980</span></div>
		
		<div class="quote-box one-third column">
		<img src="<?php echo $this->getSkinUrl('images/arush/movember/borat.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
		<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
		<span class="quote middle">Old Kazakh saying. Man with much power have much moustache and man with much moustache have much power. In the chram. High five.</span>
		<div class="quote-triangle"></div>
		<span class="author">Borat</span>
		<span class="caption-small">Man since 1999</span></div>
		
		<div class="quote-box one-third column last">
		<img src="<?php echo $this->getSkinUrl('images/arush/movember/neo.jpg'); ?>" class="scale-with-grid quote-img" alt="Neo"/>
		<div class="apostrophe"><span>‘</span><span class="apostrophe2">‘</span></div>
		<span class="quote right">There is no moustache.</span>
		<div class="quote-triangle"></div>
		<span class="author">Neo</span>
		<span class="caption-small">Man since 1999</span></div>
		
	</div>