<div class="container">
	<div class="top-block">
		

		<div class="content">

			<div class="big-tash-holder">

				<!-- <img src="<?php // echo $this->getSkinUrl('images/arush/movember/big-tash.png'); ?>" alt="" class="scale-with-grid big-tash"> -->
				<div class="big-tash"></div>
			</div>

			<div class="text-overlay clearfix">
				<div class="title">
					<span>Your personal moustache concierge</span>
					<div class="subtitle">
						<span>A 24/7 moustache concierge for the month of Movember</span>
					</div>
				</div>
				<div class="ten columns">
					<div class="mo-price-box">
						<div class="price-header">
							<span>a one time only price of</span>
						</div>
						<div class="price-details">
							<div class="big-price">
								<span>£100,000</span>
							</div>
							<div class="price-subtitles">
								<span class="blue">30 day financing option available</span><br/><br/>
								<span>UN-approved human shipping container included</span>
							</div>

						</div>
						<div class="buy-container">
							<button href="https://brandid.recurly.com/subscribe/moustache-concierge" class="convert buy">BUY NOW</button>
						</div>

					</div>
				</div>
				<div class="six columns">
					<div class="butler-holder">
						<img src="<?php echo $this->getSkinUrl('images/arush/movember/butler.gif'); ?>" alt="butler" class="scale-with-grid butler-img">
					</div>
				</div>
			</div>

		</div>
		
	</div>

</div>
