<?php
$helper = Mage::helper('popup');
$currentUrl = str_replace(Mage::getBaseUrl(), '/', $this->helper('core/url')->getCurrentUrl());
if (trim($currentUrl, '\/') == trim($helper->getTriggerUrl(), '\/') && (trim($helper->getTriggerUrl(), '\/') != '') || $helper->getTriggerUrl() == '*'): ?>
<script type="text/javascript">
vdh.trigger = '<?php echo $helper->getTriggerUrl(); ?>';
vdh.urls = new Array();
<?php $i=0;foreach($helper->getUrls() as $url):?>
vdh.urls[<?php echo $i; $i++ ?>] = { url: '<?php echo $url; ?>', loaded: false };
<?php endforeach;?>
<?php if (Mage::getModel('core/cookie')->set('suppress_popup', true)): ?>
	vdh.popup(true);
<?php else: ?>
	vdh.popup(false);
<?php endif; ?>
</script>
<?php endif ?>