<?php

?>

<div class="header-container">
    <div class="header">
		<div class="header-panel">
			<!-- REMOVING SEARCH -->
			<?php //echo $this->getChildHtml('topSearch') ?>	
			<div class="checkout-link"><?php echo $this->getChildHtml('checkoutLinks') ?></div>	
			<?php echo $this->getChildHtml('topCart') ?>
			<div class="my-account-links"><?php echo $this->getChildHtml('accountLinks') ?></div>
			  <?php if (Mage::getSingleton('customer/session')->isLoggedIn()):?> 
                <?php echo $this->getChildHtml('topLinks') ?>
                    <?php /*WDCA CODE BEGIN*/ ?>
                    <?php echo $this->getChildHtml('rewardsHeader') ?>
                    <?php /*WDCA CODE END*/ ?>
                    
                    <div id="nav-invite"><a href="/index.php/rewardsref/customer/index/"></a></div>
                    <div class="tooltip">
                    	<div class="nav-invite">
                        <p>Invite a friend</p>
                        <form action="<?php echo $this-> getBaseUrl(); ?>rewardsref/customer/invites/" method="post" id="form-validates">
                        <input type="hidden" value="Il1NwrpfsCuSmp03" name="form_key">
                         <textarea type="hidden" name="message" style="display: none;" >I'm a Member of evogue, an invitation-only shopping club for everything luxury - at private sale prices. New Collections go live a few times each month - but are available only for a short time. Sign up now with this invitation!</textarea>
                        <input type="text" name="contacts"  id="recipient_list" value="Invitee's email address" onFocus=this.value="">
                        <button type="submit">SEND</button>
                        </form>
                        <img src="<?php echo $this->getSkinUrl();?>images/points.jpg"/ width="44" height="41">
                        <span>Earn &pound;15 (1500 points) for each referral</span>
                        </div>
                    </div>
					<script>
                    jQuery(document).ready(function() {
                        jQuery("#nav-invite").tooltip({
                            offset: [21, 0],
							position: 'bottom center',
							relative: true,
                            effect: 'slide'
                            })
                        ;});
                    </script>
              <?php endif?>
		</div>
        
               
		<?php echo $this->getChildHtml('topMenu') ?>
      <?php /*?><?php if (Mage::getSingleton('customer/session')->isLoggedIn()):?> 
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('content-menu')->toHtml() ?>
      <?php else:?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('content-menu-2')->toHtml() ?>
      <?php endif?><?php */?>
		<?php echo $this->getChildHtml('topContainer'); ?>
		<div class="branding absolutetop">
			<img id="logo-back" class="logo-back" src="<?php echo $this->getSkinUrl('images/logo-back.png'); ?>" alt="logo" title="logo"/>
        	<?php if ($this->getIsHomePage()):?>

	            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img class="logo-container" id="logo-container" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
	            <?php else:?>
	            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img class="logo-container" id="logo-container" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
		        <?php endif?>
        </div>	
    </div>
    
    
</div>

