<?php echo $this->getChildHtml('landing_header'); ?>

<div class="sixteen columns title-block first">
	<div class="title-block-inner clearfix">
		<div class="title-block-container clearfix">		
			<div class="title">
				<span class="first">Press pass.</span><br/>
				<span class="second">Access all areas.</span>
			</div>
			
		</div>
	</div>
</div>
<div class="container">

	<div class="sixteen columns commitment-caption">
		<div class="commitment-caption">
			<span class="caption">Here you find our latest announcements, high resolution images and other media resources. 
			If you have any press or speaker enquiries, please get in touch with us:</span>
		</div>
	</div>
	<span class="vision-title-text">Contact Details</span>
	<div class="row">
		<br/>
	</div>
	<div class="row">
		
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/press/gemsquare.jpg" width="150" height="150" alt="Team Photo of Gem Griff"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Gem Griff
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">All Press Inquiries</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=gemgriff" class="twitter-mention-button" data-related="brandid">Tweet to @GemGriff</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
				<br/><a href="mailto:philip@andmeanwhile.com">gemma@thecrowdandi.com</a>
			</div>
			
		</div>

		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/ankushsquare.jpg" width="150" height="150" alt="Team Photo of Ankush Sehgal"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>" alt="Team Photo of Ankush Sehgal"/>
				</div>
			</div>
			<span class="vision-title-text">
				Ankush Sehgal
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Co-founder / CEO / Buying / Sales</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=4nkush" class="twitter-mention-button" data-related="brandid">Tweet to @4nkush</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
				<br/><a href="mailto:as@getbrandid.com">as@getbrandid.com</a>
			</div>
		</div>
		
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/arushsquare.jpg" alt="Team Photo of Arush Sehgal"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>" alt="Team Photo of Arush Sehgal"/>
				</div>
			</div>
			<span class="vision-title-text">
				Arush Sehgal
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Co-founder / CTO / Design / Engineering </span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=arush" class="twitter-mention-button" data-related="brandid">Tweet to @arush</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
				<br/><a href="mailto:arush@getbrandid.com">arush@getbrandid.com</a>
			</div>
		</div>



	</div>
		
	<div class="row">
		<br/><br/>
	</div>
	<span class="vision-title-text">Press</span>
	<div class="row">
		<br/><br/>
	</div>
	<img class="four columns" src="<?php echo $this->getSkinUrl('images/arush/news.jpg');?>" alt="press releases"/>
	<div id="st-accordion" class="st-accordion twelve columns">
	    <ul>

	    	
	    	<li>
	            <a href="#" class="opener">
	                [StrategyEye] - Hot Company Profile: Men's Ecommerce Firm BRANDiD<br/>
	                <span class="st-arrow">Open or Close</span>
	                <div class="article-date">by Sarah Gill, London, 30th October 2012</div>

	            </a>
	            <div class="st-content">
	                
	                Boxers looking a bit threadbare? Look no further. For men who hate shopping, e-commerce firm BRANDiD has built the ultimate sartorial wingman. Users enter style preferences into its ‘Masculine Algorithmic Learning Engine' (M.A.L.E.) and pay either a one-off, quarterly or bi-annual fee for tailored shopping delivered to their front door. If the firm gets it wrong, it simply collects the goods and the user doesn't pay a thing.
					<br/><br/>
					Full article <a href="http://www.strategyeyedigitalmedia.com/article/2012/10/30/hot_company_profile_mens_e-commerce_firm_brandid/">here</a>.<br/><br/>
					<br/><br/>
	                

	                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="ldn_tech_exec,4nkush">Tweet to @brandid</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	            </div>
	        </li>

	        <li>
	            <a href="#" class="opener">
	                [StrategyEye] - Twitter refers 80% of our customers, claims fashion e-commerce startup<br/>
	                <span class="st-arrow">Open or Close</span>
	                <div class="article-date">by Sarah Gill, London, 16th October 2012</div>

	            </a>
	            <div class="st-content">
	                
	                Men's fashion startup BRANDiD claims that 80% of its customers are coming directly from Twitter, highlighting the growing role social media is playing in driving traffic to e-commerce services. Speaking to StrategyEye, CEO and co-founder Ankush Sehgal says that social media is "absolutely essential" in engaging with potential customers and pulling in traffic to its shopping service.
					<br/><br/>
					Full article <a href="http://digitalmedia.strategyeye.com/article/nsvXuidG3oA/2012/10/16/twitter_refers_80_of_e-commerce_startups_customers_says_ceo/">here</a>.<br/><br/>
					<br/><br/>
	                

	                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="ldn_tech_exec,4nkush">Tweet to @BRANDiD</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	            </div>
	        </li>

	        <li>
	            <a href="#" class="opener">
	                [TNW] - Meet the 18 startups rocking Seedcamp Week<br/>
	                <span class="st-arrow">Open or Close</span>
	                <div class="article-date">by Robin Wauters, London, 20th September 2012</div>

	            </a>
	            <div class="st-content">
	                
	                "This week is an important one for pan-European startup accelerator Seedcamp, as it’s holding its annual 4-day event that brings together all companies it has invested in throughout the year.
	                <br/><br/>
					The event will culminate in Demo Day, which is tomorrow, and will see Seedcamp showcase its portfolio startups to a wide variety of professional investors and press...."
					<br/><br/>
					Full article <a href="http://thenextweb.com/eu/2012/09/20/meet-18-startups-rocking-seedcamp-week/">here</a>.<br/><br/>
					You can read a detailed diary post of each day of Seedcamp Week on BRANDiD's <a href="http://founders.getbrandid.com/">Founders' Blog</a>, where they are giving the inside track on what it’s like to be a Seedcamp company. From the frontline.<br/><br/>
	                

	                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="ldn_tech_exec,4nkush">Tweet to @BRANDiD</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	            </div>
	        </li>

	        <li>
	            <a href="#" class="opener">
	                BRANDiD secures investment from Seedcamp<br/>
	                <span class="st-arrow">Open or Close</span>
	                <div class="article-date">London, 16th August 2012.</div>

	            </a>
	            <div class="st-content">
	                
	                We are delighted to announce that we are now part of the Seedcamp family. <a href="http://www.seedcamp.com/">Seedcamp</a> is Europe's hottest micro-seed investment fund for Europe's hottest startups.
					<br/><br/>
					Being part of Seedcamp means that BRANDiD has the perfect backing to really kick things off. We can continue on our mission to create the ultimate online destination, built from the pixel up – for men. 
					<br/><br/>
					Forget girly editorial about this season’s ‘looks’; fashionista nonsense aimed at our girlfriends and hastily edited women’s sites with the pinks turned blue.
					<br/><br/>It’s time to take the power back. It’s time to Shop Like A Man.
					<br/><br/>
					You can keep up to speed on the founders adventures throughout the year on their newly launched <a href="http://founders.getbrandid.com/">Founders' Blog</a>, where they’ll be giving the inside track on what it’s like to be a Seedcamp company. From the frontline.<br/><br/>
	                Read what Seedcamp have to say <a href="http://www.seedcamp.com/2012/08/four-new-companies-join-the-seedcamp-family.html">here</a>.<br/><br/>

	                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="ldn_tech_exec,4nkush">Tweet to @BRANDiD</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	            </div>
	        </li>

	        <li>
	            <a href="#" class="opener">
	                BRANDiD selected as a Seedcamp London Finalist<br/>
	                <span class="st-arrow">Open or Close</span>
	                <div class="article-date">London, 3rd August 2012.</div>

	            </a>
	            <div class="st-content">
	                
	                The sun has finally made an appearance just in time for the Olympics, which kicked off fabulously last week. We’re keeping the excitement going with Seedcamp London taking place on the 7th August.
					<br/><br/>
					London being home to our most prestigious network, birthplace of Seedcamp as well as a powerful tech hub resulted in the highest number of applications we’ve ever received. Quality was at an all time high so it was no easy quest filtering the talent down to the final selected teams.
	                <br/><br/>
	                Read more <a href="http://www.seedcamp.com/2012/08/introducing-seedcamp-london-7-august-finalists.html#disqus_thread">here</a>.<br/><br/>

	                <a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="ldn_tech_exec,4nkush">Tweet to @BRANDiD</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	            </div>
	        </li>

	    </ul>

	</div>
	<!-- <img class="four columns" src="<?php // echo $this->getSkinUrl('images/arush/seedcamp.png');?>" alt="press releases"/>
	<div id="st-accordion" class="st-accordion twelve columns">
	    <ul>
	        
	    </ul>

	</div> -->
	<div class="row">
		<br/><br/>
	</div>

	<div class="row">
		<br/><br/>
	</div>
	<span class="vision-title-text">Founders' Blog</span>

	<div class="sixteen columns commitment-caption">
		<div class="commitment-caption">
			<span class="caption">Read what the founders are up to, straight from the horse's mouth: <a href="http://founders.getbrandid.com/">founders.getbrandid.com</a>.</span>
		</div>
	</div>
	<div class="row">
		<br/><br/>
	</div>
	
</div>





	<div class="grey-tilt-holder vision-block">
		<div class="grey container">
			<div class="row">
				<br/><br/>
			</div>
			<span class="vision-title-text">Logo</span>
			<div class="row">
				<br/><br/>
			</div>
			<div class="one-third column logo-box">
				<a href="http://brandid.s3.amazonaws.com/brandid-square-big.png"><img class="scale-with-grid" src="http://brandid.s3.amazonaws.com/brandid-square-big.png" alt="large square logo"/></a>
			</div>
			<div class="two-thirds column logo-box">
				<div class="what-is box">
					<span class="logo-caption">
							These assets are hosted on highly available, fast and globally distributed servers, so it's always best to use the links provided:<br/><br/>
						</span>
					
					<span class="vision-sub-title">PNG</span><br/>
					<span class="logo-caption small">
							You can copy and paste this image link into your site:<br/><br/>
						</span>
						
							<textarea class="logo-field" type="textarea" name="large-logo" readonly="readonly"><a href="http://www.getbrandid.com/"><img src="http://brandid.s3.amazonaws.com/brandid-square-big.png" alt="BRANDiD - Shop. Like a Man."/></a></textarea>
							<a href="http://brandid.s3.amazonaws.com/brandid-square-big.png">Download Large Logo (7kb) PNG Format</a><br/><br/><br/>
					<span class="vision-sub-title">Vector</span><br/>
					
					<span class="logo-caption small">
							Use this logo for print media.<br/><br/>
						</span>
								<a href="http://cl.ly/code/1Z34231z1B3U">Download Vector Logo (624kb) EPS Format</a><br/><br/>

				</div>

			</div>
			<div class="row">
				<br/><br/>
			</div>
			<div class="row">
				<br/><br/>
			</div>
			<span class="vision-title-text">Hi-Res Images</span>
			<div class="row">
				<br/><br/>
			</div>
			<div class="row">
				<div class="one-third column">
					<span class="image-title-text">
						Homepage Screenshot
					</span>
					<br/><br/>
					<a href="http://brandid.s3.amazonaws.com/press/homepage.png"><img class="scale-with-grid founders" src="http://brandid.s3.amazonaws.com/press/homepage-thumb.png" alt="BRANDiD Co-founders"/><a/>
				</div>
				<div class="one-third column">
					<span class="image-title-text">
						Packed by a Man&trade;
					</span>
					<br/><br/>

					<a href="http://brandid.s3.amazonaws.com/press/package%202.jpg"><img class="scale-with-grid" src="http://brandid.s3.amazonaws.com/press/package-2-thumb.jpg" alt="BRANDiD package"/></a>
				</div>
				<div class="one-third column">
					<span class="image-title-text">
						Product Page Screenshot
					</span>
					<br/><br/>
					<a href="http://brandid.s3.amazonaws.com/press/product-page-full.png"><img class="scale-with-grid" src="http://brandid.s3.amazonaws.com/press/product-thumb.png" alt="BRANDiD Product Page Screenshot"/><a/>
				</div>
			</div>
			<div class="row">
				<div class="one-third column">
					<span class="image-title-text">
						Co-founders
					</span>
					<br/><br/>
					<a href="http://brandid.s3.amazonaws.com/press/BRANDiD-founders-1.jpg"><img class="scale-with-grid founders" src="http://brandid.s3.amazonaws.com/press/BRANDiD-founders-1-thumb.jpg" alt="BRANDiD Co-founders"/><a/>
				</div>
			</div>
			
			<div class="row">
				<br/><br/>
			</div>
			<div class="row">
				<br/><br/>
			</div>

		</div>
		<div class="row">
				<br/><br/>
			</div>
			<div class="row">
				<br/><br/>
			</div>
	</div>


<script type="text/javascript">
	jQuery(function() {
			
				jQuery('#st-accordion').accordion({
					oneOpenedItem	: true
				});
				
            });
</script>
