<div class="getgifted">

	<?php echo $this->getChildHtml('landing_header'); ?>

		
		<div id="title-block" class="title-block">
			<div class="title-block-inner clearfix">
				<div class="title-block-container container clearfix">
					<div class="im-man-title">
						<div class="sixteen columns">
							<span class="first">They say the way to a man's heart</span><br/>
							<span class="first">Is through his stomach.</span><br/><br/>
							<span class="second">It's not. It's through his pants.</span>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	<div class="keep-calm-signup-container">
		
		
		<div class="commitment container">
			<div class="gift-landing clearfix">
				<div class="gift-blurb eight columns">
					<div class="blurb-container clearfix">
						<span class="blurb-text">
							Bored of buying the same old tat for your man?
							Then why not buy him something he needs? Something that you’ll benefit from too?
							Something like a sexy pair of undies.<br/><br/>
							
							Granted, not all men will look like Beckham in his boxers, but smart, clean, hole-free undies might get your fella half way there.<br/><br/>
							
							So, how serious are you about this guy?  Whether it’s a short-term fling or a long-term thing - girlfriend, you’ve got options.
						</span>
						<div class="super-convert">
							<a id="gift-landing-page-convert" href="/male" class="convert">Buy Your Man Some Gear!</a>
						</div>
					</div>
					
				</div>
				<div class="gift-image eight columns">
					<img class="scale-with-grid" src="<?php echo $this->getSkinUrl(); ?>images/gift/parcel.png" alt="BRANDiD Subscription Gift Box" title="BRANDiD Subscription Gift Box"/>
				</div>
			</div>
			
		</div>
		
	</div>


	<div class="final-share section">
		<div class="vision-title">
			<span class="vision-title-text">Will your girlfriends like this?</span>
		</div>
		<div class="box">
			Help spread the word and maybe, just maybe, you'll never have to see another pair of grey whites again.
		</div>
		
		<div class="share-buttons clearfix">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true"></div>
				</div>
				
				<div class="share-but twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Ladies, join the campaign to clothe our sartorially challenged men #BRANDiD" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
				
				<!-- <div class="share-but gplus">
					<g:plusone size="medium" href="https://www.getbrandid.com/"></g:plusone>
				</div> -->
				<div class="share-but pinterest">
					<a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.getbrandid.com%2Fkeep%2Fcalm%2Fgetgifted&media=http%3A%2F%2Fbrandid.macbook.pro%2Fskin%2Ffrontend%2Fdefault%2Fbrandid%2Fimages%2Fgift%2Fparcel.png&description=Bored%20of%20buying%20the%20same%20old%20tat%20for%20your%20man%3F%20Then%20why%20not%20buy%20him%20something%20he%20needs%3F%20Something%20that%20you%E2%80%99ll%20benefit%20from%20too%3F%20Something%20like%20a%20sexy%20pair%20of%20undies.%0A%0AGranted%2C%20not%20all%20men%20will%20look%20like%20Beckham%20in%20his%20boxers%2C%20but%20smart%2C%20clean%2C%20hole-free%20undies%20might%20get%20your%20fella%20half%20way%20there.%0A%0ASo%2C%20how%20serious%20are%20you%20about%20this%20guy%3F%20Whether%20it%E2%80%99s%20a%20short-term%20fling%20or%20a%20long-term%20thing%20-%20girlfriend%2C%20you%E2%80%99ve%20got%20options." class="pin-it-button" count-layout="horizontal"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
				</div>
		</div>
	</div>
</div> <!-- end getgifted -->
<!-- pinterest script -->
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>

<script type="text/javascript">

	var $j = jQuery.noConflict();
	var w;
	var w_height;
	var image_bg_pause = 1;
		
	$j(function() {
		init();
		
				
		$j(window).scroll(function() {
			w = $j(this).scrollTop();
			var howTop = $j("#how").offset().top;
			
			if(w > $j("#how").data("scrolls")[0] && w < $j("#how").data("scrolls")[1]) {
	      	      
		      window.meeting_rel = w - ($j("#how").data("scrolls")[1] - 750);
		      
		      window.meeting_ratio = (Math.round((window.meeting_rel / ($j("#how").data("scrolls")[2] )) * 100 ) / 40);
			
/* 			console.log("w: %d",w); */
/* 			console.log("del: %d / scroll2: %d = ratio: %d",window.meeting_rel, $j("#how").data("scrolls")[2], window.meeting_ratio);    */

		      $j(".moveable").each(function(index) {
		      				      		
			      	var resetMargin = $j(this).data("original")[0];
			      	var fullMargin = $j(this).data("original")[1];
			      					   	if($j(this).data("moved")=="false") {
			          if(window.meeting_ratio > index) {
			          		$j(this).stop().animate({
			          			marginLeft: fullMargin
			          		},200,function() {
			          				$j(this).data("moved","true");
			          				$j("#third-how").animate({
			          					backgroundColor: "#d2002b"
			          				  }, 500 );
							        new Effect.Morph('sorted-cal', {
							            style: 'background-position:-2425px 0px',
							            duration: 10
							        });

							    });
									
			          	}
			        }
			        else {
						if(window.meeting_ratio < index) {
			          		$j(this).stop().animate({
			          			marginLeft: resetMargin
			          		},200,function() {
			          				$j(this).data("moved","false");
			          				$j("#third-how").animate({
			          					backgroundColor: "#fff"
			          				  }, 200 );
			          				new Effect.Morph('sorted-cal', {
							            style: 'background-position: 0px 0px',
							            duration: .2
							        });
			          			});
			          	}
			        }
			
				});
			}	

		
		});
	});
	
	function set_section_scrolls() {
	  w_height = $j(window).height();
	  $j("#how").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top /* + $j(this).height() */;
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#vision").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top + $j(this).height();
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#title-block").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top;
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j(".moveable").each(function(){
		var marginBig;
		marginBig = parseInt($j(this).css('marginLeft').replace("px", ""),10);
	    marginBig += 20;
	    marginBig += "px";
	    
	    var original = new Array()
	    original[0] = $j(this).css('marginLeft');
	    original[1] = marginBig;
	    $j(this).data("original",original);
	    $j(this).data("moved","false");
	  });
	  
	}
	
	function init() {
	  set_section_scrolls();
	  $j(window).resize(set_section_scrolls);
	  	
	  $j(".hood-element").each(function(){
	    $j(this).hide();
	    $j(this).data("visible","false");
	  }); 
	}
	
	
	function clearDefault(el) {
  		if (el.defaultValue==el.value) el.value = ""
	}

	

	$j(document).ready(function () {
		$j.localScroll();		
		

});

</script>