<div class="keep-calm-signup-container">
	
	
	<div class="share-header clearfix">
		<div class="share-header-container section">
	
			<div class="tie-icon">
			</div>

			
			<div class="share-buttons">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="200" data-show-faces="true"></div>
				</div>
				
				<div class="share-but">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Men, rally the troops. It's time to take the power back. #shoplikeaman" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
				
				<div class="share-but">
					<g:plusone size="medium" href="http://www.getbrandid.com"></g:plusone>
				</div>
	
			</div>
			
			
			
			<div class="login-signup">
				
				<div class="login-signup-but"><a href="/customer/account/login">Login</a>
				</div>
				<div class="login-signup-but"><a href="#signmeupnow">Sign Up</a>
				</div>
			</div>
	
		</div>
	</div>
	
	<div class="big-fuckoff section">
		<div class="logo section">
		</div>
		<div class="shadow section">
		</div>
		<div class="title section">
			<span class="first">I'm a man.</span><br/>
			<span class="second">I don't read instructions.</span>
		</div>
		<div class="signmeup-now chevron" id="signmeupnow">
			<div class="first-line block">Sign me up</div>
			<div class="second-line block">Now!</div>
		</div>
		
	</div>
	
	<div class="title-block">
		<div class="title-block-inner clearfix">
			<div class="title-block-container section">		
				<div class="reg-form">
					<form action="/customer/account/create" method="get">
					  <input type="text" name="email" value="Register with your email address…" onFocus="clearDefault(this)"/>
					  <button type="submit">Register</button>
					</form>
				</div>
				
				<div id="oa_social_login_container"></div>
					
					<script type="text/javascript">
						 oneall.api.plugins.social_login.build("oa_social_login_container", {
						  'providers' :  ['facebook', 'google', 'twitter', 'yahoo'],
						  'callback_uri': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>arush-oneall/rpx/token_url/',
						  'css_theme_uri': 'https://cdn.oneall.com/css/api/socialize/themes/connect_vertical.css'
						 });
					</script>
			</div>
		</div>
	</div>
	<div class="commitment section">
		<a class="invisibut" href="#commitment">
			<div class="chevron down black">
				<div class="first-line block">Register? Whoa there buddy!</div>
				<div id="commitment" class="second-line block">We just met</div>
				<div class="chevron-triangle"></div>
			</div>
		</a>
		<div class="title section">
			<span class="first">I'm a man.</span><br/>
			<span class="second">I have commitment issues.</span>
		</div>
		<div class="commitment-caption section">
			<span class="caption">That's OK. Let us explain exactly what you're getting into.<br/>If only girls were this up front...</span>
		</div>
	</div>	

	<div class="grey-tilt-holder">
		<div class="grey-tilt clearfix">
				<div class="grey-tilt-container clearfix">
					<div id="vision" class="vision section clearfix">
						<div class="vision-title">
							<span class="vision-title-text">Our Vision</span>
						</div>
						<div class="mandate box">
							<span class="vision-sub-title">Our <span class="red-text">Man</span>date</span>
							<div class="mandate-one-line block">
								We are reinventing shopping for men because the industry has forgotten about us.
								Why should we have to sift through poncy female-focused fashionista content just to get our clothes delivered? It's time to <a href="http://www.youtube.com/watch?v=aaas7GFbLHk&feature=related" target="_blank">take the power back.</a>
								<!-- if you're reading this, watch this one from '92! http://www.youtube.com/watch?v=cPHEgpWhkuQ&feature=related -->
							</div>
						</div>
						<div class="what-is box">
							<span class="vision-sub-title">What is BRANDiD?</span>
							<div class="what-is-oneliner">
								BRANDiD is a subscription service for designer basics… and a whole lot more. We love quality gear, big discounts and good humour. We hate fashionistas.
							</div>
						</div>
						
					</div>
				
					<div class="how section">
						<div class="vision-title">
							<span class="vision-title-text">How does it work?</span>
						</div>
						
						
						<div class="how-to-process">
							<div class="how-to-box">
								<div class="select-title">
									<span class="select-title-text">Select</span>
								</div>
								<div class="select-circle circle">
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Select a monthly plan</span>
								</div>
								
								<div class="select-triangle vert-chevron">
									<div class="select-triangle white">
									</div>
									<div class="select-triangle grey">
									</div>
								</div>
							</div> <!-- end how to box -->
							
							<div class="how-to-box">
								<div class="select-title">
									<span class="select-title-text">Subscribe</span>
								</div>
								<div class="subscribe-circle circle">
									<div class="sub-detail detail-1">minimum of</div>
									<div class="sub-detail detail-2">30% off</div>
									<div class="sub-detail detail-3">the high street price</div>
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Automatic monthly billing</span>
								</div>
								
								<div class="subscribe-triangle vert-chevron">
									<div class="subscribe-triangle white">
									</div>
									<div class="subscribe-triangle grey">
									</div>
								</div>
							</div> <!-- end how to box -->
				
							<div class="how-to-box last">
								<div class="select-title">
									<span class="select-title-text">Sorted</span>
								</div>
								<div class="sorted-circle circle">
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Automatic monthly delivery</span>
								</div>
								
							</div> <!-- end how to box -->
							
						</div> <!-- end how to process -->
						
					</div> <!-- end how section -->
				</div> <!-- end grey tilt container -->
		</div> <!-- end grey tilt -->
	</div>

	<div class="chev-group-wrap section">
		<div class="chevron-group">
			<a class="invisibutred" href="#signmeupnow">
				<div class="chevron-triangle up red section"></div>
				<div class="chevron up">
					<div class="first-line block red">I've seen enough</div>
					<div class="second-line block red">Sign me up!</div>
				</div>	
			</a>		
			<a class="invisibut" href="#underthehood">
				<div class="chevron down black">
					<div class="first-line block">Still not</div>
					<div class="second-line block">Convinced?</div>
					<div class="chevron-triangle"></div>
				</div>
			</a>
		</div>
	</div>
	
	<div class="quotes section clearfix">
		
		<div class="quote-box">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote">@getbrandid is the kind of place Tony Montana would shop at</span>
		<div class="quote-triangle"></div>
		<span class="author">Gabbi Cahane</span>
		<span class="caption-small">Man since 1972</span></div>
		
		<div class="quote-box">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote">@getbrandid is the kind of place Tony Montana would shop at</span>
		<div class="quote-triangle"></div>
		<span class="author">Gabbi Cahane</span> <span class="caption-small">Man since 1972</span></div>
		
		<div class="quote-box last">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote">@getbrandid is the kind of place Tony Montana would shop at</span>
		<div class="quote-triangle"></div>
		<span class="author">Gabbi Cahane</span> <span class="caption-small">Man since 1972</span></div>
		
	</div>
	<div id="underthehood"></div>
	<div class="title section">
		<span class="first">I'm a man.</span><br/>
		<span class="second">Show me what's under the hood.</span>
	</div>
	
	<div class="price-compare section">
		
		<?php
		     echo  $this->getLayout()->createBlock('cms/block')->setBlockId('signup-products')->toHtml() ;
		?>

	</div>
	<div class="grey-tilt-holder">
		<div class="grey-tilt right-tilt clearfix">
			<div id="mags" class="hood section clearfix">
				
			<?php
			     echo  $this->getLayout()->createBlock('cms/block')->setBlockId('under-the-hood')->toHtml() ;
			?>
				
			</div>
	
		</div>
	</div>
	
	<div class="chev-group-wrap section">
		<div class="chevron-group final">
			<a class="invisibutred" href="#signmeupnow">
				<div class="chevron-triangle up red"></div>
				<div class="chevron up red">
					<div class="first-line block red">keep calm and</div>
					<div class="second-line block red">Sign me up!</div>
				</div>	
			</a>
			<a class="invisibut" href="#notaman">
				<div class="chevron down black">
					<div class="first-line block">Sounds cool, but it's just</div>
					<div class="second-line block">Not for me.</div>
					<div class="chevron-triangle"></div>
				</div>
			</a>
		</div>
	</div>
	
	<div id="notaman" class="final title section">
		<span class="first">I'm not a man.</span><br/>
		<span class="second red">Get me the heck out of here.</span>
	</div>
	<div class="final-share section">
		<div class="vision-title">
			<span class="vision-title-text">Know someone who will like this?</span>
		</div>
		<div class="box">
			We're a small company with big ambitions, please help us spread the word.
		</div>
		
		<div class="share-buttons clearfix">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="true" data-layout="button_count" data-width="200" data-show-faces="true"></div>
				</div>
				
				<div class="share-but twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Men, rally the troops. It's time to take the power back. #shoplikeaman" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
				
				<div class="share-but gplus">
					<g:plusone size="medium" href="http://www.getbrandid.com"></g:plusone>
				</div>
		</div>
	</div>
</div>


<script type="text/javascript">

	var $j = jQuery.noConflict();
	var w;
	var w_height;
	var image_bg_pause = 1;
		
	$j(function() {
		init();
		$j(window).scroll(function() {
			w = $j(this).scrollTop();
			
			if(w > $j("#mags").data("scrolls")[0] && w < $j("#mags").data("scrolls")[1]) {
      
		      window.group_rel = w - ($j("#mags").data("scrolls")[0] + 600);
		      window.group_ratio = (Math.round((window.group_rel / ($j("#mags").data("scrolls")[2] - 500)) * 100) / 8);      
		      
		      $j(".hood-element").each(function(index) {
		        if($j(this).data("visible")=="false") {
		          if(window.group_ratio > index) $j(this).fadeIn(600,function() {$j(this).data("visible","true")});
		        }
		        else {
		          if(window.group_ratio < index) $j(this).fadeOut(600,function() {$j(this).data("visible","false")});
		        }
		
		      });
		      
		    }
		
		});
	});
	
	function set_section_scrolls() {
	  w_height = $j(window).height();
	  $j(".section").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top + $j(this).height();
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	}
	
	function init() {
	  //$j("#intro h2").lettering();
	
	  //$j("#golden_ratio .gr").hide().css("visibility","visible");
	  
	  set_section_scrolls();
	  $j(window).resize(set_section_scrolls);
	  
	  if(w > $j("#vision").data("scrolls")[0] && w < $j("#vision").data("scrolls")[1]) {
	      window.meeting_rel = w - ($j("#vision").data("scrolls")[0] + 250);
	      window.meeting_ratio = 1 - ((window.meeting_rel / ($j("#vision").data("scrolls")[2] * .7 )));
	      var triangle_top = -40 * window.meeting_ratio;
	      if( triangle_top > 0 ) triangle_top = 0;
	
	      $j(".vert-chevron").stop().animate({
	        margin-left: triangle_top
	      }, 200);
	
	    }
	
	  $j(".hood-element").each(function(){
	    $j(this).hide();
	    $j(this).data("visible","false");
	  });
	  	  
	  
	}

	
	
	function clearDefault(el) {
  		if (el.defaultValue==el.value) el.value = ""
	}


	
    
    	$j(document).ready(function () {
			$j.localScroll();
			$j('a.invisibut').hover(
				function() {
					$j(this).addClass('red');
					},
				function() {
					$j(this).removeClass('red');
				});				
			
			// $j("a.invisibut > .chevron").("border", "3px double red");

	});

</script>