<?php 

Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::getUrl("plans.html"));

?>


<div class="keep-calm-signup-container">
	
	
	<div class="share-header clearfix">
		<div class="share-header-container section">
	
			<div class="tie-icon">
			</div>

			
			<div class="share-buttons">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
				</div>
			
				<div class="share-but follow">
					<a href="https://twitter.com/getbrandid" class="twitter-follow-button" data-show-count="true" data-lang="en">Follow @getbrandid</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
				</div>
				
				<div class="share-but">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Dirty boxers never got anyone laid. Designer brands auto-delivered for MEN. get #BRANDiD" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
								
				<div class="share-but gp">
					<g:plusone size="medium" href="https://www.getbrandid.com"></g:plusone>
				</div>
	
			</div>
			
			
			
			<div class="login-signup">
					<div class="login-signup-but"><a href="/customer/account/login">Login</a>
					</div>
					<div class="login-signup-but but-right"><a href="#signmeupnow">Sign Up</a>
					</div>
			</div>
	
		</div>
	</div>
	
	<div class="big-fuckoff section">
		<div class="logo section">
		</div>
		<a class="gift invisibut" href="/keep/calm/getgifted">
			<div class="subscribe-circle circle gift">
				<div class="sub-detail detail-1">looking for a</div>
				<div class="sub-detail detail-2">GIFT?</div>
				<div class="sub-detail detail-3">click here</div>
			</div>
		</a>
		<div class="shadow section">
		</div>
		<div class="title section">
			<span class="first">I'm a man.</span><br/>
			<span class="second">I don't read instructions.</span>
		</div>
		
		<div class="signmeupnow-container section">
			<div class="signmeup-now chevron" id="signmeupnow">
				<a href="#signmeupnow">
					<div class="first-line block">Sign up to our beta</div>
					<div class="second-line block">Now!</div>
				</a>
			</div>
		</div>
		
	</div>
	
	<div id="title-block" class="title-block">
		<div class="title-block-inner clearfix">
			<div class="title-block-container section clearfix">		
				<div class="reg-form">
					<div class="product-sub-title">
						<span>No commitment or credit card required, just balls.</span>
					</div>
					<form action="/customer/account/create" method="get">
					  <input type="text" name="email" value="Register with your email address…" onFocus="clearDefault(this)"/>
					  <button type="submit">Register Free</button>
					</form>
				</div>
				
				<div id="oa_social_login_container"></div>
					
					<script type="text/javascript">
						 oneall.api.plugins.social_login.build("oa_social_login_container", {
						  'providers' :  ['facebook', 'google', 'twitter', 'yahoo'],
						  'callback_uri': '<?php echo $this->getUrl('arush-oneall/rpx/token_url', array('_forced_secure' => false)) ?>',
						  'css_theme_uri': 'https://cdn.oneall.com/css/api/socialize/themes/connect_vertical.css'
						 });
					</script>
			</div>
		</div>
	</div>
	<div class="commitment section">
		<a class="invisibut" href="#commitment">
			<div class="chevron down black">
				<div class="first-line block">Register? Whoa there buddy!</div>
				<div id="commitment" class="second-line block">We just met</div>
				<div class="chevron-triangle"></div>
			</div>
		</a>
		<div class="title section">
			<span class="first">I'm a man.</span><br/>
			<span class="second">I have commitment issues.</span>
		</div>
		<div class="commitment-caption section">
			<span class="caption">That's OK. Let us explain exactly what you're getting into.<br/>If only girls were this up front...</span>
		</div>
	</div>	
	
	<div class="grey-tilt-holder">
		<div class="grey-tilt clearfix">
				<div class="grey-tilt-container clearfix">
					<div class="vision section clearfix">
						<div class="vision-title">
							<span class="vision-title-text">#1 Plans</span>
						</div>
						<div class="what box plans">Because you've got more important things to do.<br/>
						Yes boys, everyone needs clean undies. Even you.
						Choose your essentials, we deliver monthly. Bosh.
						</div>
						<div class="plans-img">
						</div>
						
					</div>
					
					<div id="how" class="how section">
						<!--
							<div class="vision-title">
								<span class="vision-title-text">How does it work?</span>
							</div>
						-->
						
						
						<div class="how-to-process">
							<div class="how-to-box">
								<div class="select-title">
									<span class="select-title-text">Select</span>
								</div>
								<div class="select-circle circle">
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Select a monthly plan</span>
								</div>
								
								<div class="select-triangle vert-chevron">
									<div class="select-triangle white moveable">
									</div>
									<div class="select-triangle grey">
									</div>
								</div>
							</div> <!-- end how to box -->
							
							<div class="how-to-box">
								<div class="select-title">
									<span class="select-title-text">Subscribe</span>
								</div>
								<div class="subscribe-circle circle">
									<div class="sub-detail detail-1">minimum of</div>
									<div class="sub-detail detail-2">30% off</div>
									<div class="sub-detail detail-3">the high street price</div>
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Automatic monthly billing</span>
								</div>
								
								<div class="subscribe-triangle vert-chevron">
									<div class="subscribe-triangle white moveable">
									</div>
									<div class="subscribe-triangle grey">
									</div>
								</div>
							</div> <!-- end how to box -->
				
							<div id="third-how" class="how-to-box last">
								<div class="select-title">
									<span class="select-title-text">Sorted</span>
								</div>
								<div id="sorted-cal" class="sorted-circle circle">
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Automatic monthly delivery</span>
								</div>
								
							</div> <!-- end how to box -->
							
						</div> <!-- end how to process -->						
						
						
					</div> <!-- end how section -->
					
					<div class="vision section clearfix">
						<div class="vision-title">
							<span class="vision-title-text">#2 Boosters</span>
						</div>
						<div class="what box boosters">Because men shop to solve a problem.<br/>
						Delivered immediately in large quantities and with bulk discounts,
						Boosters ensure you're not in this situation again any time soon.<br/>
						If you're not the shopping type, choose Lucky Dip and we'll shop for you.
						</div>

						<div class="boosters-img first">
						</div>
						<div class="boosters-img second">
						</div>
						<div class="boosters-img third">
						</div>

						
					</div>
				</div> <!-- end grey tilt container -->
		</div> <!-- end grey tilt -->
	</div>
	
	<div class="quotes section clearfix">

		<div class="quote-box">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote left">BRANDiD makes the hairs on my hairs stand up.</span>
		<div class="quote-triangle"></div>
		<span class="author">Wolverine</span>
		<span class="caption-small">aka Logan of the X-Men</span>
		<span class="caption-small">Man since… nobody knows</span></div>
		
		<div class="quote-box">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote middle">I’d have shopped at BRANDiD if it had been around in my day.</span>
		<div class="quote-triangle"></div>
		<span class="author">Charlton Heston</span>
		<span class="caption-small">Actor of heroic roles</span>
		<span class="caption-small">Man since 1923</span></div>
		
		<div class="quote-box last">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote right">It's not for me.</span>
		<div class="quote-triangle"></div>
		<span class="author">Gok Wan</span>
		<span class="caption-small">Not sure why he's famous</span>
		<span class="caption-small">Around since 1974</span></div>
		
	</div>
	
	<div class="grey-tilt-holder">
		<div class="grey-tilt clearfix">
				<div class="grey-tilt-container clearfix">
					<div class="vision section clearfix">
						<div class="vision-title">
							<span class="vision-title-text">Our Vision</span>
						</div>
						<div class="mandate box">
							<span class="vision-sub-title">Our <span class="red-text">Man</span>date</span>
							<div class="mandate-one-line block">
								We are reinventing shopping for men because the industry has forgotten about us.
								Why should we have to sift through poncy female-focused fashionista content just to get our clothes delivered? It's time to <a href="https://www.youtube.com/watch?v=aaas7GFbLHk&feature=related" target="_blank">take the power back.</a>
								<!-- if you're reading this, watch this one from '92! http://www.youtube.com/watch?v=cPHEgpWhkuQ&feature=related -->
							</div>
						</div>
						<div class="what-is box">
							<span class="vision-sub-title">What is BRANDiD?</span>
							<div class="what-is-oneliner">
								BRANDiD is a subscription service for designer basics… and a whole lot more. We love quality gear, big discounts and good humour. We hate fashionistas.
							</div>
						</div>
						
					</div>
				</div> <!-- end grey tilt container -->
		</div> <!-- end grey tilt -->
	</div>
	
			

	<div id="chevron-plax" class="chev-group-wrap section convinced">
		<div class="chevron-group">
			<a class="invisibutred" href="#signmeupnow">
				<div class="chevron-triangle up red section"></div>
				<div class="chevron up">
					<div class="first-line block red">I've seen enough</div>
					<div class="second-line block red">Sign me up!</div>
				</div>	
			</a>		
			<a class="invisibut" href="#bigtop-title">
				<div class="chevron down black">
					<div class="first-line block">Still not</div>
					<div class="second-line block">Convinced?</div>
					<div class="chevron-triangle"></div>
				</div>
			</a>
		</div>
	</div>

		<div id="bigtop-title" class="title section">
			<span class="first">I'm a man.</span><br/>
			<span class="second">Show me what's under the hood.</span>
		</div>
	
	<div class="price-compare section">
		
		<?php
		     echo  $this->getLayout()->createBlock('cms/block')->setBlockId('signup-products')->toHtml() ;
		?>

	</div>
	<div class="grey-tilt-holder">
		<div class="grey-tilt right-tilt clearfix">
			<div id="mags" class="hood section clearfix">
				
			<?php
			     echo  $this->getLayout()->createBlock('cms/block')->setBlockId('under-the-hood')->toHtml() ;
			?>
				
			</div>
	
		</div>
	</div>
	
	<div class="chev-group-wrap section">
		<div class="chevron-group final">
			<a class="invisibutred" href="#signmeupnow">
				<div class="chevron-triangle up red"></div>
				<div class="chevron up red">
					<div class="first-line block red">keep calm and</div>
					<div class="second-line block red">Sign me up!</div>
				</div>	
			</a>
			<a class="invisibut" href="#notaman">
				<div class="chevron down black">
					<div class="first-line block">Sounds cool, but it's just</div>
					<div class="second-line block">Not for me.</div>
					<div class="chevron-triangle"></div>
				</div>
			</a>
		</div>
	</div>
	
	<div id="notaman" class="final title section">
		<span class="first">I'm not a man.</span><br/>
		<a href="http://www.barbie.com/"><span class="second red">Get me the heck out of here.</a></span>
	</div>
	<div class="final-share section">
		<div class="vision-title">
			<span class="vision-title-text">Know someone who will like this?</span>
		</div>
		<div class="box">
			We're a small team with big ambitions, please help us spread the word.
		</div>
		
		<div class="share-buttons clearfix">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
				</div>
				
				<div class="share-but twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Men, rally the troops. It's time to take the power back. #shoplikeaman" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
				
				<div class="share-but gplus">
					<g:plusone size="medium" href="https://www.getbrandid.com/"></g:plusone>
				</div>
		</div>
	</div>
</div>


<script type="text/javascript">

	var $j = jQuery.noConflict();
	var w;
	var w_height;
	var image_bg_pause = 1;
		
	$j(function() {
		init();
		
				
		$j(window).scroll(function() {
			w = $j(this).scrollTop();
			var howTop = $j("#how").offset().top;
			
			if(w > $j("#how").data("scrolls")[0] && w < $j("#how").data("scrolls")[1]) {
	      	      
		      window.meeting_rel = w - ($j("#how").data("scrolls")[1] - 750);
		      
		      window.meeting_ratio = (Math.round((window.meeting_rel / ($j("#how").data("scrolls")[2] )) * 100 ) / 40);
			
/* 			console.log("w: %d",w); */
/* 			console.log("del: %d / scroll2: %d = ratio: %d",window.meeting_rel, $j("#how").data("scrolls")[2], window.meeting_ratio);    */

		      $j(".moveable").each(function(index) {
		      				      		
			      	var resetMargin = $j(this).data("original")[0];
			      	var fullMargin = $j(this).data("original")[1];
			      					   	if($j(this).data("moved")=="false") {
			          if(window.meeting_ratio > index) {
			          		$j(this).stop().animate({
			          			marginLeft: fullMargin
			          		},200,function() {
			          				$j(this).data("moved","true");
			          				$j("#third-how").animate({
			          					backgroundColor: "#d2002b"
			          				  }, 500 );
							        new Effect.Morph('sorted-cal', {
							            style: 'background-position:-2425px 0px',
							            duration: 10
							        });

							    });
									
			          	}
			        }
			        else {
						if(window.meeting_ratio < index) {
			          		$j(this).stop().animate({
			          			marginLeft: resetMargin
			          		},200,function() {
			          				$j(this).data("moved","false");
			          				$j("#third-how").animate({
			          					backgroundColor: "#fff"
			          				  }, 200 );
			          				new Effect.Morph('sorted-cal', {
							            style: 'background-position: 0px 0px',
							            duration: .2
							        });
			          			});
			          	}
			        }
			
				});
			}	

			
			if(w > $j("#mags").data("scrolls")[0] && w < $j("#mags").data("scrolls")[1]) {
      
		      window.group_rel = w - ($j("#mags").data("scrolls")[0] + 650);
		      window.group_ratio = (Math.round((window.group_rel / ($j("#mags").data("scrolls")[2] - 650)) * 100) / 25);      
		    	

		    
   		      $j(".hood-element").each(function(index) {
		        if($j(this).data("visible")=="false") {
		          if(window.group_ratio > index) $j(this).fadeIn(600,
		          	function() {
		          		$j(this).data("visible","true");
								          		
		          		});
		        }
		        else {
		          if(window.group_ratio < index) $j(this).fadeOut(600,function() {$j(this).data("visible","false")});
		        }
		 
		      });
		      
		    }
		   	
		   	if(w > $j("#title-block").data("scrolls")[0]) {
				$j.plax.disable();      			
			}
			if(w < $j("#title-block").data("scrolls")[0]) {
				$j.plax.enable();      			
			}
		
		});
	});
	
	function set_section_scrolls() {
	  w_height = $j(window).height();
	  $j(".section").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top /* + $j(this).height() */;
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#vision").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top + $j(this).height();
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#title-block").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top;
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j(".moveable").each(function(){
		var marginBig;
		marginBig = parseInt($j(this).css('marginLeft').replace("px", ""),10);
	    marginBig += 30;
	    marginBig += "px";
	    
	    var original = new Array()
	    original[0] = $j(this).css('marginLeft');
	    original[1] = marginBig;
	    $j(this).data("original",original);
	    $j(this).data("moved","false");
	  });
	  
	}
	
	function init() {
	  set_section_scrolls();
	  $j(window).resize(set_section_scrolls);
	  	
	  $j(".hood-element").each(function(){
	    $j(this).hide();
	    $j(this).data("visible","false");
	  });
 
	  
	}

	$j('#signmeupnow').plaxify({"xRange":0,"yRange":30, invert:false});
	$j.plax.enable();
	
	
	function clearDefault(el) {
  		if (el.defaultValue==el.value) el.value = ""
	}

	

	$j(document).ready(function () {
		$j.localScroll();
		$j('a.invisibut').hover(
			function() {
				$j(this).addClass('red');
				},
			function() {
				$j(this).removeClass('red');
			});				
		

});

</script>