<?php echo $this->getChildHtml('landing_header'); ?>

<div class="sixteen columns title-block first">
	<div class="title-block-inner clearfix">
		<div class="title-block-container clearfix">		
			<div class="im-man-title">
				<span class="first">Keep calm.</span><br/>
				<span class="second">We're professionals.</span>
			</div>
			
		</div>
	</div>
</div>
<div class="container">

	<div class="sixteen columns commitment-caption">
		<div class="commitment-caption">
			<span class="caption">Our team is the perfect mix of tech startup, retail, fashion, branding and comms entrepreneurs.<br/>And we are deadly serious about solving clothing shopping for men. Forever.<br/><br/><a href="/keep/calm/accessallareas">Click here for our press page</a></span>
		</div>
	</div>

	<div class="row">
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/ankushsquare.jpg" width="150" height="150" alt="Team Photo of Ankush Sehgal"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>" alt="Team Photo of Ankush Sehgal"/>
				</div>
			</div>
			<span class="vision-title-text">
				Ankush Sehgal
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Co-founder / CEO / Buying / Sales</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=4nkush" class="twitter-mention-button" data-related="brandid">Tweet to @4nkush</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Ankush’s experience in retail spans eight years, and varies from working on the shop- floor to founding retail pop-up concept ‘I Love Brands’, in 2009. During which time he developed relationships and supply networks with some of the biggest brands including Armani, Dolce & Gabbana and Calvin Klein. Previously he worked in FX Sales at Deutsche Bank.
				</span>
			</div>
		</div>
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/arushsquare.jpg" alt="Team Photo of Arush Sehgal"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>" alt="Team Photo of Arush Sehgal"/>
				</div>
			</div>
			<span class="vision-title-text">
				Arush Sehgal
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Co-founder / CTO / Design / Engineering </span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=arush" class="twitter-mention-button" data-related="brandid">Tweet to @arush</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Arush is a consumer web tech evangelist, active open source contributor, designer, developer, project manager with a background in retail. An ex-Deloitte tech consultant, he has worked built systems for johnlewis.com, The Disney Store, Sony, Lloyds TSB Corporate Markets and Phonographic Performance Limited.
				</span>
			</div>
		</div>

		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/gabbisquare.jpg" alt="Team Photo of Gabbi Cahane"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Gabbi Cahane
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">MR Brand Activation</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=gabbicahane" class="twitter-mention-button" data-related="brandid">Tweet to @gabbicahane</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Gabbi founded his first marketing firm aged 23. His work for brands including DHL, Financial Times, Shell, Unilever, Warner Music, Umbro, Ladbrokes, Penguin Books, Novartis and Sony has covered almost every marketing and communications discipline in pretty much every sector and spanned most geographic regions.
				</span>
			</div>
		</div>

	</div>
	<div class="row">
		<br/><br/>
	</div>
	<div class="row">
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/philsquare.jpg" width="150" height="150" alt="Team Photo of Philip Sheldrake"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Philip Sheldrake
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">SOCIAL / DIGITAL / COMMUNITY / PR</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=sheldrake" class="twitter-mention-button" data-related="brandid">Tweet to @sheldrake</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Philip co-founded, built and sold an award-winning PR consultancy, was the CEO of Nochex, Europe’s first e- payment service, and co-founded OnOneMap, Europe’s first Google Maps mashup.
					He authored The Business of Influence, Wiley, April 2011, and the Digital Marketing chapter of The Marketing Century.
					He is a founding member of the CIPR’s social media panel and leads its policy group on campaign measurement and evaluation. He sits on the board of Intellect & 6UK.
				</span>
			</div>
		</div>

		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/monsquare.jpg" alt="Team Photo of Monica Durden"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Monica Durden
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Wing girl</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=monicarosed" class="twitter-mention-button" data-related="brandid">Tweet to @monicarosed</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Monica’s experience includes creative production and account management roles at agencies VCCP, Intro and Exposure; campaigns for Levi’s, O2, Agent Provocateur, TK Maxx and Converse; and projects for publishers including Hachette Filipacchi, Conde Nast and IPC. She managed the in-house creative team for MSHK producing global content, product and campaigns for their stable of brands including Ministry of Sound, Hed Kandi, Global Underground and Data Records.
				</span>
			</div>
		</div>

		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/simonsquare.jpg" alt="Team Photo of Simon Huhtala"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Simon Huhtala
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Professor of Post Production</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=huhtala" class="twitter-mention-button" data-related="brandid">Tweet to @huhtala</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Simon’s early career was spent in Milan collaborating with renowned directors such as Gabrielle Salvatores, Roman Polanski and Tarsem pioneering new visual technology and techniques in post production.
					As MD of boutique London facility Clear Post Production, he refocused the business, returned it to profitability and sold it to Prime Focus.
					At Prime Focus he was responsible for clients ranging from the BBC, VW, Head & Shoulders, 118 118, P&G and supervised one of Burberry’s most ambitious online campaigns ever.
				</span>
			</div>
		</div>
	</div>
	<div class="row">
		<br/>
	</div>
	<div class="row">
		<div class="six columns offset-by-five">
			<div class="teampic">
				<div class="backpic-square hire">
					?
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				We're Hiring
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Shit hot web devs / designers</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=brandid" class="twitter-mention-button" data-related="male,4nkush">Tweet to @brandid</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Want to be part of an awesome growing startup? We're hiring Magento developers, web and mobile designers and front-end engineers. Get in touch via twitter or <a href="mailto:help@getbrandid.com">email us</a> your github profile or portfolio.<br/><br/>Recruiters will be marked as spam.
				</span>
			</div>
		</div>
	</div>
	<div class="row">
		<br/><br/>
	</div>
	
</div>




