<?php 

Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::getUrl("plans.html"));

	$refererSet = false;
	if(Mage::getSingleton('core/session')->getReferer()) {
		$refererSet = true;
	}

	if($refererSet) {
		//get the referrer
		if (isset($_SERVER['HTTP_REFERER'])) {
			$referer = $_SERVER['HTTP_REFERER'];
		} else {
			$referer = "unknown";
		}
		//save it in a session variable
		Mage::getSingleton('core/session')->setReferer($referer); // store session data
	}
	else {
		$referer = Mage::getSingleton('core/session')->getReferer();
	}
	
?>

<div id="top" class="ghost-header"></div>
<div class="share-header clearfix">
	<div class="trans-back"></div>
	<div class="share-header-container container clearfix">
			<a id="logo" href="/" class="logo-button">
				<div class="gift-logo">
				</div>
			</a>
		<nav>
			<select onchange="window.open(this.options[this.selectedIndex].value,'_top')">
			    <option value="" selected="selected">Navigate</option>
			    <option value="/">Home</option>
			    <option value="http://www.getbrandid.com/customer/account/login">Login</option>
			    <option value="/keep/calm/accessallareas">Press</option>
			    <option value="http://blog.getbrandid.com/">Blog</option>
			  </select>
		</nav>

		<div id="wide-nav">
			<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) {?>
				<div class="top-name">
					
					<!--oneall thumbnail -->
					<?php // TODO put this in the module code
					
					$customerID = Mage::getSingleton('customer/session')->getId();
					//check if user has a Facebook ID or twitter ID
					$model = Mage::getModel('oneall/identifiers');
					$collection = $model->getCollection()
						->addFieldToFilter('customer_id',$customerID)
						->addFieldToFilter('provider',array('in' => array('Facebook','twitter')));
					foreach($collection as $item) {
					   if($item['provider'] === 'Facebook') {
			   				$facebookID = $item['identifier'];
			   			}
			   			else if($item['provider'] === 'twitter') {
			   				$twitterID = $item['profile_name'];
			   			};
					   
					}
					
					
					if(isset($facebookID)) { ?>
						<img class="oaimg" width="50" height="50" src="https://graph.facebook.com/<?php echo $facebookID ?>/picture?type=square" />
					<?php  } else if(isset($twitterID)) { ?>
						<img class="oaimg" width="50" height="50" src="https://api.twitter.com/1/users/profile_image?screen_name=<?php echo $twitterID ?>&size=normal" />
					<?php
					} else {
					?><style type"text/css">.top-header .account-link a.header-link { padding-right:0px; }</style><?php
					}
					?>
					
					<?php // Mage::helper('oneall')->getThumbnailUrl(); ?>
					<!--oneall thumbnail -->
					

				</div>

				<div class="account-link">
					<a class="header-link" href="/customer/account/index/">My Account</a>
					<?php $customerName = Mage::helper('customer')->getCustomerName(); 
						$names = explode(" ",$customerName, 2);
						$firstname = $names[0];
					
					?> 						
					<a class="flname" href="#">Hi <?php echo $firstname; ?></a>						
										
				
				</div>
				
			<?php }
				else { ?>
					<div id="oa_social_login_header_convert" class="loading"></div>
				<span></span>	
					<script type="text/javascript">
						 oneall.api.plugins.social_login.build("oa_social_login_header_convert", {
						  'providers' :  ['facebook', 'twitter'],
						  'callback_uri': '<?php echo $this->getUrl('arush-oneall/rpx/token_url', array('_forced_secure' => false)) ?>',
						  'css_theme_uri': '<?php echo $this->getSkinUrl(); ?>css/social-convert-head.css',
						  'events' :{
							        'onload' : function(){jQuery('#oa_social_login_header_convert').removeClass('loading');}   
							      } 
						 });
					</script>
					
			<?php } ?>
						
			<div class="convert">
				<a id="header-convert" href="/plans.html" class="convert">View Plans</a>
			</div>
			<a id="blog" href="http://blog.getbrandid.com/" class="header-button">
				<span class="button-copy">Blog</span>
			</a>
			<a id="who" href="/keep/calm/wearepros" class="header-button">
				<span class="button-copy">Who?</span>
			</a>
			<a id="what" href="/keep/calm/signmeup#mags" class="header-button">
				<span class="button-copy">What?</span>
			</a>
			<a id="how-but" href="/keep/calm/signmeup#1" class="header-button">
				<span class="button-copy">How?</span>
			</a>
			<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) {?>
				<span style="
				    float: right;
				    clear: both;
				    margin-top: -23px;
				    margin-right: 14px;
					" class="login">or <a style="text-decoration:underline;" href="/customer/account/login">Login</a>
				</span>
			<?php } ?>
		</div>
	</div>
	
</div>

<div class="sixteen columns title-block first">
	<div class="title-block-inner clearfix">
		<div class="title-block-container clearfix">		
			<div class="title">
				<span class="first">Keep Calm.</span><br/>
				<span class="second">We're professionals.</span>
			</div>
			
		</div>
	</div>
</div>
<div class="container">

	<div class="sixteen columns commitment-caption">
		<div class="commitment-caption">
			<span class="caption">Our team is the perfect mix of tech startup, retail, fashion, branding and comms entrepreneurs.<br/>And we are deadly serious about solving clothing shopping for men. Forever.<br/><br/><a href="/keep/calm/accessallareas">Click here for our Press page</a></span>
		</div>
	</div>

	<div class="row">
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/ankushsquare.jpg" width="150" height="150" alt="Team Photo of Ankush Sehgal"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>" alt="Team Photo of Ankush Sehgal"/>
				</div>
			</div>
			<span class="vision-title-text">
				Ankush Sehgal
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Co-founder / CEO / Buying / Sales</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=4nkush" class="twitter-mention-button" data-related="getbrandid">Tweet to @4nkush</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Ankush’s experience in retail spans eight years, and varies from working on the shop- floor to founding retail pop-up concept ‘I Love Brands’, in 2009. During which time he developed relationships and supply networks with some of the biggest brands including Armani, Dolce & Gabbana and Calvin Klein. Previously he worked in FX Sales at Deutsche Bank.
				</span>
			</div>
		</div>
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/arushsquare.jpg" alt="Team Photo of Arush Sehgal"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>" alt="Team Photo of Arush Sehgal"/>
				</div>
			</div>
			<span class="vision-title-text">
				Arush Sehgal
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Co-founder / CTO / Design / Engineering </span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=ldn_tech_exec" class="twitter-mention-button" data-related="getbrandid">Tweet to @ldn_tech_exec</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Arush is a consumer web tech evangelist, active open source contributor, designer, developer, project manager with a background in retail. An ex-Deloitte tech consultant, he has worked built systems for johnlewis.com, The Disney Store, Sony, Lloyds TSB Corporate Markets and Phonographic Performance Limited.
				</span>
			</div>
		</div>

		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/gabbisquare.jpg" alt="Team Photo of Gabbi Cahane"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Gabbi Cahane
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">MR Brand Activation</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=gabbicahane" class="twitter-mention-button" data-related="getbrandid">Tweet to @gabbicahane</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Gabbi founded his first marketing firm aged 23. His work for brands including DHL, Financial Times, Shell, Unilever, Warner Music, Umbro, Ladbrokes, Penguin Books, Novartis and Sony has covered almost every marketing and communications discipline in pretty much every sector and spanned most geographic regions.
				</span>
			</div>
		</div>

	</div>
	<div class="row">
		<br/><br/>
	</div>
	<div class="row">
		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/philsquare.jpg" width="150" height="150" alt="Team Photo of Philip Sheldrake"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Philip Sheldrake
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">SOCIAL / DIGITAL / COMMUNITY / PR</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=sheldrake" class="twitter-mention-button" data-related="getbrandid">Tweet to @sheldrake</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Philip co-founded, built and sold an award-winning PR consultancy, was the CEO of Nochex, Europe’s first e- payment service, and co-founded OnOneMap, Europe’s first Google Maps mashup.
					He authored The Business of Influence, Wiley, April 2011, and the Digital Marketing chapter of The Marketing Century.
					He is a founding member of the CIPR’s social media panel and leads its policy group on campaign measurement and evaluation. He sits on the board of Intellect & 6UK.
				</span>
			</div>
		</div>

		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/monsquare.jpg" alt="Team Photo of Monica Durden"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Monica Durden
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Wing girl</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=monicarosed" class="twitter-mention-button" data-related="getbrandid">Tweet to @monicarosed</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Monica’s experience includes creative production and account management roles at agencies VCCP, Intro and Exposure; campaigns for Levi’s, O2, Agent Provocateur, TK Maxx and Converse; and projects for publishers including Hachette Filipacchi, Conde Nast and IPC. She managed the in-house creative team for MSHK producing global content, product and campaigns for their stable of brands including Ministry of Sound, Hed Kandi, Global Underground and Data Records.
				</span>
			</div>
		</div>

		<div class="one-third column">
			<div class="teampic">
				<div class="backpic-square">
					<img src="http://brandid.s3.amazonaws.com/simonsquare.jpg" alt="Team Photo of Simon Huhtala"/>
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				Simon Huhtala
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Professor of Post Production</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=huhtala" class="twitter-mention-button" data-related="getbrandid">Tweet to @huhtala</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Simon’s early career was spent in Milan collaborating with renowned directors such as Gabrielle Salvatores, Roman Polanski and Tarsem pioneering new visual technology and techniques in post production.
					As MD of boutique London facility Clear Post Production, he refocused the business, returned it to profitability and sold it to Prime Focus.
					At Prime Focus he was responsible for clients ranging from the BBC, VW, Head & Shoulders, 118 118, P&G and supervised one of Burberry’s most ambitious online campaigns ever.
				</span>
			</div>
		</div>
	</div>
	<div class="row">
		<br/>
	</div>
	<div class="row">
		<div class="six columns offset-by-five">
			<div class="teampic">
				<div class="backpic-square hire">
					?
				</div>
				<div class="picframe">
					<img src="<?php echo $this->getSkinUrl('images/arush/circleframe.png');?>"/>
				</div>
			</div>
			<span class="vision-title-text">
				We're Hiring
			</span>
			<div class="commitment-caption">
				<span class="caption jobtitle">Shit hot web devs / designers</span><br/>
				<a href="https://twitter.com/intent/tweet?screen_name=getbrandid" class="twitter-mention-button" data-related="ldn_tech_exec,4nkush">Tweet to @getbrandid</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="jobtitle-container">
				<span class="hood-explanation">
					Want to be part of an awesome growing startup? We're hiring Magento developers, web and mobile designers and front-end engineers. Get in touch via twitter or <a href="mailto:help@getbrandid.com">email us</a> your github profile or portfolio.
				</span>
			</div>
		</div>
	</div>
	<div class="row">
		<br/><br/>
	</div>
	
</div>

	<div class="grey-tilt-holder vision-block">
		<div class="grey container">

			<div class="grey-tilt clearfix">
					<div class="vision clearfix">
						<div class="vision-title">
							<span class="vision-title-text">Our Vision</span>
						</div>
						<div class="eight columns">
							<div class="mandate box">
								<span class="vision-sub-title">Our <span class="red-text">Man</span>date</span>
								<div class="mandate-one-line block">
									We are reinventing shopping for men because the industry has forgotten about us.
									Why should we have to sift through poncy female-focused fashionista content just to get our clothes delivered? It's time to <a href="https://www.youtube.com/watch?v=aaas7GFbLHk&feature=related" target="_blank">take the power back.</a>
									<!-- if you're reading this, watch this one from '92! http://www.youtube.com/watch?v=cPHEgpWhkuQ&feature=related -->
								</div>
							</div>
						</div>
						<div class="eight columns">

							<div class="what-is box">
								<span class="vision-sub-title">What is BRANDiD?</span>
								<div class="what-is-oneliner">
									BRANDiD is an online subscription service for all the things men need, starting with designer basics such as underwear, socks, tees and shirts from the likes of Calvin Klein, Hugo Boss and Ralph Lauren. Select, subscribe, sorted.
								</div>
							</div>
						</div>
					</div>
			</div> <!-- end grey tilt -->
		</div>
	</div>


