<!-- hide password fields and create a random password for gigya socialize users -->
<script type="text/javascript">

	var gs4m_passchar_groups=['abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ','01234567890','!@$^*'];
	var gs4m_pass='';

	$R(1,7+Math.floor(Math.random() * 4)).each(function(i) {
		var char_group=gs4m_passchar_groups[Math.floor(Math.random() * gs4m_passchar_groups.length)];
		gs4m_pass += char_group.charAt(Math.floor(Math.random() * char_group.length));
	});
	
	$('password').up('.fieldset').hide();
	$('password','confirmation').each(function(el){
											el.value=gs4m_pass;
											el.hide();
									   });
</script>