<?php
/**
 * @see Mage_Catalog_Block_Product_View
 */
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
?>
<?php if (count($_tierPrices) > 0 && 1 == 2): ?>
    <ul class="tier-prices product-pricing">
    <?php foreach($_tierPrices as $_price): ?>
        <li><?php echo $this->__('Buy %1$s with %2$s discount each', $_price['price_qty'], '<strong class="benefit">'.($_price['price']*1).'%</strong>') ?></li>
    <?php endforeach ?>
    </ul>
<?php endif;?>
<ul class="quickie-tier-prices">
	<li><span><?php echo $this->__('1')?></span>x<br /><span><?php echo $this->__('for one night stands');?></span></li>
	<li><span><?php echo $this->__('2')?></span>x<br /><span><?php echo $this->__('\'cos all good things come in threes');?></span></li>
	<li><span><?php echo $this->__('3')?></span>x<br /><span><?php echo $this->__('to impress that fit bird at work');?></span></li>		
</ul>
<script type="text/javascript">
	document.observe('dom:loaded', function(){
		$$('ul.quickie-tier-prices li').each(function(obj){
			obj.observe('mouseover', function(){
				if (this.getStyle('background-color') != '#d2002b') {
					this.setStyle({ backgroundColor: '#000000' });				
				}

			});
			obj.observe('mouseout', function(){
				if (this.getStyle('background-color') != '#d2002b') {
					this.setStyle({ backgroundColor: '#595959' });
				}
			});

			obj.observe('click', function(){
				if (!$$('.input-text.qty')[0].hasClassName('qty-disabled')) {
					this.up().select('li').each(function(o){
						o.setStyle({ backgroundColor: '#595959', cursor: 'pointer' });
					});
					this.setStyle({ backgroundColor: '#d2002b', cursor: 'default' });

					$$('.input-text.qty')[0].value = this.select('span')[0].innerHTML;	
					jQuery($$('.input-text.qty')[0]).keyup();		
				}

			});			

		
		});
	});
</script>
<style type="text/css">
.quickie-tier-prices {
/* 	clear: both; */
	float: left;
}

.quickie-tier-prices li {
	background-color: #595959;
	width: 106px;
	padding: 10px;
	cursor: pointer;
	float: left;
	margin-right: 10px;
	text-align: center;
}
</style>