<?php $_product = Mage::getModel('catalog/product')->load(Mage::registry('current_product')->getId());?>
<?php $_helper = $this->helper('catalog/output'); ?>

<div class="sliders">
<?php
$pieces = array(
	'Socks'		=> 'SOCKS',
	'Boxers'	=> 'BOXERS',
	'T-Shirts'	=> 'T-SHIRT',
	'Shirts'	=> 'SHIRT'
);
$relatedProductIds = array();
foreach($_product->getRelatedLinkCollection() as $related) {
	$relatedProductIds[] = $related->getLinkedProductId();
}
?>
<?php
foreach ($pieces as $k => $v) {
	$products = Mage::getModel('catalog/product')
		->getCollection()
		->addAttributeToSelect('*')
		->addAttributeToFilter('rmscategory', $v)
		->addAttributeToFilter('entity_id', array('in' => $relatedProductIds));	

if ($products->count() > 0){ ?>
<div id="planOther">
	<h1 class="black-title-bar"><?php echo $this->__($k);?></h1>	
	<div class="holder">
	
		<div class="slider">
			<ul>
			<?php foreach($products as $product): ?>
				<li>
					<img src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(191, 155);?>" width="191" height="155" />
					<span class="black-title-small"><?php echo $product->getAttributeText('brand'); ?></span>
					<span><?php echo Mage::helper('core')->currency($product->getPrice(), true); ?></span>
				</li>
			<? endforeach ?>
			</ul>
		</div>
		<div class="left"></div>		
		<div class="right"></div>	
	</div>
</div>
<?php 
	};
}
?>
</div>
<div class="plan product-info">
    <div class="container2">
    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
    </div>
    <div class="add-to-box">
        <?php echo $this->getChildHtml('addtocart') ?>
        <?php echo $this->getChildHtml('addto') ?>
		<div class="delivery-date"><?php
		$profile = Mage::helper('randomquote')->getProfileDate();
		echo $this->__('Your plan will be delivered on <span>%s</span>', $profile['delivery_date']);
		?>
		</div>        
    </div>
    <div class="extra-info">
    	<ul>
			<?php if ($_helper->productAttribute($_product, $_product->getName(), 'freeshipping') != ''): ?>
    		<li><?php echo $this->__('Free delivery'); ?></li>
			<?php endif; ?>	
    	</ul>
    </div>
</div>
<?php
$upsells = $_product->getUpSellProductCollection()->addAttributeToSort('position', 'asc');
if ($upsells->count() > 0):
?>
<div class="upsells">
	<h1 class="black-title-bar"><?php echo $this->__('Our Plans'); ?></h1>
	<ul>
	<?php foreach($upsells as $upsell): ?>
		<?php $upsellProduct = Mage::getModel('catalog/product')->load($upsell->getId()); ?>
		<li>
			<h3><span class="title">the</span><? echo $upsellProduct->getName(); ?></h3>
			<span class="price"><?php echo Mage::helper('core')->currency($upsellProduct->getPrice());?></span><br />
			<span class="special-price"><?php echo Mage::helper('core')->currency($upsellProduct->getSpecialPrice());?></span>
			<button class="button"><span><span><?php echo $this->__('View plan'); ?></span></span></button>
		</li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>


<script type="text/javascript">

	$('product-options-wrapper').select('label').each(function(obj){
		if (obj.innerHTML.toLowerCase().indexOf('sock') >= 0) {
			obj.up().next().addClassName('sock-bg');
		} else if (obj.innerHTML.toLowerCase().indexOf('t-shirt') >= 0) {
			obj.up().next().addClassName('tshirt-bg');	
		} else if (obj.innerHTML.toLowerCase().indexOf('boxer') >= 0) {
			obj.up().next().addClassName('boxer-bg');		
		} else if (obj.innerHTML.toLowerCase().indexOf('shirt') >= 0) {
			obj.up().next().addClassName('shirt-bg');		
		}
	});


	
</script>