<div class="custom-plan"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('custom-plan')->toHtml() ?></div>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>    
<?php if($_productCollection->count()): ?>
<?php $counter = $_productCollection->count(); ?>

<?php /* gift page */
	$category = Mage::registry('current_category');
	$giftCategory = false;
	if($category) {
		$categoryId = $category->getId();
		if($categoryId ==135){ $giftCategory = true;}
	}
?>


<?php // echo  $this->getLayout()->createBlock('cms/block')->setBlockId('next-delivery-drop')->toHtml() ; ?>



<ul class="plans-list clearfix">
	<?php foreach($_productCollection as $product):?>
	
	<?php
		$_productName = strtolower($product->getName());
	
		$god   = 'godfather';
		$boss = 'boss';
		$soldier = 'soldier';

		$containsGod = strpos($_productName, $god);
		$containsBoss = strpos($_productName, $boss);
		$containsSoldier = strpos($_productName, $soldier);

		if($containsBoss !== false) {
			$maleRecommendsId = $boss;
		}
		else if($containsGod !== false)	{
			$maleRecommendsId = $god;
		}
		else {
			$maleRecommendsId = $soldier;
		}
	?>


	<?php $counter--;?>
	<li<?php echo ($counter == 0) ? ' class="last"': ''; ?>>
		<!-- div class="discount-triangle-container">
			<span class="discount-number"<?php // if($_earner == 1) {echo ' style="margin:0 0 0 8px;"';} ?>><?php // echo $_earner; ?>x POINT<?php // if($_earner > 1) {echo 'S';} ?></span>
			<span class="discount-label">PER £1</span>
		</div>

		<div class="discount-triangle">
		</div-->		
		<div class="male-recommends ani" id="male-<?php echo $maleRecommendsId ?>">
			<div class="male-recommends-circle">
			</div>
			<div class="male-recommends-circle whiteoutline">
			</div>
			<div class="male-recommends-circle redoutline">
			</div>
			<div class="recommends-text">
				<span class="first">
					M.A.L.E.
				</span><br/>
				<span class="second">
					Recommends
				</span>
			</div>
		</div>

		<!-- script to enable recommendation -->
		<script type="text/javascript">
			var $j = jQuery.noConflict();
			
			//check if punter exists first
			createPunter();
			if(punter != null) {
				$j('#male-'+punter.recommended).css('display','block');
				$j('#male-'+punter.recommended).addClass('flash');
			}


				
		</script>

		
		<?php if($giftCategory == true) { ?>
		
			<h3><span class="plan-category-grid-title"><?php echo $product->getName(); ?></span></h3>
			<!-- span class="rrp">RRP <?php /*
			
 			 $_rrp = $product->getGiftRrp();
 			 echo Mage::helper('core')->currency($_rrp,true,false);  
			 */
			 ?></span-->
			<span class="special-price">Gift Price &pound;<?php echo number_format($product->getSpecialPrice(),0);?>
			</span>

			<div class="plan-checks clearfix">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('plan-text-' . $product->getSku())->toHtml(); ?>
			</div>

		<?php } 
		else { ?>
			
			<h3><span class="the"></span><span class="plan-category-grid-title"><?php echo $product->getName(); ?></span></h3>
			<!--span class="rrp">RRP &pound;<?php // echo number_format($product->getPrice(),0);?></span-->
			<span class="special-price">From &pound;<?php echo number_format($product->getSpecialPrice(),0);?>
				<span class="per-month">per delivery</span>
			</span>
		
		<?php }	?>
			
		<a class="convert plan-button" href="<?php echo $product->getProductUrl(); ?>">
			<span class="choose-plan-text"><?php echo $this->__('View plan'); ?></span>
		</a>
		
		<!--
<br/><br/>
		<?php /* echo 'socks '. $product->getNumSocks(); echo 'tees '. $product->getNumTshirts(); echo 'boxers '. $product->getNumBoxers(); echo 'shirts '. $product->getNumShirts();   */ ?>
		<br/><br/>
-->
		
		<div class="plan-graphics">
			
			<?php if ($product->getNumSocks() && $product->getNumSocks() > 0): ?><div class="package-desc socks"><?php echo $product->getNumSocks(); ?>x</div><?php endif; ?>
			<?php if ($product->getNumTshirts() && $product->getNumTshirts() > 0): ?><div class="package-desc tshirts"><?php echo $product->getNumTshirts(); ?>x</div><?php endif; ?>
			<?php if ($product->getNumBoxers() && $product->getNumBoxers() > 0): ?><div class="package-desc boxers"><?php echo $product->getNumBoxers(); ?>x</div><?php endif; ?>
			<?php if ($product->getNumShirts() && $product->getNumShirts() > 0): ?><div class="package-desc shirts"><?php echo $product->getNumShirts(); ?>x</div><?php endif; ?>		
		</div>
		
		
		<div class="plan-checks">
		<?php if($giftCategory == true) { ?>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('plan-text-gift')->toHtml(); ?>
		<?php } 
		else { ?>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('plan-text-' . $product->getSku())->toHtml(); ?>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('plan-text-common')->toHtml(); ?>
		<?php }	?>
		
		</div>
		
	</li>
	<?php endforeach;?>
</ul>
<?php endif; ?>


