<?php
Mage::helper('recurly')->config();
$customerId = Mage::getSingleton('customer/session')->getId();
$customerEmail = Mage::getModel('customer/customer')->load($customerId)->getEmail();
$sku = Mage::helper('recurly')->getSku();
$onceOff = $this->_isOnceOff();
$signature = $onceOff ? Mage::helper('recurly')->signOneTimeTransaction($customerId)  : Mage::helper('recurly')->signSubscription($sku, $customerId);
Mage::getSingleton('core/session')->setSignature($signature);
var_dump($onceOff);
?>
<script type="text/javascript">

document.observe('dom:loaded', function(){

	loadRecurly(
		'<?php echo Mage::helper('recurly')->getSubdomain(); ?>'
		, '<?php echo Mage::helper('recurly')->getCurrency(); ?>'
		, '<?php echo Mage::helper('recurly')->getCountry(); ?>'
		, '<?php echo $sku; ?>'
		, '<?php echo $customerId; ?>'
		, '<?php echo Mage::getBaseUrl() . 'recurly/callback/success/'; ?>'
		, '<?php echo $customerEmail; ?>'
		, '<?php echo $signature; ?>'
		, '<?php echo ($onceOff) ? 'once-off' : 'subscription'; ?>'
	);
});
</script>
