// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.magsQ = function() {
    var q;
    wipeConsole();
    saveProgress("magsQ");
    q = "What magazines do you read? ";
    newQ(q);
    typeit();
    return insertMagsField();
  };

}).call(this);
