// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.rollQ = function() {
    var q, s;
    wipeConsole();
    saveProgress("rollQ");
    q = "How do you roll? ";
    newQ(q);
    typeit();
    s = $j("#male-welcome-msg");
    return rollImages(s);
  };

  root.rollDone = function() {
    newQ("Got it. ");
    typeit();
    return setTimeout((function() {
      return insertContinue("rollQ()");
    }), 500);
  };

  root.rollAa = function() {
    punter.roll = "shirts";
    wipeConsole();
    return rollDone;
  };

  root.rollAb = function() {
    punter.roll = "polos";
    wipeConsole();
    return rollDone;
  };

  root.rollAc = function() {
    punter.roll = "tees";
    wipeConsole();
    return rollDone;
  };

  root.rollAd = function() {
    punter.roll = "elvis";
    wipeConsole();
    return rollDone;
  };

}).call(this);
