// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.shirtsQ = function() {
    var q, s;
    wipeConsole();
    saveProgress("shirtsQ");
    if (punter.workShirts || punter.playShirts) {
      if (punter.workShirts) {
        q = "So you wear shirts for work";
        if (punter.playShirts) {
          q += " and play.";
        } else {
          q += ".";
        }
      } else if (punter.playShirts) {
        q = "So you wear shirts for play.";
      }
      q += "\n\nWhat kind of shirts do you wear? ";
    } else {
      return tees();
    }
    newQ(q);
    typeit();
    s = $j("#male-welcome-msg");
    return shirtsImages(s);
  };

  root.shirtsDone = function() {
    newQ("All good. Let's save your progress again. ");
    typeit();
    return setTimeout((function() {
      return insertContinue("emailPrompt(punter.email)", "save progress");
    }), 1500);
  };

  root.shirtsAa = function() {
    punter.shirts = "private jet";
    wipeConsole();
    return shirtsDone();
  };

  root.shirtsAb = function() {
    punter.shirts = "business class";
    wipeConsole();
    return shirtsDone();
  };

  root.shirtsAc = function() {
    punter.shirts = "economy";
    wipeConsole();
    return shirtsDone();
  };

  root.shirtsAd = function() {
    punter.shirts = "bus";
    wipeConsole();
    return shirtsDone();
  };

}).call(this);
