// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.watchQ = function() {
    var q;
    wipeConsole();
    saveProgress("watchQ");
    q = "What are your favourite TV shows? ";
    newQ(q);
    typeit();
    return insertTvField();
  };

}).call(this);
