// Generated by CoffeeScript 1.4.0
(function() {
  var app, auth, express, port, xmlBodyParser;

  xmlBodyParser = require('custom_modules/xmlBodyParser/xmlBodyParser');

  express = require('express');

  port = 3000;

  app = express();

  auth = express.basicAuth('yourmom', 'p4ssw0rd');

  app.configure(function() {
    return app.use(xmlBodyParser.xmlBodyParser);
  });

  app.post('/', auth, function(req, res) {
    var responseData;
    responseData = req.body;
    console.dir(req.body);
    res.contentType("application/json");
    return res.send(req.body, 200);
  });

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
